aPackageInfo = [
	:name = "The stzlib Package",
	:description = "Our stzlib package using the Ring programming language",
	:folder = "stzlib",
	:developer = "Mansour Ayouni",
	:email = "kalidianow@gmail.com",
	:license = "MIT License",
	:version = "0.9",
	:ringversion = "1.21",
	:versions = 	[
		[
			:version = "0.9",
			:branch = "master"
		]
	],
	:libs = [
		[
			:name = "ringqt",
			:version = "1.0",
			:providerusername = "ringpackages"
		],
		[
			:name = "stdlib",
			:version = "1.0",
			:providerusername = "ringpackages"
		]
	],
	:files = [
		"lib.ring",
		"main.ring",
		"setup.ring",
		"uninstall.ring",
		"LICENSE",
		"README.md",
		"common/stzCounter.ring",
		"common/stzFunctions.ring",
		"common/stzOccurrences.ring",
		"common/stzParser.ring",
		"common/stzParser2.ring",
		"common/stzQtFunc.ring",
		"common/stzRingLibs.ring",
		"common/stzSection.ring",
		"common/stzSmallFunc.ring",
		"common/stzSplitter.ring",
		"common/stzWalker.ring",
		"common/stzWalkerDoc.ring",
		"core/common/stkListCommons.ring",
		"core/common/stkLowLevelFuncs.ring",
		"core/common/stkNumberCommons.ring",
		"core/common/stkObjectCommons.ring",
		"core/common/stkRingFuncs.ring",
		"core/common/stkRingLibs.ring",
		"core/common/stkStringCommons.ring",
		"core/doc/stkNumberDoc.ring",
		"core/error/stkError.ring",
		"core/list/stkList.ring",
		"core/number/stkBigNumber.ring",
		"core/number/stkkSafeNumber.ring",
		"core/number/stkListOfNumbers.ring",
		"core/number/stkNumber.ring",
		"core/number/stkSciNumber.ring",
		"core/object/stkObject.ring",
		"core/stkLib.ring",
		"core/string/stkBoxedString.ring",
		"core/string/stkChar.ring",
		"core/string/stkString.ring",
		"core/string/stkStringArt.ring",
		"core/stzCoreLib.ring",
		"core/temp/tempo.ring",
		"core/test/stkBigNumberTest.ring",
		"core/test/stkBoxedStringTest.ring",
		"core/test/stkCharTest.ring",
		"core/test/stkErrorTest.ring",
		"core/test/stkListTest.ring",
		"core/test/stkNumberTest.ring",
		"core/test/stkSciNumberTest.ring",
		"core/test/stkStringArtTest.ring",
		"core/test/stkStringTest.ring",
		"data/stzCharData.ring",
		"data/stzConstraintsData.ring",
		"data/stzLocaleData.ring",
		"data/stzRandomData.ring",
		"data/stzStopWordsData.ring",
		"data/stzStringData.ring",
		"data/stzUnicodeData.ring",
		"data/stzUnicodeData.txt",
		"Doc/narration-softanza-conditional-code.txt",
		"Doc/replacing_substrings_inside_listofstrings.docx",
		"Doc/stz-features.txt",
		"Doc/stz-sort-functions.txt",
		"Doc/stz_code_explained_by_claude_ai.pdf",
		"Doc/stz_code_explained_by_gemini_ai.pdf",
		"Doc/testimonials.txt",
		"Doc/walkers-Checkers-Yielders-and-Performers.txt",
		"error/stzBinaryNumberError.ring",
		"error/stzCharError.ring",
		"error/stzCounterError.ring",
		"error/stzCountryError.ring",
		"error/stzCurrencyError.ring",
		"error/stzDecimalToBinaryError.ring",
		"error/stzEntityError.ring",
		"error/stzFileError.ring",
		"error/stzGridError.ring",
		"error/stzHexNumberError.ring",
		"error/stzLanguageError.ring",
		"error/stzListError.ring",
		"error/stzListOfBytesError.ring",
		"error/stzListOfCharsError.ring",
		"error/stzListOfEntitiesError.ring",
		"error/stzListOfSetsError.ring",
		"error/stzListOfStringsError.ring",
		"error/stzLocaleError.ring",
		"error/stzMultiStringError.ring",
		"error/stzNumberError.ring",
		"error/stzObjectError.ring",
		"error/stzOctalNumberError.ring",
		"error/stzScriptError.ring",
		"error/stzSetError.ring",
		"error/stzStringError.ring",
		"error/stzTextEncodingSystemError.ring",
		"extended/i18n/stzCounterTest.ring",
		"extended/i18n/stzCountry.ring",
		"extended/i18n/stzCurrency.ring",
		"extended/i18n/stzDate.ring",
		"extended/i18n/stzLanguage.ring",
		"extended/i18n/stzLocale.ring",
		"extended/i18n/stzScript.ring",
		"extended/i18n/stzStopWords.ring",
		"extended/i18n/stzTime.ring",
		"extended/natural/stzCCode.ring",
		"extended/natural/stzChainOfTruth.ring",
		"extended/natural/stzChainOfValue.ring",
		"extended/natural/stzConstraints.ring",
		"extended/natural/stzEntity.ring",
		"extended/natural/stzFalseObject.ring",
		"extended/natural/stzListOfEntities.ring",
		"extended/natural/stzNaturalCode.ring",
		"extended/natural/stzNullObject.ring",
		"extended/natural/stzText.ring",
		"extended/natural/stzTrueObject.ring",
		"extended/plugins/plugin_string_countVowels.ring",
		"extended/plugins/plugin_string_removeNonLetters.ring",
		"extended/plugins/plugin_string_replace.ring",
		"extended/plugins/plugin_string_reverse.ring",
		"extended/systems/stzArchitectureSystem.ring",
		"extended/systems/stzArchSys.ring",
		"extended/systems/stzCoordinateSystem.ring",
		"extended/systems/stzErrorSystem.ring",
		"extended/systems/stzErrSys.ring",
		"extended/systems/stzEventSystem.ring",
		"extended/systems/stzEvtSys.ring",
		"extended/systems/stzPluginSystem.ring",
		"extended/systems/stzPlugSys.ring",
		"extended/systems/stzProfilingSystem.ring",
		"extended/systems/stzProfSys.ring",
		"extended/systems/stzRingInstance.ring",
		"extended/systems/stzRingStateSystem.ring",
		"extended/systems/stzShowSys.ring",
		"extended/systems/stzShowSystem.ring",
		"extended/systems/stzStateSys.ring",
		"extended/systems/stzStateSystem.ring",
		"extended/systems/stzTextEncodingSystem.ring",
		"extended/systems/stzTranslationSystem.ring",
		"extended/systems/stzTransSys.ring",
		"io/stzExtCode.ring",
		"io/stzFile.ring",
		"io/stzFolder.ring",
		"list/stzGrid.ring",
		"list/stzHashList.ring",
		"list/stzItem.ring",
		"list/stzList.ring",
		"list/stzListInString.ring",
		"list/stzListOfGrids.ring",
		"list/stzListOfHashlists.ring",
		"list/stzListOfLists.ring",
		"list/stzListOfPairs.ring",
		"list/stzListOfSets.ring",
		"list/stzListOfTables.ring",
		"list/stzListParser.ring",
		"list/stzListProvidedAsString.ring",
		"list/stzPair.ring",
		"list/stzPairOfLists.ring",
		"list/stzSet.ring",
		"list/stzSetTest.ring",
		"list/stzSortedList.ring",
		"list/stzTable.ring",
		"list/stzTree.ring",
		"misc/stzCodeGenerators.ring",
		"misc/stzDistanceZero.ring",
		"number/stzBinaryFile.ring",
		"number/stzBinaryNumber.ring",
		"number/stzDecimalToBinary.ring",
		"number/stzHexNumber.ring",
		"number/stzListOfBytes.ring",
		"number/stzListOfListsOfNumbers.ring",
		"number/stzListOfNumbers.ring",
		"number/stzNumber.ring",
		"number/stzNumberLowLevelType.ring",
		"number/stzOctalNumber.ring",
		"number/stzPairOfNumbers.ring",
		"number/stzRandom.ring",
		"object/stzListOfNamedObjects.ring",
		"object/stzListOfObjects.ring",
		"object/stzObject.ring",
		"string/stzChar.ring",
		"string/stzListOfBoxedStrings.ring",
		"string/stzListOfChars.ring",
		"string/stzListOfStrings.ring",
		"string/stzListOfUnicodes.ring",
		"string/stzMultiString.ring",
		"string/stzString.ring",
		"string/stzStringArt.ring",
		"string/stzStringNeg.ring",
		"string/stzStringXT.ring",
		"string/stzSubString.ring",
		"stzlib.ring",
		"test/stzArchitectureSystemTest.ring",
		"test/stzBinaryNumberTest.ring",
		"test/stzCCodeTest.ring",
		"test/stzChainOfTruthTest.ring",
		"test/stzChainOfValueTest.ring",
		"test/stzCharDataTest.ring",
		"test/stzCharTest.ring",
		"test/stzconstraintsTest.ring",
		"test/stzCountryTest.ring",
		"test/stzCurrencyTest.ring",
		"test/stzDateTest.ring",
		"test/stzDecimalToBinaryTest.ring",
		"test/stzDistanceZeroTest.ring",
		"test/stzEntityTest.ring",
		"test/stzExtCodeTest.ring",
		"test/stzFileTest.ring",
		"test/stzFolderTest.ring",
		"test/stzGlobalSystemTest.ring",
		"test/stzGlobalTest.ring",
		"test/stzGridTest.ring",
		"test/stzHashListTest.ring",
		"test/stzHexNumberTest.ring",
		"test/stzLanguageTest.ring",
		"test/stzListInStringTest.ring",
		"test/stzListOfBytesTest.ring",
		"test/stzListOfCharsTest.ring",
		"test/stzListOfEntitiesTest.ring",
		"test/stzListOfHashListsTest.ring",
		"test/stzListOfListsTest.ring",
		"test/stzListOfNumbersTest.ring",
		"test/stzListOfPairsTest.ring",
		"test/stzListOfSetsTest.ring",
		"test/stzListOfStringsTest.ring",
		"test/stzListOfUnicodesTest.ring",
		"test/stzListParserTest.ring",
		"test/stzListTest.ring",
		"test/stzLocaleTest.ring",
		"test/stzMultiStringTest.ring",
		"test/stzNaturalCodeTest.ring",
		"test/stzNumberTest.ring",
		"test/stzObjectTest.ring",
		"test/stzOctalNumberTest.ring",
		"test/stzPairOfListsTest.ring",
		"test/stzPairTest.ring",
		"test/stzParserTest.ring",
		"test/stzPluginSystemTest.ring",
		"test/stzProfilingSystemTest.ring",
		"test/stzrandomDataTest.ring",
		"test/stzRandomTest.ring",
		"test/stzScriptTest.ring",
		"test/stzSectionTest.ring",
		"test/stzShowSystemTest.ring",
		"test/stzSmallFuncTest.ring",
		"test/stzSortedListTest.ring",
		"test/stzSplitterTest.ring",
		"test/stzStateSystemTest.ring",
		"test/stzStopWordsTest.ring",
		"test/stzStringArtTest.ring",
		"test/stzStringTest.ring",
		"test/stzStringXTTest.ring",
		"test/stzSubStringTest.ring",
		"test/stzTableTest.ring",
		"test/stzTest.ring",
		"test/stzTestTest.ring",
		"test/stzTextEncodingSystemTest.ring",
		"test/stzTextTest.ring",
		"test/stzTimeTest.ring",
		"test/stzTreeTest.ring",
		"test/stzUnicodeDataTest.ring",
		"test/stzWalkerTest.ring"
	],
	:ringfolderfiles = 	[
		"bin/load/stzlib.ring",
		"libraries/stzlib.zip"

	],
	:windowsfiles = 	[

	],
	:linuxfiles = 	[

	],
	:ubuntufiles = 	[

	],
	:fedorafiles = 	[

	],
	:macosfiles = 	[

	],
	:windowsringfolderfiles = 	[

	],
	:linuxringfolderfiles = 	[

	],
	:ubunturingfolderfiles = 	[

	],
	:fedoraringfolderfiles = 	[

	],
	:macosringfolderfiles = 	[

	],
	:run = "ring main.ring",
	:windowsrun = "",
	:linuxrun = "",
	:macosrun = "",
	:ubunturun = "",
	:fedorarun = "",
	:setup = "ring setup.ring",
	:windowssetup = "",
	:linuxsetup = "",
	:macossetup = "",
	:ubuntusetup = "",
	:fedorasetup = "",
	:remove = "ring uninstall.ring",
	:windowsremove = "",
	:linuxremove = "",
	:macosremove = "",
	:ubunturemove = "",
	:fedoraremove = ""
]