aPackageInfo = [
	:name = "The SoftanzaLib Package",
	:description = "Our SoftanzaLib package using the Ring programming language",
	:folder = "SoftanzaLib",
	:developer = "",
	:email = "",
	:license = "MIT License",
	:version = "1.0.0",
	:ringversion = "1.16",
	:versions = 	[
		[
			:version = "1.0.0",
			:branch = "master"
		]
	],
	:libs = 	[
		[
			:name = "ringqt",
			:version = "1.0",
			:providerusername = "ringpackages"
		],
		[
			:name = "stdlib",
			:version = "1.0",
			:providerusername = "ringpackages"
		],
		[
			:name = "internetlib",
			:version = "1.0",
			:providerusername = "ringpackages"
		]
	],
	:files = 	[
		"main.ring",
		"LICENSE",
		"README.md"
	],
	:ringfolderfiles = 	[
		"bin/load/stzlib.ring",
		"libraries/softanzalib/Cache/abc.txt",
		"libraries/softanzalib/Cache/hi.txt",
		"libraries/softanzalib/Cache/mansour-ayouni.lnk",
		"libraries/softanzalib/Cache/mycahe.txt",
		"libraries/softanzalib/Cache/temp1.ring",
		"libraries/softanzalib/Cache/todo-files.txt",
		"libraries/softanzalib/Cache/‰’.txt",
		"libraries/softanzalib/Doc/baba.txt",
		"libraries/softanzalib/Doc/bug-bidirectional-text.PNG",
		"libraries/softanzalib/Doc/CodesOfLanguages.txt",
		"libraries/softanzalib/Doc/find-in-stzlistofstrings.txt",
		"libraries/softanzalib/Doc/stzDocFunctions.ring",
		"libraries/softanzalib/Doc/stzFunctions.ring",
		"libraries/softanzalib/Doc/StzNumberFunctions.ring",
		"libraries/softanzalib/Doc/walkers-Checkers-Yielders-and-Performers.txt",
		"libraries/softanzalib/Doc/xlsfile.xlsx",
		"libraries/softanzalib/Doc/~$xlsfile.xlsx",
		"libraries/softanzalib/Misc/functions.ring",
		"libraries/softanzalib/Misc/links.txt",
		"libraries/softanzalib/SoftanzaLib.ring",
		"libraries/softanzalib/stz.db",
		"libraries/softanzalib/stzActiveItem.ring",
		"libraries/softanzalib/stzAssociativeList.ring",
		"libraries/softanzalib/stzBinaryFile.ring",
		"libraries/softanzalib/stzBinaryNumber.ring",
		"libraries/softanzalib/stzBinaryNumberError.ring",
		"libraries/softanzalib/stzBinaryNumberTest.ring",
		"libraries/softanzalib/stzBit.ring",
		"libraries/softanzalib/stzBoxDraw.ring",
		"libraries/softanzalib/stzByte.ring",
		"libraries/softanzalib/stzCache.ring",
		"libraries/softanzalib/stzChainOfTruth.ring",
		"libraries/softanzalib/stzChainOfTruthTest.ring",
		"libraries/softanzalib/stzChainOfValue.ring",
		"libraries/softanzalib/stzChainOfValueTest.ring",
		"libraries/softanzalib/stzChar.ring",
		"libraries/softanzalib/stzCharData.ring",
		"libraries/softanzalib/stzcharDataTest.ring",
		"libraries/softanzalib/stzCharError.ring",
		"libraries/softanzalib/stzCharTest.ring",
		"libraries/softanzalib/stzCodeGenerators.ring",
		"libraries/softanzalib/stzConstraint.ring",
		"libraries/softanzalib/stzConstraintTest.ring",
		"libraries/softanzalib/stzCoordinateSystem.ring",
		"libraries/softanzalib/stzCounter.ring",
		"libraries/softanzalib/stzCounterError.ring",
		"libraries/softanzalib/stzCounterTest.ring",
		"libraries/softanzalib/stzCountry.ring",
		"libraries/softanzalib/stzCountryError.ring",
		"libraries/softanzalib/stzCountryTest.ring",
		"libraries/softanzalib/stzCurrency.ring",
		"libraries/softanzalib/stzCurrencyError.ring",
		"libraries/softanzalib/stzCurrencyTest.ring",
		"libraries/softanzalib/stzDatabase.ring",
		"libraries/softanzalib/stzDate.ring",
		"libraries/softanzalib/stzDateNative.ring",
		"libraries/softanzalib/stzDecimalToBinary.ring",
		"libraries/softanzalib/stzDecimalToBinaryError.ring",
		"libraries/softanzalib/stzDecimalToBinaryTest.ring",
		"libraries/softanzalib/stzDefaults.ring",
		"libraries/softanzalib/stzDynamicList.ring",
		"libraries/softanzalib/stzEnglishData.ring",
		"libraries/softanzalib/stzEntity.ring",
		"libraries/softanzalib/stzEntityError.ring",
		"libraries/softanzalib/stzEntityTest.ring",
		"libraries/softanzalib/stzEvent.ring",
		"libraries/softanzalib/stzEventManager.ring",
		"libraries/softanzalib/stzFile.ring",
		"libraries/softanzalib/stzFileError.ring",
		"libraries/softanzalib/stzFileTest.ring",
		"libraries/softanzalib/stzFileUsingRing.ring",
		"libraries/softanzalib/stzFolder.ring",
		"libraries/softanzalib/stzFolderTest.ring",
		"libraries/softanzalib/stzFunction.ring",
		"libraries/softanzalib/stzFunctionTest.ring",
		"libraries/softanzalib/stzGeneralFunctions.ring",
		"libraries/softanzalib/stzGeneralFunctionsTest.ring",
		"libraries/softanzalib/stzGlobals.ring",
		"libraries/softanzalib/stzGrid.ring",
		"libraries/softanzalib/stzGridError.ring",
		"libraries/softanzalib/stzGridTest.ring",
		"libraries/softanzalib/stzHashList.ring",
		"libraries/softanzalib/stzHashListTest.ring",
		"libraries/softanzalib/stzHexNumber.ring",
		"libraries/softanzalib/stzHexNumberError.ring",
		"libraries/softanzalib/stzHexNumberTest.ring",
		"libraries/softanzalib/stzInit.ring",
		"libraries/softanzalib/stzItem.ring",
		"libraries/softanzalib/stzItemTest.ring",
		"libraries/softanzalib/stzLanguage.ring",
		"libraries/softanzalib/stzLanguageError.ring",
		"libraries/softanzalib/stzLanguageTest.ring",
		"libraries/softanzalib/stzlib.ring",
		"libraries/softanzalib/stzList.ring",
		"libraries/softanzalib/stzListError.ring",
		"libraries/softanzalib/stzListInString.ring",
		"libraries/softanzalib/stzListInStringTest.ring",
		"libraries/softanzalib/stzListOfBits.ring",
		"libraries/softanzalib/stzListOfBoxedStrings.ring",
		"libraries/softanzalib/stzListOfBytes.ring",
		"libraries/softanzalib/stzListOfBytesError.ring",
		"libraries/softanzalib/stzListOfBytesTest.ring",
		"libraries/softanzalib/stzListOfChars.ring",
		"libraries/softanzalib/stzListOfCharsError.ring",
		"libraries/softanzalib/stzListOfCharsTest.ring",
		"libraries/softanzalib/stzListOfConstraints.ring",
		"libraries/softanzalib/stzListOfConstraintsTest.ring",
		"libraries/softanzalib/stzListOfEntities.ring",
		"libraries/softanzalib/stzListOfEntitiesError.ring",
		"libraries/softanzalib/stzListOfEntitiesTest.ring",
		"libraries/softanzalib/stzListOfHashlists.ring",
		"libraries/softanzalib/stzListOfHashListsTest.ring",
		"libraries/softanzalib/stzListOfLists.ring",
		"libraries/softanzalib/stzListOfListsTest.ring",
		"libraries/softanzalib/stzListOfNumbers.ring",
		"libraries/softanzalib/stzListOfNumbersList.ring",
		"libraries/softanzalib/stzListOfNumbersTest.ring",
		"libraries/softanzalib/stzListOfObjects.ring",
		"libraries/softanzalib/stzListOfPairs.ring",
		"libraries/softanzalib/stzListOfSets.ring",
		"libraries/softanzalib/stzListOfSetsError.ring",
		"libraries/softanzalib/stzListOfSetsTest.ring",
		"libraries/softanzalib/stzListOfStrings.ring",
		"libraries/softanzalib/stzListOfStringsError.ring",
		"libraries/softanzalib/stzListOfStringsOld.ring",
		"libraries/softanzalib/stzListOfStringsTest.ring",
		"libraries/softanzalib/stzListOfUnicodes.ring",
		"libraries/softanzalib/stzListOfUnicodesTest.ring",
		"libraries/softanzalib/stzListOfValues.ring",
		"libraries/softanzalib/stzListParser.ring",
		"libraries/softanzalib/stzListParserTest.ring",
		"libraries/softanzalib/stzListProvidedAsString.ring",
		"libraries/softanzalib/stzListTest.ring",
		"libraries/softanzalib/stzLocale.ring",
		"libraries/softanzalib/stzLocaleAbbreviationString.ring",
		"libraries/softanzalib/stzLocaleAbbreviationStringTest.ring",
		"libraries/softanzalib/stzLocaleError.ring",
		"libraries/softanzalib/stzLocaleTest.ring",
		"libraries/softanzalib/stzMetaCode.ring",
		"libraries/softanzalib/stzMoney.ring",
		"libraries/softanzalib/stzMultilingualString.ring",
		"libraries/softanzalib/stzMultilingualStringError.ring",
		"libraries/softanzalib/stzMultilingualStringTest.ring",
		"libraries/softanzalib/stzMultiString.ring",
		"libraries/softanzalib/stzNaturalCode.ring",
		"libraries/softanzalib/stzNaturalCodeTest.ring",
		"libraries/softanzalib/stzNumber.ring",
		"libraries/softanzalib/stzNumberError.ring",
		"libraries/softanzalib/stzNumberInScientificNotation.ring",
		"libraries/softanzalib/stzNumberLowLevelType.ring",
		"libraries/softanzalib/stzNumberStorage.ring",
		"libraries/softanzalib/stzNumberTest.ring",
		"libraries/softanzalib/stzObject.ring",
		"libraries/softanzalib/stzObjectError.ring",
		"libraries/softanzalib/stzObjectTest.ring",
		"libraries/softanzalib/stzOctalNumber.ring",
		"libraries/softanzalib/stzOctalNumberError.ring",
		"libraries/softanzalib/stzOctalNumberTest.ring",
		"libraries/softanzalib/stzPair.ring",
		"libraries/softanzalib/stzPairOfLists.ring",
		"libraries/softanzalib/stzPairOfListsTest.ring",
		"libraries/softanzalib/stzPairOfNumbers.ring",
		"libraries/softanzalib/stzParser.ring",
		"libraries/softanzalib/stzParser2.ring",
		"libraries/softanzalib/stzParserTest.ring",
		"libraries/softanzalib/stzParser_old.ring",
		"libraries/softanzalib/stzPath.ring",
		"libraries/softanzalib/stzPivotTable.ring",
		"libraries/softanzalib/stzProfiler.ring",
		"libraries/softanzalib/stzQEngine.ring",
		"libraries/softanzalib/StzQtParamMapping.ring",
		"libraries/softanzalib/stzQuery.ring",
		"libraries/softanzalib/stzQueryTest.ring",
		"libraries/softanzalib/stzRingParser.ring",
		"libraries/softanzalib/stzRule.ring",
		"libraries/softanzalib/stzRunTime.ring",
		"libraries/softanzalib/stzRuntimeData.ring",
		"libraries/softanzalib/stzRunTimeTest.ring",
		"libraries/softanzalib/stzScript.ring",
		"libraries/softanzalib/stzScriptError.ring",
		"libraries/softanzalib/stzScriptTest.ring",
		"libraries/softanzalib/stzSet.ring",
		"libraries/softanzalib/stzSetError.ring",
		"libraries/softanzalib/stzSetTest.ring",
		"libraries/softanzalib/stzSplitter.ring",
		"libraries/softanzalib/stzSplitter2Test.ring",
		"libraries/softanzalib/stzSplitterTest.ring",
		"libraries/softanzalib/stzStopWords.ring",
		"libraries/softanzalib/stzStopWordsData.ring",
		"libraries/softanzalib/stzStopWordsTest.ring",
		"libraries/softanzalib/stzStorage.ring",
		"libraries/softanzalib/stzString.ring",
		"libraries/softanzalib/stzStringArt.ring",
		"libraries/softanzalib/stzStringArtTest.ring",
		"libraries/softanzalib/stzStringData.ring",
		"libraries/softanzalib/stzStringError.ring",
		"libraries/softanzalib/stzStringPattern.ring",
		"libraries/softanzalib/stzStringTemplate.ring",
		"libraries/softanzalib/stzStringTest.ring",
		"libraries/softanzalib/stzTable.ring",
		"libraries/softanzalib/stzTableTest.ring",
		"libraries/softanzalib/stzTalkative.ring",
		"libraries/softanzalib/stzTemp.ring",
		"libraries/softanzalib/stzTempFile.ring",
		"libraries/softanzalib/stzTemplate.ring",
		"libraries/softanzalib/stzTest.ring",
		"libraries/softanzalib/stzText.ring",
		"libraries/softanzalib/stzTextEncoding.ring",
		"libraries/softanzalib/stzTextEncodingError.ring",
		"libraries/softanzalib/stzTextEncodingTest.ring",
		"libraries/softanzalib/stzTextFile.ring",
		"libraries/softanzalib/stzTextStream.ring",
		"libraries/softanzalib/stzTextStreamError.ring",
		"libraries/softanzalib/stzTextStreamTest.ring",
		"libraries/softanzalib/stzTextTest.ring",
		"libraries/softanzalib/stzTime.ring",
		"libraries/softanzalib/stzTimeTest.ring",
		"libraries/softanzalib/stzTree.ring",
		"libraries/softanzalib/stzUnicodeBlocks.ring",
		"libraries/softanzalib/stzUnicodeData.ring",
		"libraries/softanzalib/stzUnicodeDataTest.ring",
		"libraries/softanzalib/stzUnicodeNames.ring",
		"libraries/softanzalib/stzWalker.ring",
		"libraries/softanzalib/stzWalkerTest.ring",
		"libraries/softanzalib/stzWarning.ring",
		"libraries/softanzalib/temp/123.txt",
		"libraries/softanzalib/temp/barra.txt",
		"libraries/softanzalib/temp/bazza.txt",
		"libraries/softanzalib/temp/calltree.txt",
		"libraries/softanzalib/temp/folio.txt",
		"libraries/softanzalib/temp/kum.txt",
		"libraries/softanzalib/temp/mandra.txt",
		"libraries/softanzalib/temp/marra.txt",
		"libraries/softanzalib/temp/max.txt",
		"libraries/softanzalib/temp/Qt.txt",
		"libraries/softanzalib/temp/RawnaqNotepadContent.txt",
		"libraries/softanzalib/temp/showtree.txt",
		"libraries/softanzalib/temp/sonwe.txt",
		"libraries/softanzalib/temp/stzTempo1.ring",
		"libraries/softanzalib/temp/stzTempo10.ring",
		"libraries/softanzalib/temp/stzTempo11.ring",
		"libraries/softanzalib/temp/stzTempo12.ring",
		"libraries/softanzalib/temp/stzTempo13.ring",
		"libraries/softanzalib/temp/stzTempo14.ring",
		"libraries/softanzalib/temp/stzTempo15.ring",
		"libraries/softanzalib/temp/stzTempo16.ring",
		"libraries/softanzalib/temp/stzTempo17.ring",
		"libraries/softanzalib/temp/stzTempo18.ring",
		"libraries/softanzalib/temp/stzTempo19.ring",
		"libraries/softanzalib/temp/stzTempo2.ring",
		"libraries/softanzalib/temp/stzTempo20.ring",
		"libraries/softanzalib/temp/stzTempo21.ring",
		"libraries/softanzalib/temp/stzTempo22.ring",
		"libraries/softanzalib/temp/stzTempo23.ring",
		"libraries/softanzalib/temp/stzTempo24.ring",
		"libraries/softanzalib/temp/stzTempo25.ring",
		"libraries/softanzalib/temp/stzTempo26.ring",
		"libraries/softanzalib/temp/stzTempo27.ring",
		"libraries/softanzalib/temp/stzTempo3.ring",
		"libraries/softanzalib/temp/stzTempo4.ring",
		"libraries/softanzalib/temp/stzTempo5.ring",
		"libraries/softanzalib/temp/stzTempo6.ring",
		"libraries/softanzalib/temp/stzTempo7.ring",
		"libraries/softanzalib/temp/stzTempo8.ring",
		"libraries/softanzalib/temp/stzTempo9.ring",
		"libraries/softanzalib/temp/stzTextStreamXT.ring",
		"libraries/softanzalib/temp/temp100.ring",
		"libraries/softanzalib/temp/temp101.ring",
		"libraries/softanzalib/temp/temp102.ring",
		"libraries/softanzalib/temp/temp103.ring",
		"libraries/softanzalib/temp/temp104.ring",
		"libraries/softanzalib/temp/temp105.ring",
		"libraries/softanzalib/temp/temp106.ring",
		"libraries/softanzalib/temp/temp107.ring",
		"libraries/softanzalib/temp/temp108.ring",
		"libraries/softanzalib/temp/temp109.ring",
		"libraries/softanzalib/temp/temp110.ring",
		"libraries/softanzalib/temp/temp35.ring",
		"libraries/softanzalib/temp/temp38.ring",
		"libraries/softanzalib/temp/temp40.ring",
		"libraries/softanzalib/temp/temp41.ring",
		"libraries/softanzalib/temp/temp42.ring",
		"libraries/softanzalib/temp/temp43.ring",
		"libraries/softanzalib/temp/temp44.ring",
		"libraries/softanzalib/temp/temp45.ring",
		"libraries/softanzalib/temp/temp46.ring",
		"libraries/softanzalib/temp/temp47.ring",
		"libraries/softanzalib/temp/temp48.ring",
		"libraries/softanzalib/temp/temp49.ring",
		"libraries/softanzalib/temp/temp50.ring",
		"libraries/softanzalib/temp/temp51.ring",
		"libraries/softanzalib/temp/temp52.ring",
		"libraries/softanzalib/temp/temp53.ring",
		"libraries/softanzalib/temp/temp54.ring",
		"libraries/softanzalib/temp/temp55.ring",
		"libraries/softanzalib/temp/temp56.ring",
		"libraries/softanzalib/temp/temp57.ring",
		"libraries/softanzalib/temp/temp58.ring",
		"libraries/softanzalib/temp/temp59.ring",
		"libraries/softanzalib/temp/temp6.ring",
		"libraries/softanzalib/temp/temp60.ring",
		"libraries/softanzalib/temp/temp61.ring",
		"libraries/softanzalib/temp/temp62.ring",
		"libraries/softanzalib/temp/temp63.ring",
		"libraries/softanzalib/temp/temp64.ring",
		"libraries/softanzalib/temp/temp65.ring",
		"libraries/softanzalib/temp/temp66.ring",
		"libraries/softanzalib/temp/temp67.ring",
		"libraries/softanzalib/temp/temp69.ring",
		"libraries/softanzalib/temp/temp70.ring",
		"libraries/softanzalib/temp/temp71.ring",
		"libraries/softanzalib/temp/temp72.ring",
		"libraries/softanzalib/temp/temp73.ring",
		"libraries/softanzalib/temp/temp74.ring",
		"libraries/softanzalib/temp/temp75.ring",
		"libraries/softanzalib/temp/temp76.ring",
		"libraries/softanzalib/temp/temp77.ring",
		"libraries/softanzalib/temp/temp78.ring",
		"libraries/softanzalib/temp/temp79.ring",
		"libraries/softanzalib/temp/temp80.ring",
		"libraries/softanzalib/temp/temp81.ring",
		"libraries/softanzalib/temp/temp82.ring",
		"libraries/softanzalib/temp/temp83.ring",
		"libraries/softanzalib/temp/temp84.ring",
		"libraries/softanzalib/temp/temp85.ring",
		"libraries/softanzalib/temp/temp86.ring",
		"libraries/softanzalib/temp/temp87.ring",
		"libraries/softanzalib/temp/temp88.ring",
		"libraries/softanzalib/temp/temp89.ring",
		"libraries/softanzalib/temp/temp99.ring",
		"libraries/softanzalib/temp/tempo20.ring",
		"libraries/softanzalib/temp/tempo21.ring",
		"libraries/softanzalib/temp/tempo22.ring",
		"libraries/softanzalib/temp/tempo23.ring",
		"libraries/softanzalib/temp/tempo28.ring",
		"libraries/softanzalib/temp/tempo29.ring",
		"libraries/softanzalib/temp/tempo30.ring",
		"libraries/softanzalib/temp/tempo31.ring",
		"libraries/softanzalib/temp/tempo32.ring",
		"libraries/softanzalib/temp/tempo33.ring",
		"libraries/softanzalib/temp/tempo34.ring",
		"libraries/softanzalib/temp/tempo35.ring",
		"libraries/softanzalib/temp/tempo36.ring",
		"libraries/softanzalib/temp/tempo37.ring",
		"libraries/softanzalib/temp/tempo38.ring",
		"libraries/softanzalib/temp/tempo39.ring",
		"libraries/softanzalib/temp/tempo40.ring",
		"libraries/softanzalib/temp/tempqtime.ring",
		"libraries/softanzalib/temp/tmpunicode.txt",
		"libraries/softanzalib/temp/todo.txt",
		"libraries/softanzalib/temp/webtest.ring",
		"libraries/softanzalib/temp/À·«ÀÊ‰.txt",
		"libraries/softanzalib/temp/Œ„”Ê‰.txt",
		"libraries/softanzalib/temp/‘Ì.txt",
		"libraries/softanzalib/temp/’œÌﬁÌ.txt",
		"libraries/softanzalib/temp/„—Õ»«.txt",
		"libraries/softanzalib/temp/„·«.txt",
		"libraries/softanzalib/temp/„·›¯Ì.txt",
		"libraries/softanzalib/temp/‰’.txt",
		"libraries/softanzalib/todo/addtostzstring.txt",
		"libraries/softanzalib/todo/qbytearray.txt",
		"libraries/softanzalib/todo/qchar.txt",
		"libraries/softanzalib/todo/qdate.txt",
		"libraries/softanzalib/todo/qdatetime.txt",
		"libraries/softanzalib/todo/qdir.txt",
		"libraries/softanzalib/todo/qdir_entryInfoList-methods.txt",
		"libraries/softanzalib/todo/qfile.txt",
		"libraries/softanzalib/todo/qfiledevice.txt",
		"libraries/softanzalib/todo/qfileinfo.txt",
		"libraries/softanzalib/todo/qiodevice.txt",
		"libraries/softanzalib/todo/qlocale.txt",
		"libraries/softanzalib/todo/qstring.txt",
		"libraries/softanzalib/todo/qstringlist.txt",
		"libraries/softanzalib/todo/qtextcodec.txt",
		"libraries/softanzalib/todo/qtextstream.txt",
		"libraries/softanzalib/todo/qtexttospeech.txt",
		"libraries/softanzalib/todo/qtime.txt",
		"libraries/softanzalib/todo/qurl.txt",
		"libraries/softanzalib/todo/qvoice.txt",
		"libraries/softanzalib/todo/temp.ring",
		"libraries/softanzalib/todo/todo.txt",
		"libraries/softanzalib/todo/todos.txt"
	],
	:windowsfiles = 	[

	],
	:linuxfiles = 	[

	],
	:ubuntufiles = 	[

	],
	:fedorafiles = 	[

	],
	:macosfiles = 	[

	],
	:windowsringfolderfiles = 	[

	],
	:linuxringfolderfiles = 	[

	],
	:ubunturingfolderfiles = 	[

	],
	:fedoraringfolderfiles = 	[

	],
	:macosringfolderfiles = 	[

	],
	:run = "ring main.ring",
	:windowsrun = "",
	:linuxrun = "",
	:macosrun = "",
	:ubunturun = "",
	:fedorarun = "",
	:setup = "",
	:windowssetup = "",
	:linuxsetup = "",
	:macossetup = "",
	:ubuntusetup = "",
	:fedorasetup = "",
	:remove = "",
	:windowsremove = "",
	:linuxremove = "",
	:macosremove = "",
	:ubunturemove = "",
	:fedoraremove = ""
]