#--------------------------------------------------------------#
#         SOFTANZA LIBRARY (V0.9) - STZWEBBUNDLE               #
#   An accelerative library for Ring applications, and more!   #
#--------------------------------------------------------------#
#                                                              #
#   Description  : The WEB is a COMPOSITE target -- not one    #
#                  binary but an assembly: wasm module(s) +    #
#                  a stz.js bridge + an HTML shell + a         #
#                  manifest. stzBuilder builds the wasm parts  #
#                  (freestanding, bridge ABI); stzWebBundle    #
#                  assembles them into one deployable folder.  #
#   Version      : V0.9 (2026)                                 #
#   Author       : Mansour Ayouni (kalidianow@gmail.com)       #
#                                                              #
#--------------------------------------------------------------#
#
# The bridge is real, not WASI emulation: JS owns the linear memory and passes it
# to the module; the module imports stz_log to render; its listed exports are
# callable from JS. This is "a part in wasm + a stz.js library bridging Softanza
# to the native wasm", assembled.
#
#   oW = new stzBuilder("app").AsC().Source("app.c").ForWeb().Export("stz_main")
#   oW.Build()
#   oB = new stzWebBundle("app").Title("My App").OutDir("dist")
#   oB.WithWasm("app", oW.OutputPath())
#   oB.Build()
#   #--> dist/{app.wasm, stz.js, index.html, bundle.json}

  #=============#
 #  FUNCTIONS  #
#=============#

func StzWebBundleQ(pcName)
	return new stzWebBundle(pcName)

# The Softanza <-> wasm bridge, emitted into the bundle. JS strings are single-
# quoted so this stays clean when generated. Matches the proven runtime bridge.
func _StzWebBridgeJs()
	_c_ = "// stz.js -- the Softanza <-> wasm bridge (generated by stzWebBundle)." + nl
	_c_ += "// JS owns the linear memory and passes it to the module; the module" + nl
	_c_ += "// imports stz_log to render. No WASI -- a real, minimal bridge surface." + nl
	_c_ += "(function (global) {" + nl
	_c_ += "  'use strict';" + nl
	_c_ += "  var dec = new TextDecoder('utf-8');" + nl
	_c_ += "  async function load(wasmUrl, opts) {" + nl
	_c_ += "    opts = opts || {};" + nl
	_c_ += "    var sink = opts.sink || function (s) { if (typeof console !== 'undefined') console.log(s); };" + nl
	_c_ += "    var memory = new WebAssembly.Memory({ initial: opts.pages || 256, maximum: opts.maxPages || 16384 });" + nl
	_c_ += "    var imports = { env: { memory: memory," + nl
	_c_ += "      stz_log: function (ptr, len) { sink(dec.decode(new Uint8Array(memory.buffer, ptr, len))); }" + nl
	_c_ += "    } };" + nl
	_c_ += "    var bytes = await fetch(wasmUrl).then(function (r) { return r.arrayBuffer(); });" + nl
	_c_ += "    var res = await WebAssembly.instantiate(bytes, imports);" + nl
	_c_ += "    return { exports: res.instance.exports, memory: memory };" + nl
	_c_ += "  }" + nl
	_c_ += "  global.Stz = { load: load };" + nl
	_c_ += "})(typeof window !== 'undefined' ? window : this);" + nl
	return _c_

func _StzWebShellHtml(pcTitle, pcMainWasm)
	_c_ = "<!doctype html>" + nl
	_c_ += "<html lang='en'><head><meta charset='utf-8'>" + nl
	_c_ += "<meta name='viewport' content='width=device-width, initial-scale=1'>" + nl
	_c_ += "<title>" + pcTitle + "</title></head>" + nl
	_c_ += "<body>" + nl
	_c_ += "<h1>" + pcTitle + "</h1>" + nl
	_c_ += "<div id='stz-out'></div>" + nl
	_c_ += "<script src='stz.js'></script>" + nl
	_c_ += "<script>" + nl
	_c_ += "(function () {" + nl
	_c_ += "  var out = document.getElementById('stz-out');" + nl
	_c_ += "  function sink(s) { var p = document.createElement('p'); p.textContent = s; out.appendChild(p); }" + nl
	_c_ += "  Stz.load('" + pcMainWasm + "', { sink: sink }).then(function (mod) {" + nl
	_c_ += "    if (mod.exports.stz_main) { mod.exports.stz_main(); }" + nl
	_c_ += "    var d = document.createElement('div'); d.id = 'stz-done'; d.textContent = 'ready';" + nl
	_c_ += "    document.body.appendChild(d);" + nl
	_c_ += "  }).catch(function (e) { sink('ERROR: ' + e); });" + nl
	_c_ += "})();" + nl
	_c_ += "</script></body></html>" + nl
	return _c_

func _StzWebManifest(pcName, paFiles, pcMain)
	_q_ = char(34)
	_c_ = "{" + nl
	_c_ += "  " + _q_ + "name" + _q_ + ": " + _q_ + pcName + _q_ + "," + nl
	_c_ += "  " + _q_ + "kind" + _q_ + ": " + _q_ + "web-bundle" + _q_ + "," + nl
	_c_ += "  " + _q_ + "entry" + _q_ + ": " + _q_ + "index.html" + _q_ + "," + nl
	_c_ += "  " + _q_ + "main" + _q_ + ": " + _q_ + pcMain + _q_ + "," + nl
	_c_ += "  " + _q_ + "files" + _q_ + ": ["
	_n_ = len(paFiles)
	for _i_ = 1 to _n_
		_c_ += _q_ + paFiles[_i_] + _q_
		if _i_ < _n_
			_c_ += ", "
		ok
	next
	_c_ += "]" + nl + "}" + nl
	return _c_


  #===============#
 #  STZWEBBUNDLE  #
#===============#

class stzWebBundle from stzObject

	@cName = ""
	@cTitle = ""
	@cOutDir = ""
	@aParts = []       # [ name, wasmPath ]
	@aFiles = []
	@bBuilt = FALSE

	def init(pcName)
		@cName = "" + pcName
		@cTitle = "" + pcName

	def Title(pcTitle)
		@cTitle = "" + pcTitle
		return This

	def OutDir(pcDir)
		@cOutDir = "" + pcDir
		return This

	# Add a wasm part -- a prebuilt .wasm path, or a stzBuilder (which is built).
	def WithWasm(pcName, pWasm)
		_cPath_ = ""
		if isObject(pWasm)
			pWasm.Build()
			_cPath_ = pWasm.OutputPath()
		else
			_cPath_ = "" + pWasm
		ok
		@aParts + [ "" + pcName, _cPath_ ]
		return This

	def BundleDir()
		if @cOutDir != ""
			return @cOutDir
		ok
		return @cName + "_web"

	def Build()
		_cDir_ = This.BundleDir()
		StzEngineDirCreatePath(_cDir_)
		@aFiles = []

		# copy each wasm part into the bundle
		_nP_ = len(@aParts)
		_cMain_ = ""
		for _i_ = 1 to _nP_
			_cPartName_ = @aParts[_i_][1]
			_cSrc_ = @aParts[_i_][2]
			_cDst_ = _cDir_ + "/" + _cPartName_ + ".wasm"
			write(_cDst_, read(_cSrc_))
			@aFiles + (_cPartName_ + ".wasm")
			if _i_ = 1
				_cMain_ = _cPartName_ + ".wasm"
			ok
		next

		# the bridge, the shell, the manifest
		write(_cDir_ + "/stz.js", _StzWebBridgeJs())
		@aFiles + "stz.js"
		write(_cDir_ + "/index.html", _StzWebShellHtml(@cTitle, _cMain_))
		@aFiles + "index.html"
		write(_cDir_ + "/bundle.json", _StzWebManifest(@cName, @aFiles, _cMain_))
		@aFiles + "bundle.json"

		@bBuilt = TRUE
		return This

		def BuildQ()
			This.Build()
			return This

	def Files()
		return @aFiles

	def NumberOfParts()
		return len(@aParts)

	def IsBuilt()
		return @bBuilt

	def ShellPath()
		return This.BundleDir() + "/index.html"

	def BridgePath()
		return This.BundleDir() + "/stz.js"

	def ManifestPath()
		return This.BundleDir() + "/bundle.json"

	def Show()
		? "WebBundle '" + @cName + "' (" + This.NumberOfParts() + " wasm part(s))"
		? "  dir:   " + This.BundleDir()
		if @bBuilt
			? "  files: " + @@(@aFiles)
		ok
