
# Loading additional Ring libs required by Softanza Base layer
#NOTE Core layer already has "../../core/common/stkRingLibs.ring"

# Load Base Engine bridges (stz_* DLLs -- superset of Core stk_* DLLs)

load "../../engine/stz_string.ring"
load "../../engine/stz_datetime.ring"
load "../../engine/stz_file.ring"
load "../../engine/stz_locale.ring"
load "../../engine/stz_unicode.ring"
load "../../engine/stz_regex.ring"
load "../../engine/stz_bytes.ring"
load "../../engine/stz_json.ring"
load "../../engine/stz_url.ring"
load "../../engine/stz_system.ring"
load "../../engine/stz_value.ring"
load "../../engine/stz_number.ring"
load "../../engine/stz_list.ring"
load "../../engine/stz_hashmap.ring"
load "../../engine/stz_table.ring"
load "../../engine/stz_matrix.ring"
load "../../engine/stz_unidata.ring"
load "../../engine/stz_random.ring"
load "../../engine/stz_csv.ring"
load "../../engine/stz_stats.ring"
load "../../engine/stz_graph.ring"
load "../../engine/stz_text.ring"
load "../../engine/stz_uuid.ring"
load "../../engine/stz_codec.ring"
load "../../engine/stz_bits.ring"
load "../../engine/stz_html.ring"
load "../../engine/stz_geo.ring"
load "../../engine/stz_compress.ring"
load "../../engine/stz_solver.ring"
load "../../engine/stz_watch.ring"
load "../../engine/stz_log.ring"
load "../../engine/stz_cache.ring"
load "../../engine/stz_stream.ring"
load "../../engine/stz_process.ring"
load "../../engine/stz_arith.ring"
load "../../engine/stz_registry.ring"
load "../../engine/stz_profiler.ring"
load "../../engine/stz_callstack.ring"
load "../../engine/stz_crypto.ring"
load "../../engine/stz_async.ring"
load "../../engine/stz_embed.ring"
load "../../engine/stz_smallfn.ring"
load "../../engine/stz_execmodel.ring"
load "../../engine/stz_numtheory.ring"
load "../../engine/stz_splitter.ring"
load "../../engine/stz_univops.ring"
load "../../engine/stz_pattern.ring"
load "../../engine/stz_stringart.ring"
load "../../engine/stz_display.ring"
load "../../engine/stz_constraint.ring"
load "../../engine/stz_natlang.ring"
load "../../engine/stzMeta.ring"

# Initialize the meta-engine (named params, error catalog, aliases)
StzMetaInit()
