load "../../stzBase.ring"
load "../_narrated.ring"

Scenario("stzLoadBalancer initializes with default routing")
    Given("a freshly-constructed load balancer")
    oLB = new stzLoadBalancer()
    aStats = oLB.GetRoutingStats()
    Then("no requests routed yet",   aStats[:total_requests], 0)
    Then("no clusters registered",   aStats[:clusters_count], 0)
    Then("four default routing rules", aStats[:routing_rules], 4)
EndScenario()

Scenario("RegisterCluster supports add then in-place update")
    Given("a load balancer with no clusters")
    oLB = new stzLoadBalancer()
    When("registering an NLP cluster with two nodes")
    oLB.RegisterCluster("nlp", [ "node-1", "node-2" ])
    Then("cluster count = 1", oLB.GetRoutingStats()[:clusters_count], 1)
    aFound = oLB.FindCluster("nlp")
    Then("FindCluster returns the cluster", aFound[:type], "nlp")
    Then("with the registered node list", len(aFound[:nodes]), 2)
    Then("FindCluster on unknown type returns NULL",
        oLB.FindCluster("unknown"), NULL)
    When("re-registering the same NLP cluster with three nodes")
    oLB.RegisterCluster("nlp", [ "node-1", "node-2", "node-3" ])
    Then("cluster count still 1",   oLB.GetRoutingStats()[:clusters_count], 1)
    Then("node list updated to 3", len(oLB.FindCluster("nlp")[:nodes]), 3)
EndScenario()

Scenario("stzClusterNode reports overload via metrics")
    Given("a math node with light load")
    oNode = new stzClusterNode("math", "math-1")
    oNode.UpdateMetrics(50, 10, 100)
    Then("not overloaded under thresholds", oNode.IsOverloaded(), FALSE)
    When("the metrics cross every threshold")
    oNode.UpdateMetrics(90, 60, 250)
    Then("overload flag flips", oNode.IsOverloaded(), TRUE)
    aH = oNode.GetHealthStatus()
    Then("health status carries node id",       aH[:node_id],      "math-1")
    Then("health status carries cluster type",  aH[:cluster_type], "math")
    Then("health status reflects updated load", aH[:load],         90)
EndScenario()

Summary()
