load "../../stzBase.ring"
load "../_narrated.ring"

# The all-lengths consecutive-substrings forms: ConsecutiveSubStrings()
# concatenates the phase-tiled windows of every length 1..floor(len/2)
# (315 windows for this 29-char string, per the archive), and
# FindConsecutiveSubStrings() reduces to [1..len]. The archive's expected
# lists for the all-lengths Z/ZZ groupings were generated by a buggy
# impl (the entry substrings and spans disagree with each other, e.g.
# [ "hp", [2,2] ]) -- so those two are asserted at the coherent original-impl
# values ([window, start] / [window, span], ascending start within each
# length), spot-checked plus a full self-consistency sweep.
# Archive block #292.

Scenario("Counting and listing all consecutive substrings")
	Given('"phpringringringpythonrubyruby" (29 chars)')
	o1 = new stzString("phpringringringpythonrubyruby")
	Then("their total number is Sum(29-i+1, i=1..14)", o1.NumberOfConsecutiveSubStrings(), 315)
	acAll = o1.ConsecutiveSubStrings()
	Then("the list carries all 315 windows", len(acAll), 315)
	Then("it starts with the single chars", acAll[1] + acAll[2] + acAll[3], "php")
	Then("the length-2 windows follow, phase-major", acAll[30] + "/" + acAll[31] + "/" + acAll[44], "ph/pr/hp")
	Then("it ends with the last length-14 window", acAll[315], "ngpythonrubyru")
	anPos = o1.FindConsecutiveSubStrings()
	Then("the Find form reduces to 1..29", len(anPos), 29)
	Then("... starting at 1", anPos[1], 1)
	Then("... ending at 29", anPos[29], 29)
EndScenario()

Scenario("The Z / ZZ groupings stay coherent with the windows")
	Given('the same string')
	o1 = new stzString("phpringringringpythonrubyruby")
	aZZSec = o1.FindConsecutiveSubStringsZZ()
	Then("the FindZZ spans cover all 315 windows", len(aZZSec), 315)
	Then("... first span", ListEq( aZZSec[1], [1,1] ), TRUE)
	Then("... first length-2 span", ListEq( aZZSec[30], [1,2] ), TRUE)
	Then("... last span", ListEq( aZZSec[315], [16,29] ), TRUE)
	aZ = o1.ConsecutiveSubStringsZ()
	Then("the Z grouping pairs window and start", ListEq( aZ[30], [ "ph", 1 ] ), TRUE)
	Then("... last entry", ListEq( aZ[315], [ "pythonrubyruby", 16 ] ), TRUE)
	aZZ = o1.ConsecutiveSubStringsZZ()
	Then("the ZZ grouping pairs window and span", ListEq( aZZ[30], [ "ph", [1,2] ] ), TRUE)
	Then("... last entry", ListEq( aZZ[315], [ "pythonrubyruby", [16,29] ] ), TRUE)
	bCoherent = TRUE
	for i = 1 to 315
		if aZZ[i][1] != o1.Section(aZZ[i][2][1], aZZ[i][2][2])
			bCoherent = FALSE
			exit
		ok
	next
	Then("every ZZ substring equals the section at its span", bCoherent, TRUE)
EndScenario()

Summary()

func ListEq aA, aE
	if len(aA) != len(aE) return FALSE ok
	nLen = len(aA)
	for i = 1 to nLen
		if isList(aA[i]) and isList(aE[i])
			if NOT ListEq(aA[i], aE[i]) return FALSE ok
		else
			if aA[i] != aE[i] return FALSE ok
		ok
	next
	return TRUE
