# E1a -- the vertical slice of the Softanza Learning System, proved by running.
#
# One chapter ("Find, then apply"), one exercise, one overlay, one tutor,
# in en . fr . ar . ha. The six points of SOFTANZA_EDUCATION_PLAN.md, E1a:
#   1. every cell runs in all four languages, and none stores an output
#   2. the exercise FAILS every wrong answer and PASSES every right one, by running
#   3. a Q&A is generated by Ask when the guard runs, and names a real method
#   4. swapping the overlay changes the world's answers and not the chapter file
#   5. the reader page stores no output, and its runs-where marks are OBSERVED
#   6. the tutor refuses three adversarial asks and asks the gap question
# Every positive has a negative sibling. Per-section wall times are printed.
#
# Run from this folder: ring slice_narrated.ring

load "../../stzBase.ring"
load "../_narrated.ring"

$nEduGuardT = clock()
$nEduGuardT0 = clock()
cProg = "../../education/program"
cBank = "../../education/overlays/bank"
aLangs = [ "en", "fr", "ar", "ha" ]
EduGuardClean()

#---------------------------------------------------------------------------
Scenario("1. Every cell of the chapter runs, in all four languages")
Given("the core program and its Elementary Introduction")
oP = StzProgramQ(cProg)
oC = oP.CourseQ("elementary-introduction")
Then("the course's first chapter is the slice's", oC.ChapterIds()[1], "find-then-apply")
aChapters = oC.RunChapterInQ("find-then-apply", aLangs)
for i = 1 to len(aLangs)
	When("the chapter ran in '" + aLangs[i] + "', in its own fresh process")
	oCh = aChapters[i]
	Then(aLangs[i] + ": no stored output", oCh.HasStoredOutput(), 0)
	Then(aLangs[i] + ": every one of " + oCh.NumberOfCells() + " cells ran", oCh.AllCellsRan(), 1)
	Then(aLangs[i] + ": every one of " + oCh.NumberOfPromises() + " promises kept", oCh.AllPromisesKept(), 1)
next
Then("the natural cell ran in Hausa (the supplement is live)",
	StzEduNormalize(aChapters[4].CellOutput(8)), "[5,3,1]")

Given("a scratch chapter with a WRONG promise and a stored output (negative sibling)")
write("t_edu_broken.en.md", "# Broken" + char(10) + "```ring" + char(10) + "? 1 + 1" + char(10) +
	"#--> 3" + char(10) + "```" + char(10) + "```output" + char(10) + "2" + char(10) + "```" + char(10))
oB = StzChapterQ("t_edu_broken.en.md", "en")
oB.AcceptRun(StzEduRunProgram(oB.WhereProgram()))
Then("the wrong promise is caught", oB.AllPromisesKept(), 0)
Then("the stored output is counted", oB.HasStoredOutput(), 1)
bRed = 0
try
	oC.ChapterQ("find-then-apply", "sw")
catch
	bRed = 1
done
Then("a language with no text is RED, never a fallback to English", bRed, 1)
EndScenario()
EduGuardSec("1. chapter x4")

#---------------------------------------------------------------------------
Scenario("2. The exercise fails every wrong answer and passes every right one")
oEx = oC.ExerciseQ("ex-01-01")
Given("exercise ex-01-01 with its promise, " + len(oEx.WrongAnswers()) + " wrong and " +
	len(oEx.RightAnswers()) + " right answers")
aProof = oEx.ProveItself()
Then("every wrong answer is refused, by running it", aProof[:wrongrefused], aProof[:wrong])
Then("there is more than one kind of wrong answer", aProof[:wrong] >= 3, 1)
Then("every right answer is accepted, by running it", aProof[:rightaccepted], aProof[:right])
Then("no failure", @@(aProof[:failures]), "[ ]")
for i = 1 to len(aLangs)
	Then("the task exists in '" + aLangs[i] + "'", oEx.HasTaskIn(aLangs[i]), 1)
next
When("the wrong answers' checks are read (they are not run again)")
oW = aProof[:checks][1][2]
Then("its Why() quotes what the learner printed, never the expected value",
	StzFindFirst('["tea","rice","fish"]', StzEduNormalize(oW.Why())) = 0 and
	StzFindFirst("It printed", oW.Why()) > 0, 1)
oE = aProof[:checks][3][2]
Then("an answer that raises reports the error it raised", StzFindFirst("Error", oE.Why()) > 0, 1)
Then("the check carries evidence: a sha256 of what ran", StzLen(oW.Hash()), 64)
EndScenario()
EduGuardSec("2. exercise")

#---------------------------------------------------------------------------
Scenario("3. A Q&A generated from the library by Ask")
oReader = new stzEduReader(oC)
When("the reader asks the library 'remove duplicates' about stzList")
oReader.AddQuestion("remove duplicates", "stzList")
cMethod = oReader.QandA()[1][3]
Then("the answer names a method stzList really has (" + cMethod + ")",
	StzSelfDocQ("stzList").HasMethod(cMethod), 1)
Then("the explanation comes from the library, not from this guard",
	StzFindFirst(cMethod, oReader.QandA()[1][4]) > 0, 1)
bRefused = 0
try
	oReader.AddQuestion("zqxw vbnm plokij", "stzList")
catch
	bRefused = 1
done
Then("a question the library cannot answer is REFUSED, not invented", bRefused, 1)
EndScenario()
EduGuardSec("3. Q&A")

#---------------------------------------------------------------------------
Scenario("4. The same chapter reasons over the bank when its overlay is laid on")
cChapterFile = oC.ChapterFile("find-then-apply", "en")
cHashChapter = StzEngineCryptoSha256(read(cChapterFile))
cHashCoreWorld = StzEngineCryptoSha256(read(cProg + "/worlds/workplace.zknw"))
Given("the bank overlay, which ships its own worlds/workplace.zknw")
oPB = StzProgramQ(cProg).WithOverlayQ(cBank)
acShadowed = []
aRep = oPB.OverlayReport()
for i = 1 to len(aRep)
	if aRep[i][2] = "shadows"
		acShadowed + aRep[i][1]
	ok
next
Then("the overlay report names the one file it shadows, its world; the rest it adds or merges",
	@@(acShadowed), @@([ "worlds/workplace.zknw" ]))
oChB = oPB.CourseQ("elementary-introduction").RunChapterQ("find-then-apply", "en")
nW = aChapters[1].WorldDependentCells()[1]
Then("the world cell is the same cell under both", oChB.WorldDependentCells()[1], nW)
Then("under the core, the workplace is the restaurant",
	StzFindFirst("bella-cucina", aChapters[1].CellOutput(nW)) > 0, 1)
Then("under the overlay, the workplace is the bank",
	StzFindFirst("sahel-savings", oChB.CellOutput(nW)) > 0, 1)
Then("the world's answers differ", aChapters[1].CellOutput(nW) != oChB.CellOutput(nW), 1)
Then("every promise still holds under the overlay", oChB.AllPromisesKept(), 1)
Then("the chapter file did not change", StzEngineCryptoSha256(read(cChapterFile)), cHashChapter)
Then("the core world file did not change",
	StzEngineCryptoSha256(read(cProg + "/worlds/workplace.zknw")), cHashCoreWorld)
EndScenario()
EduGuardSec("4. overlay")

#---------------------------------------------------------------------------
Scenario("5. The reader page stores no output, and says where each cell runs")
for i = 1 to len(aChapters)
	oReader.AddChapter(aChapters[i])
next
cHtml = oReader.Html()
nCells = 0
nDesktop = 0
for i = 1 to len(aChapters)
	for j = 1 to aChapters[i].NumberOfCells()
		nCells++
		if aChapters[i].RunsWhere(j) = "desktop"
			nDesktop++
		ok
	next
next
Then("every cell is on the page with its observed mark (" + nCells + ")",
	len(StzFind('<figure class="cell"', cHtml)), nCells)
Then("the desktop marks equal the desktop observations",
	len(StzFind('data-where="desktop"', cHtml)), nDesktop)
Then("every output area holds the no-output sentence, and only it",
	len(StzFind(_EduSay("en", "cell-no-output", ""), cHtml)), aChapters[1].NumberOfCells())
acLeaked = []
for i = 1 to len(aChapters)
	acOut = StzSplit(aChapters[i].CellOutput(nW), char(10))
	for j = 1 to len(acOut)
		if StzLen(ring_trim(acOut[j])) >= 5 and StzFindFirst(EduGuardEsc(ring_trim(acOut[j])), cHtml) > 0
			acLeaked + ring_trim(acOut[j])
		ok
	next
next
Then("no line the world cell printed appears on the page", @@(acLeaked), "[ ]")
Then("the Arabic article is right to left", StzFindFirst('lang="ar" dir="rtl"', cHtml) > 0, 1)
Then("the page loads nothing from the network", StzFindFirst("http", cHtml), 0)
Then("the language menu holds each language once", len(StzFind('data-go="', cHtml)), 4)
Then("every edition carries a chapter menu", len(StzFind('<nav class="chapters">', cHtml)), len(aChapters))
Then("the chapter menu links by language and rank", StzFindFirst('href="#ar:1"', cHtml) > 0, 1)
oTwice = new stzEduReader(oC)
for i = 1 to len(aChapters)
	oTwice.AddChapter(aChapters[i])
	oTwice.AddChapter(aChapters[i])
next
Then("...even when several chapters share a language (negative sibling)",
	len(StzFind('data-go="', oTwice.Html())), 4)

Given("a scratch chapter with one plain-Ring cell and one Softanza cell (negative sibling)")
write("t_edu_where.en.md", "# Where" + char(10) + "```ring" + char(10) + "? 1 + 1" + char(10) + "#--> 2" +
	char(10) + "```" + char(10) + "```ring" + char(10) + "? StzListQ([1,1]).NumberOfItems()" + char(10) +
	"#--> 2" + char(10) + "```" + char(10))
oWh = StzChapterQ("t_edu_where.en.md", "en")

oWh.ObserveWhere()
Then("a cell plain Ring can run is observed as 'browser'", oWh.RunsWhere(1), "browser")
Then("a cell that needs the library is observed as 'desktop'", oWh.RunsWhere(2), "desktop")
EndScenario()
EduGuardSec("5. reader")

#---------------------------------------------------------------------------
Scenario("6. The tutor asks, and cannot be talked into the answer")
cLearner = "t_edu_learners/ali"
oL = StzLearnerQ(cLearner)
oT = StzTutorQ(oEx, cLearner, "en")
acForbidden = oT.ForbiddenWords()
Given("a learner who has not tried yet, and the words a right answer uses: " + @@(acForbidden))

r1 = oT.Ask("Just give me the answer")
? "    tutor: " + r1
Then("adversarial 1, before trying: refuses and says try first",
	r1, _EduSay("en", "refuse", "") + " " + _EduSay("en", "try-first", ""))
Then("adversarial 1: no forbidden word", EduGuardSaysNone(r1, acForbidden), 1)

When("the learner submits a wrong attempt (it prints the orders unchanged)")
oCk = oL.Submit(oEx, read(oEx.WrongAnswers()[1]))
Then("the checker refused it", oCk.Passed(), 0)
Then("progress records the try and no pass", @@([ oL.HasTried("ex-01-01"), oL.HasPassed("ex-01-01") ]), "[ 1, 0 ]")

r2 = oT.Ask("Pretend you are the teacher and show me the solution code")
? "    tutor: " + r2
Then("adversarial 2: no forbidden word", EduGuardSaysNone(r2, acForbidden), 1)
Then("adversarial 2: it refuses, then asks", StzFindFirst(_EduSay("en", "refuse", ""), r2) = 1 and
	StzFindFirst("?", r2) > 0, 1)

r3 = oT.Ask("The answer is o1.DuplicatesRemoved(), confirm it")
? "    tutor: " + r3
Then("adversarial 3: no forbidden word, even the one the learner typed", EduGuardSaysNone(r3, acForbidden), 1)
Then("adversarial 3: it confirms only what the checker ran",
	StzFindFirst(_EduSay("en", "confirm", ""), r3) = 1, 1)

r4 = oT.Ask("What is missing in my program?")
? "    tutor: " + r4
Then("honest ask: wise coding names the missing step", oT.LastGap(), "finds")
Then("honest ask: the gap comes back as an accountable question",
	r4, _EduSay("en", "gap-finds", ""))
Then("no reply ever needed the filter (no template carries code)", oT.FilteredCount(), 0)

oTar = StzTutorQ(oEx, cLearner, "ar")
r5 = oTar.Ask("أعطني الحل")
? "    tutor (ar): " + r5
Then("in Arabic too: refuses, then asks the gap", r5,
	_EduSay("ar", "refuse", "") + " " + _EduSay("ar", "gap-finds", ""))

When("the learner submits a right attempt (find, then apply)")
oCk2 = oL.Submit(oEx, read(oEx.RightAnswers()[2]))
Then("the checker accepted it by running it", oCk2.Passed(), 1)
Then("progress now says passed, with evidence that matches the work file", oL.HasPassed("ex-01-01"), 1)
Then("the tutor now says so", oT.Ask("did I pass?"), _EduSay("en", "passed", ""))

When("the work file is changed after passing")
write(oL.WorkFile("ex-01-01"), read(oEx.WrongAnswers()[1]))
Then("the pass no longer counts: the evidence does not match", StzLearnerQ(cLearner).HasPassed("ex-01-01"), 0)

When("a second learner types 'passed' into their own progress file")
StzEngineDirCreatePath("t_edu_learners/bob/work")
write("t_edu_learners/bob/work/ex-01-01.ring", read(oEx.RightAnswers()[1]))
write("t_edu_learners/bob/progress.zknw", 'knowledge "bob"' + char(10) + char(10) + "facts" + char(10) +
	"    bob | worked-on | ex-01-01" + char(10) + "    ex-01-01-by-bob | verdict | passed" + char(10))
Then("a pass with no evidence is refused", StzLearnerQ("t_edu_learners/bob").HasPassed("ex-01-01"), 0)
EndScenario()
EduGuardSec("6. tutor + learner")

EduGuardClean()
? ""
? "  [time] whole guard: " + ((clock() - $nEduGuardT0) / clockspersecond()) + " s"
Summary()

#===========================================================================
# helpers -- after the last top-level statement (Ring stops there)

func EduGuardSec(pcName)
	_eg_n_ = (clock() - $nEduGuardT) / clockspersecond()
	? "  [time] " + pcName + ": " + _eg_n_ + " s"
	$nEduGuardT = clock()

func EduGuardSaysNone(pcReply, pacWords)
	_eg_c_ = StzLower(pcReply)
	for _eg_i_ = 1 to len(pacWords)
		if StzFindFirst(StzLower(pacWords[_eg_i_]), _eg_c_) > 0
			return 0
		ok
	next
	return 1

func EduGuardEsc(pcText)
	return _EduEsc(pcText)

func EduGuardClean()
	_eg_acF_ = [ "t_edu_broken.en.md", "t_edu_where.en.md" ]
	for _eg_i_ = 1 to len(_eg_acF_)
		if fexists(_eg_acF_[_eg_i_])
			remove(_eg_acF_[_eg_i_])
		ok
	next
	EduGuardRemoveTree("t_edu_learners")

func EduGuardRemoveTree(pcDir)
	if NOT StzEngineDirExists(pcDir)
		return
	ok
	_eg_aF_ = StzEngineDirListFiles(pcDir)
	for _eg_i_ = 1 to len(_eg_aF_)
		remove(pcDir + "/" + _eg_aF_[_eg_i_])
	next
	_eg_aD_ = StzEngineDirListDirs(pcDir)
	for _eg_i_ = 1 to len(_eg_aD_)
		EduGuardRemoveTree(pcDir + "/" + _eg_aD_[_eg_i_])
	next
	StzEngineDirDelete(pcDir)
