R = 'o1 = new stzHashList([ :one = "a", :two = "b", :three = "a", :four = 4 ])'
RL = 'o1 = new stzHashList([ :one = :NONE, :two = [ :is, :will, :can ], :three = [ :can, :will ] ])'

DOC = {
"class": "stzHashList",
"receiver": R,
"class_block": {
    "brief": "Holds a list of [ key, value ] pairs and finds, reads and groups them by key or by value.",
    "detail": "A hash list is the Ring list [ :name = \"Ali\", :age = 30 ] made into an object: keys are looked up without regard to case, values can be of any type and repeat, and the pairs keep their order. Reach for it when you read the pairs by position or by value as often as by key.",
    "receiver": R,
    "example": ['? @@( o1.FindValue("a") )', '#--> [ 1, 3 ]'],
    "see": ["stzList", "stzTable"],
},
"entries": [
 {"name": "Content",
  "brief": "Returns the pairs as they are held, a list of [ key, value ] pairs.",
  "returns": "a list of [ key, value ] pairs, in order",
  "see": ["Keys", "Values"],
  "example": ['? @@( o1.Content() )']},
 {"name": "Show",
  "brief": "Prints the hash list as a boxed table, one row per pair.",
  "returns": "nothing; the table is printed",
  "see": ["Content"]},
 {"name": "FindValue",
  "brief": "Returns the positions of the pairs that hold the given value, ignoring case.",
  "params": {"pValue": "the value to look for"},
  "returns": "a list of numbers; [ ] when no pair holds the value",
  "note": ["FindValueCS takes a case-sensitivity flag"],
  "see": ["FindFirstOccurrenceOfValue", "FindNthOccurrenceOfValue", "HasKey"],
  "example": ['? @@( o1.FindValue("a") )', '? @@( o1.FindValue("z") )']},
 {"name": "Copy",
  "brief": "Returns a new hash list with the same pairs, so the copy can change without touching this one.",
  "returns": "a new stzHashList",
  "example": ['o2 = o1.Copy()', 'o2.Add([ "five", "e" ])', '? o1.NumberOfPairs()', '? o2.NumberOfPairs()']},
 {"name": "NthValue",
  "brief": "Returns the value of the pair at position n.",
  "params": {"_n_": "a position from 1 to the number of pairs, or :First or :Last"},
  "returns": "the value of that pair, of any type",
  "warning": ["a position outside the hash list raises an error"],
  "see": ["Values", "FindNthOccurrenceOfValue"],
  "example": ['? o1.NthValue(2)', '? o1.NthValue(:Last)']},
 {"name": "Add",
  "brief": "Adds a pair at the end of the hash list, in place.",
  "params": {"paNewPair": "the pair to add, as [ key, value ]"},
  "returns": "nothing; the hash list changes. AddQ returns the object for chaining",
  "see": ["InsertBefore"],
  "example": ['o1.Add([ "five", "e" ])', '? o1.NumberOfPairs()', '? o1.NthValue(5)']},
 {"name": "FindFirstOccurrenceOfValue",
  "brief": "Returns the position of the first pair that holds the given value.",
  "params": {"pValue": "the value to look for"},
  "returns": "a number, the position of the first pair holding the value",
  "warning": ["when no pair holds the value the call raises an error (index out of range) instead of answering 0"],
  "see": ["FindValue", "FindLastOccurrenceOfValue", "FindNthOccurrenceOfValue"],
  "example": ['? o1.FindFirstOccurrenceOfValue("a")']},
 {"name": "NumberOfItems",
  "brief": "Returns how many different items the list values hold, counting each item once.",
  "returns": "a number",
  "note": ["only the values that are lists are looked into; the items of two lists that share one are counted once"],
  "see": ["Items", "FindItem"],
  "example": [RL, '? o1.NumberOfItems()']},
 {"name": "FindLastOccurrenceOfValue",
  "brief": "Returns the position of the last pair that holds the given value.",
  "params": {"pValue": "the value to look for"},
  "returns": "a number, the position of the last pair holding the value",
  "warning": ["known defect: it asks for the nth occurrence with n = the number of pairs, so it raises an error (index out of range) unless every pair holds the value; FindValue gives the positions to take the last of"],
  "see": ["FindValue", "FindFirstOccurrenceOfValue"]},
 {"name": "FindNthOccurrenceOfValue",
  "brief": "Returns the position of the pair that holds the given value for the nth time, ignoring case.",
  "params": {"_n_": "which occurrence, counting from 1", "pValue": "the value to look for"},
  "returns": "a number, the position of that pair",
  "warning": ["when there are fewer than n occurrences the call raises an error (index out of range) instead of answering 0"],
  "see": ["FindValue", "FindFirstOccurrenceOfValue"],
  "example": ['? o1.FindNthOccurrenceOfValue(2, "a")']},
 {"name": "StzType",
  "brief": "Returns the Softanza type symbol of the object, always :stzHashList.",
  "returns": "the symbol :stzHashList, which prints as stzhashlist",
  "example": ['? o1.StzType()']},
 {"name": "Classify",
  "brief": "Groups the keys by the value they hold, one [ class, keys ] pair per distinct value.",
  "returns": "a list of [ value as text, list of keys ] pairs, in order of first appearance",
  "warning": ["known defect: the call raises error R14 today, because it uses IsStrictlyEqualTo, which no class defines; Classes and NumberOfClasses work"],
  "see": ["Classes", "NumberOfClasses"]},
 {"name": "Keys",
  "brief": "Returns the keys of the hash list, in order.",
  "returns": "a list of the keys, which are held in lower case",
  "see": ["Values", "HasKey"],
  "example": ['? @@( o1.Keys() )']},
 {"name": "HasKey",
  "brief": "TRUE if the hash list holds the given key, whatever its case.",
  "params": {"pcKey": "the key to look for, as text"},
  "returns": "TRUE or FALSE",
  "see": ["Keys"],
  "example": ['? o1.HasKey("two")', '? o1.HasKey("TWO")', '? o1.HasKey("six")']},
 {"name": "NumberOfPairs",
  "brief": "Returns how many [ key, value ] pairs the hash list holds.",
  "returns": "a number",
  "example": ['? o1.NumberOfPairs()']},
 {"name": "Numbers",
  "brief": "Returns the values that are numbers, in order.",
  "returns": "a list of numbers",
  "see": ["Values"],
  "example": ['? @@( o1.Numbers() )']},
 {"name": "InsertBefore",
  "brief": "Inserts a pair before position n, in place.",
  "params": {"_n_": "the position to insert before, from 2 to the number of pairs", "paPair": "the pair to insert, as [ key, value ]"},
  "returns": "nothing; the hash list changes",
  "warning": ["known defect: the call raises an error today, because it reads a property named HashList that the object does not have; Add appends a pair and works"],
  "see": ["Add"]},
 {"name": "NumberOfClasses",
  "brief": "Returns how many different values the hash list holds.",
  "returns": "a number",
  "see": ["Classes", "Classify"],
  "example": ['? o1.NumberOfClasses()']},
 {"name": "Values",
  "brief": "Returns the values of the hash list, in order.",
  "returns": "a list of the values",
  "see": ["Keys", "Numbers"],
  "example": ['? @@( o1.Values() )']},
 {"name": "ToCode",
  "brief": "Returns the hash list as Ring code that rebuilds it.",
  "returns": "a string",
  "note": ["every value is written as text, so the number 4 comes out as \"4\""],
  "example": ['? o1.ToCode()']},
 {"name": "FindItem",
  "brief": "Returns, for every list value that holds the given item, its position and the item's positions inside it.",
  "params": {"pItem": "the item to look for inside the list values"},
  "returns": "a list of [ position of the pair, list of positions of the item ] pairs",
  "see": ["Items", "NumberOfItems"],
  "example": [RL, '? @@( o1.FindItem(:can) )']},
 {"name": "Items",
  "brief": "Returns the items of all the list values, merged, each item once.",
  "returns": "a list of the distinct items",
  "see": ["NumberOfItems", "FindItem"],
  "example": [RL, '? @@( o1.Items() )']},
 {"name": "Classes",
  "brief": "Returns the distinct values of the hash list, each as text.",
  "returns": "a list of text, in order of first appearance",
  "see": ["Classify", "NumberOfClasses"],
  "example": ['? @@( o1.Classes() )']},
]}
