R = 'o1 = new stzList([ "a", "b", "c", "b" ])'
RN = 'o1 = new stzList([ 3, 1, 4, 1, 5 ])'

def E(name, brief, params=None, returns=None, example=None, note=None, see=None, warning=None, **kw):
    d = {"name": name, "brief": brief}
    if params: d["params"] = params
    if returns: d["returns"] = returns
    if note: d["note"] = note
    if warning: d["warning"] = warning
    if see: d["see"] = see
    if example: d["example"] = example
    d.update(kw)
    return d

P = lambda lines: lines

DOC = {
"class": "stzList",
"receiver": R,
"class_block": {
    "brief": "Holds a list of items of any type and finds, sorts, edits, groups and compares them.",
    "detail": "A stzList wraps a Ring list so that every operation on it has one name that reads like the sentence it stands for: Find, Remove, Replace, Section, Sorted. Active forms change the list in place (Sort), passive forms return a changed copy (Sorted), and the Q forms return the object so calls chain. Reach for it before writing a loop over a list.",
    "receiver": R,
    "example": ['? @@( o1.Find("b") )', '#--> [ 2, 4 ]'],
    "see": ["stzString", "stzListOfNumbers", "stzHashList"],
},
"entries": [
 E("Show", "Prints the list in its computable @@ form.", returns="nothing; the list is printed", see=["ShowShort", "Stringified"], example=['o1.Show()'], printing=True),
 E("Find", "Returns the positions of every occurrence of the item, as a list of numbers.",
   params={"pItem": "the item to look for, of any type"}, returns="a list of numbers; [ ] when the item is absent",
   note=["case-sensitive: FindCS takes the flag"], see=["FindFirst", "FindLast", "FindNth", "Contains"],
   example=['? @@( o1.Find("b") )', '? @@( o1.Find("z") )']),
 E("Count", "Returns how many times the item occurs in the list.",
   params={"pItem": "the item to count"}, returns="a number", see=["NumberOfOccurrence", "Find"],
   example=['? o1.Count("b")', '? o1.Count("z")']),
 E("Section", "Returns the items from position n1 to position n2, both included.",
   params={"_n1_": "the first position", "_n2_": "the last position"}, returns="a list of the items of that section",
   see=["Range", "RemoveSection", "Sections"], example=['? @@( o1.Section(2, 3) )']),
 E("Contains", "TRUE if the list holds the given item.",
   params={"pItem": "the item to look for"}, returns="TRUE or FALSE", note=["case-sensitive: ContainsCS takes the flag"],
   see=["Find", "ContainsOneOfThese"], example=['? o1.Contains("c")', '? o1.Contains("z")']),
 E("FindAll", "Returns the positions of every occurrence of the item, as Find does.",
   params={"pItem": "the item to look for"}, returns="a list of numbers; [ ] when the item is absent", see=["Find"],
   example=['? @@( o1.FindAll("b") )']),
 E("ToString", "Returns the items as one string, one item per line.",
   returns="a string; an item that is neither text nor a number is written in its @@ form", see=["Join", "Stringified"],
   example=['? o1.ToString()'], printing=True),
 E("Copy", "Returns a new stzList with the same items, so the copy can change without touching this one.",
   returns="a new stzList", example=['o2 = o1.Copy()', 'o2.Add("z")', '? @@( o1.Content() )', '? @@( o2.Content() )']),
 E("FindFirst", "Returns the position of the first occurrence of the item.",
   params={"pItem": "the item to look for"}, returns="a number; 0 when the item is absent", see=["Find", "FindLast", "FindNth"],
   example=['? o1.FindFirst("b")', '? o1.FindFirst("z")']),
 E("IsEqualTo", "TRUE if the list holds the same items as the given list, in any order, each item as many times.",
   params={"paOtherList": "the list to compare with"}, returns="TRUE or FALSE", note=["order does not matter: IsStrictlyEqualTo also compares the positions"],
   see=["IsStrictlyEqualTo"],
   example=['? o1.IsEqualTo([ "c", "b", "a", "b" ])', '? o1.IsEqualTo([ "a", "b", "c" ])']),
 E("Max", "Returns the greatest number of the list.",
   returns="a number; 0 for an empty list", see=["Min", "Sum", "Mean"], example=[RN, '? o1.Max()']),
 E("Add", "Appends the item at the end of the list, in place.",
   params={"pItem": "the item to add"}, returns="nothing; the list changes. AddQ returns the object for chaining", see=["Append", "Extend", "InsertBefore"],
   example=['o1.Add("z")', '? @@( o1.Content() )']),
 E("NumberOfOccurrence", "Returns how many times the item occurs in the list.",
   params={"pItem": "the item to count"}, returns="a number", see=["Count"], example=['? o1.NumberOfOccurrence("b")']),
 E("Replace", "Replaces every occurrence of the item by the new item, in place.",
   params={"pItem": "the item to replace", "pNewItem": "the item to put instead"}, returns="nothing; the list changes",
   see=["ReplaceAt", "ReplaceByMany", "ReplaceManyByMany"], example=['o1.Replace("b", "B")', '? @@( o1.Content() )']),
 E("DuplicatedItems", "Returns the items that occur more than once, each listed once.",
   returns="a list of items", see=["FindDuplicates", "NumberOfDuplicates", "ContainsDuplicatedItems"], example=['? @@( o1.DuplicatedItems() )']),
 E("Mean", "Returns the arithmetic mean of the numbers of the list.",
   returns="a number; 0 for an empty list", see=["Median", "Sum", "Max"], example=[RN, '? o1.Mean()']),
 E("Uppercased", "Returns a copy of the list with every text item in uppercase; the list is unchanged.",
   returns="a list; items that are not text pass through", see=["Lowercased", "UppercaseQ"], example=['? @@( o1.Uppercased() )']),
 E("RemoveDuplicates", "Removes the repeated occurrences of every item, keeping the first of each, in place.",
   returns="nothing; the list changes", see=["WithoutDuplication", "DuplicatedItems"],
   example=['o1.RemoveDuplicates()', '? @@( o1.Content() )']),
 E("Sum", "Returns the sum of the numbers of the list.",
   returns="a number; 0 for an empty list", see=["Mean", "Max"], example=[RN, '? o1.Sum()']),
 E("NumberOfItems", "Returns how many items the list holds.",
   returns="a number", see=["Count", "IsEmpty"], example=['? o1.NumberOfItems()']),
 E("IsLowercase", "TRUE if every item is a text in lowercase.",
   returns="TRUE or FALSE; FALSE for an empty list or when an item is not text", see=["IsUppercase", "Lowercased"],
   example=['? o1.IsLowercase()', 'o1 = new stzList([ "a", "B" ])', '? o1.IsLowercase()']),
 E("Min", "Returns the smallest number of the list.",
   returns="a number; 0 for an empty list", see=["Max", "Sum"], example=[RN, '? o1.Min()']),
 E("IsEmpty", "TRUE if the list holds no item.", returns="TRUE or FALSE", see=["NumberOfItems"],
   example=['? o1.IsEmpty()', 'o1 = new stzList([])', '? o1.IsEmpty()']),
 E("Reversed", "Returns a copy of the list in reverse order; the list is unchanged.",
   returns="a list", see=["Reverse"], example=['? @@( o1.Reversed() )']),
 E("NumberOfChars", "Returns how many items are a single character.",
   returns="a number", note=["it counts single-character items, not the characters inside longer texts"], see=["Chars"],
   example=['o1 = new stzList([ "a", "bb", "c" ])', '? o1.NumberOfChars()']),
 E("FindLast", "Returns the position of the last occurrence of the item.",
   params={"pItem": "the item to look for"}, returns="a number; 0 when the item is absent", see=["FindFirst", "Find"],
   example=['? o1.FindLast("b")', '? o1.FindLast("z")']),
 E("Sorted", "Returns a copy of the list sorted in ascending order; the list is unchanged.",
   returns="a list", see=["Sort", "SortedInDescending", "IsSortedInAscending"], example=['? @@( o1.Sorted() )']),
 E("Lowercased", "Returns a copy of the list with every text item in lowercase; the list is unchanged.",
   returns="a list; items that are not text pass through", see=["Uppercased"], example=['o1 = new stzList([ "A", "b", 7 ])', '? @@( o1.Lowercased() )']),
 E("Remove", "Removes every occurrence of the item, in place.",
   params={"pItem": "the item to remove"}, returns="nothing; the list changes", see=["RemoveAll", "RemoveAt", "RemoveSection"],
   example=['o1.Remove("b")', '? @@( o1.Content() )']),
 E("FindNth", "Returns the position of the nth occurrence of the item.",
   params={"_n_": "which occurrence, counting from 1", "pItem": "the item to look for"}, returns="a number; 0 when there are fewer than n occurrences",
   see=["Find", "FindFirst", "FindLast"], example=['? o1.FindNth(2, "b")', '? o1.FindNth(3, "b")']),
 E("StzType", "Returns the Softanza type symbol of the object, always :stzList.",
   returns="the symbol :stzList, which prints as stzlist", example=['? o1.StzType()']),
 E("FindDuplicates", "Returns the positions of every repeated occurrence, leaving out the first occurrence of each item.",
   returns="a list of numbers", see=["DuplicatedItems", "NumberOfDuplicates"], example=['? @@( o1.FindDuplicates() )']),
 E("IsUppercase", "TRUE if every item is a text in uppercase.",
   returns="TRUE or FALSE; FALSE for an empty list or when an item is not text", see=["IsLowercase", "Uppercased"],
   example=['? o1.IsUppercase()', 'o1 = new stzList([ "A", "B" ])', '? o1.IsUppercase()']),
 E("FindNext", "Returns the position of the next occurrence of the item after the given position.",
   params={"pItem": "the item to look for", "pnStartingAt": "the position to start after; :StartingAt = n is accepted"},
   returns="a number; 0 when there is none", see=["FindPrevious", "FindNth"], example=['? o1.FindNext("b", 2)', '? o1.FindNext("b", 4)']),
 E("Classify", "Groups the positions of the items by item, one [ item, positions ] pair per distinct item.",
   returns="a list of [ item, list of positions ] pairs, in order of first appearance", see=["Mode", "MostFrequent", "NumberOfClasses"],
   example=['? @@( o1.Classify() )']),
 E("UppercaseQ", "Puts every text item in uppercase, in place, and returns the object so the call can chain.",
   returns="the object itself", see=["Uppercased"], example=['o1.UppercaseQ()', '? @@( o1.Content() )']),
 E("Map", "Returns the list of the results of an expression applied to every item.",
   params={"pcExpr": "the expression, as text, where @item stands for the current item"}, returns="a list of the results, one per item",
   see=["Filter", "Perform"], example=[RN, '? @@( o1.Map("2*@item") )']),
 E("Extend", "Appends an item, or every item of a list, at the end of the list, in place.",
   params={"pWith": "an item, or a list whose items are appended one by one"}, returns="nothing; the list changes. ExtendQ returns the object for chaining",
   see=["Add", "ExtendTo"], example=['o1.Extend([ "x", "y" ])', '? @@( o1.Content() )']),
 E("Sections", "Returns the given sections of the list, each as a list of items.",
   params={"paSections": "a list of sections, each [ start, end ]"}, returns="a list of lists",
   see=["Section", "SplitBeforePositions"], example=['? @@( o1.Sections([ [ 1, 2 ], [ 3, 4 ] ]) )']),
 E("Repeated", "Returns a list that holds this list n times, nested.",
   params={"_n_": "how many times; n or n :Times is accepted"}, returns="a list of n copies of the list",
   note=["it nests: for the flat repetition use MultiplyBy"], example=['? @@( o1.Repeated(2) )']),
 E("Stringified", "Returns the list as a string in its computable @@ form.",
   returns="a string", see=["ToString", "Show"], example=['? o1.Stringified()']),
 E("VizFind", "Returns a picture of where the item occurs: the list as code, with a ^ under each occurrence.",
   params={"pItem": "the item to look for"}, returns="a string of two lines", see=["Find"], example=['? o1.VizFind("b")'], printing=True),
 E("RemoveAll", "Removes every occurrence of the item, in place.",
   params={"pItem": "the item to remove"}, returns="nothing; the list changes", see=["Remove", "RemoveAt"],
   example=['o1.RemoveAll("b")', '? @@( o1.Content() )']),
 E("Names", "Returns the Unicode name of every item, when the items are characters.",
   returns="a list of names", warning=["it raises an error when the list is not a list of characters"], example=['? @@( o1.Names() )']),
 E("ReplaceAt", "Replaces the item at position n by the new item, in place.",
   params={"_n_": "the position, or a list of positions", "pNewItem": "the item to put there; :With = item is accepted"},
   returns="nothing; the list changes", see=["Replace", "ReplaceSection"], example=['o1.ReplaceAt(2, "X")', '? @@( o1.Content() )']),
 E("Swap", "Exchanges the items at the two given positions, in place.",
   params={"_n1_": "the first position", "_n2_": "the second position"}, returns="nothing; the list changes",
   example=['o1.Swap(1, 3)', '? @@( o1.Content() )']),
 E("SortInAscending", "Sorts the items in ascending order, in place, as Sort does.",
   returns="nothing; the list changes", see=["Sort", "Sorted"], example=[RN, 'o1.SortInAscending()', '? @@( o1.Content() )']),
 E("Chars", "Returns the items that are a single character.",
   returns="a list of those items", see=["NumberOfChars"], example=['o1 = new stzList([ "a", "bb", "c" ])', '? @@( o1.Chars() )']),
 E("Range", "Returns a number of items from a start position.",
   params={"pnStart": "the first position, or :First or :Last", "pnRange": "how many items to take"}, returns="a list of the items taken",
   see=["Section"], example=['? @@( o1.Range(2, 2) )']),
 E("Sort", "Sorts the items in ascending order, in place.",
   returns="nothing; the list changes", see=["Sorted", "SortInAscending"], example=[RN, 'o1.Sort()', '? @@( o1.Content() )']),
 E("ReplaceSection", "Replaces the items from position n1 to position n2 by one new item, in place.",
   params={"_n1_": "the first position of the section", "_n2_": "the last position of the section", "pNewItem": "the item that takes its place"},
   returns="nothing; the list changes", see=["Section", "ReplaceAt"], example=['o1.ReplaceSection(2, 3, "Z")', '? @@( o1.Content() )']),
 E("RemoveSpaces", "Removes the items that are a single space, in place.",
   returns="nothing; the list changes", example=['o1 = new stzList([ "a", " ", "b" ])', 'o1.RemoveSpaces()', '? @@( o1.Content() )']),
 E("MultiplyBy", "Replaces the list by a list that holds it n times, nested, in place.",
   params={"p": "how many times the list is repeated"}, returns="nothing; the list changes",
   see=["Repeated"], example=['o1.MultiplyBy(2)', '? @@( o1.Content() )']),
 E("Unicodes", "Returns the Unicode codepoint of every item that is a character.",
   returns="a list: a number stays a number, a character gives its codepoint, a longer text gives the list of its codepoints",
   example=['o1 = new stzList([ "a", "bb", "c" ])', '? @@( o1.Unicodes() )']),
 E("FindPrevious", "Returns the position of the nearest occurrence of the item before the given position.",
   params={"pItem": "the item to look for", "pnStartingAt": "the position to look before; :StartingAt = n is accepted"},
   returns="a number; 0 when there is none", see=["FindNext"], example=['? o1.FindPrevious("b", 4)', '? o1.FindPrevious("b", 2)']),
 E("ReplaceManyByMany", "Replaces each of several items by the item at the same place in a second list, in place.",
   params={"paItems": "the items to replace", "paNewItems": "the replacements, in the same order"}, returns="nothing; the list changes",
   see=["Replace", "ReplaceByMany"], example=['o1.ReplaceManyByMany([ "a", "b" ], [ "1", "2" ])', '? @@( o1.Content() )']),
 E("Reverse", "Reverses the order of the items, in place.",
   returns="nothing; the list changes. ReverseQ returns the object for chaining", see=["Reversed"],
   example=['o1.Reverse()', '? @@( o1.Content() )']),
 E("Bounds", "Returns the first and the last items of the list.",
   returns="a list of two items", see=["IsBoundedBy"], example=['? @@( o1.Bounds() )']),
 E("FindItems", "Returns every distinct item with the positions where it occurs.",
   returns="a list of [ item, list of positions ] pairs, in order of first appearance", see=["Find", "Classify"],
   example=['? @@( o1.FindItems() )']),
 E("Trim", "Removes the empty items at both ends of the list, in place.",
   returns="nothing; the list changes", example=['o1 = new stzList([ "", "a", "" ])', 'o1.Trim()', '? @@( o1.Content() )']),
 E("Join", "Returns the items joined into one string with the separator between them.",
   params={"pcSep": "the text put between two items"}, returns="a string", see=["ToString"], example=['? o1.Join("-")']),
 E("Item", "Returns the item at position n.",
   params={"_n_": "a position from 1 to the number of items; a negative position counts from the end; \"first\" and \"last\" are accepted"},
   returns="the item, of any type", warning=["a position beyond the end raises an error"], see=["Section", "Find"],
   example=['? o1.Item(3)', '? o1.Item(-1)']),
 E("StartsWith", "TRUE if the list begins with the given items, in order.",
   params={"paItems": "the items it should begin with"}, returns="TRUE or FALSE", see=["EndsWith"],
   example=['? o1.StartsWith([ "a", "b" ])', '? o1.StartsWith([ "b" ])']),
 E("ContainsDuplicatedItems", "TRUE if some item occurs more than once.",
   returns="TRUE or FALSE", see=["DuplicatedItems", "NumberOfDuplicates"], example=['? o1.ContainsDuplicatedItems()']),
 E("ExtendTo", "Pads the list up to position n, with 0 for a list of numbers and an empty text otherwise, in place.",
   params={"_n_": "the length to reach"}, returns="nothing; the list changes. ExtendToXT chooses the padding item",
   see=["Extend"], example=['o1.ExtendTo(6)', '? @@( o1.Content() )']),
 E("InsertBefore", "Inserts the item before position n, in place.",
   params={"_n_": "the position to insert before", "pItem": "the item to insert"}, returns="nothing; the list changes",
   see=["InsertAfter", "Add"], example=['o1.InsertBefore(2, "X")', '? @@( o1.Content() )']),
 E("SplitAt", "Splits the list at a position into the items before it and the items from it.",
   params={"_n_": "the position where the second part starts"}, returns="a list of two lists",
   see=["SplitBeforePositions"], example=['? @@( o1.SplitAt(2) )']),
 E("IsBoundedBy", "TRUE if the list begins and ends with the given pair of items.",
   params={"paBounds": "the two items, [ first, last ]"}, returns="TRUE or FALSE", see=["Bounds"],
   example=['o1 = new stzList([ "<", "a", ">" ])', '? o1.IsBoundedBy([ "<", ">" ])']),
 E("Mode", "Returns the items that occur most often.",
   returns="a list of items, more than one when they tie", see=["MostFrequent", "Classify"], example=['? @@( o1.Mode() )']),
 E("Numbers", "Returns the items that are numbers.",
   returns="a list of numbers", see=["Chars"], example=['o1 = new stzList([ "a", 1, "b", 2 ])', '? @@( o1.Numbers() )']),
 E("NumberOfDuplicates", "Returns how many repeated occurrences the list holds, counting every one after the first.",
   returns="a number", note=["it counts occurrences, not distinct duplicated items: [ a, a, a ] gives 2"], see=["DuplicatedItems", "FindDuplicates"],
   example=['? o1.NumberOfDuplicates()']),
 E("ReplaceByMany", "Replaces each occurrence of the item by the items of a list in turn, in place.",
   params={"pItem": "the item to replace", "paNewItems": "the replacements, used one per occurrence"}, returns="nothing; the list changes",
   see=["Replace", "ReplaceManyByMany"], example=['o1.ReplaceByMany("b", [ "1", "2" ])', '? @@( o1.Content() )']),
 E("SplitBeforePositions", "Splits the list before each of the given positions, in place.",
   params={"panPos": "the positions to split before"}, returns="nothing; the list becomes a list of sections",
   see=["SplitAt"], example=['o1.SplitBeforePositions([ 2, 4 ])', '? @@( o1.Content() )']),
 E("Flattened", "Returns a copy of the list with every nested list opened out; the list is unchanged.",
   returns="a flat list", example=['o1 = new stzList([ [ 1, 2 ], [ 3, [ 4 ] ] ])', '? @@( o1.Flattened() )']),
 E("Are", "TRUE if every item is of the given kind, such as :Strings or :Numbers.",
   params={"p": "a kind such as :Strings, :Numbers, :Uppercase, or a list of kinds that must all hold"}, returns="TRUE or FALSE; FALSE for an empty list",
   see=["IsUppercase", "IsLowercase"], example=['? o1.Are(:Strings)', '? o1.Are(:Numbers)']),
 E("Filter", "Returns the items for which an expression is true.",
   params={"pcExpr": "the condition, as text, where @item stands for the current item"}, returns="a list of the items that pass",
   see=["Map"], example=[RN, '? @@( o1.Filter("@item > 2") )']),
 E("NumberOfPairs", "Returns how many items are a [ key, value ] pair.",
   returns="a number; 0 for a list that holds no pair", see=["NumberOfItems"],
   example=['o1 = new stzList([ [ "x", 1 ], [ "y", 2 ] ])', '? o1.NumberOfPairs()', '? o1.NumberOfItems()']),
 E("Append", "Appends the item at the end of the list, in place, as Add does.",
   params={"pItem": "the item to append"}, returns="nothing; the list changes. AppendQ returns the object for chaining", see=["Add"],
   example=['o1.Append("e")', '? @@( o1.Content() )']),
 E("ContainsOneOfThese", "TRUE if the list holds at least one of the given items.",
   params={"paItems": "the items to look for"}, returns="TRUE or FALSE", see=["Contains"],
   example=['? o1.ContainsOneOfThese([ "x", "c" ])', '? o1.ContainsOneOfThese([ "x", "y" ])']),
 E("IsStrictlyEqualTo", "TRUE if the list holds the same items at the same positions as the given list.",
   params={"paOtherList": "the list to compare with"}, returns="TRUE or FALSE", see=["IsEqualTo"],
   example=['? o1.IsStrictlyEqualTo([ "a", "b", "c", "b" ])', '? o1.IsStrictlyEqualTo([ "a", "b", "b", "c" ])']),
 E("EndsWith", "TRUE if the list ends with the given items, in order.",
   params={"paItems": "the items it should end with"}, returns="TRUE or FALSE", see=["StartsWith"],
   example=['? o1.EndsWith([ "c", "b" ])', '? o1.EndsWith([ "c" ])']),
 E("IsSortedInAscending", "TRUE if the items are in ascending order.",
   returns="TRUE or FALSE", see=["IsSortedInDescending", "SortingOrder", "Sort"], example=['? o1.IsSortedInAscending()', 'o1 = new stzList([ 1, 2, 2, 5 ])', '? o1.IsSortedInAscending()']),
 E("InsertAfter", "Returns a copy of the list with the item inserted after position n; the list is unchanged.",
   params={"pnPos": "the position to insert after; :ItemAtPosition = n is accepted", "pItem": "the item to insert"}, returns="a list",
   see=["InsertBefore"], example=['? @@( o1.InsertAfter(2, "X") )', '? @@( o1.Content() )']),
 E("RemoveSection", "Removes the items from position n1 to position n2, both included, in place.",
   params={"_n1_": "the first position of the section", "_n2_": "the last position of the section"}, returns="nothing; the list changes",
   see=["Section", "RemoveAt"], example=['o1.RemoveSection(2, 3)', '? @@( o1.Content() )']),
 E("NumberOfOccurrences", "Returns how many times the item occurs in the list.",
   params={"pItem": "the item to count"}, returns="a number", see=["Count", "NumberOfOccurrence"], example=['? o1.NumberOfOccurrences("b")']),
 E("Perform", "Replaces every item by the result of an expression applied to it, in place.",
   params={"pcAction": "the expression, as text, where @item stands for the current item"}, returns="nothing; the list changes",
   see=["Map"], example=['o1.Perform("@item + @item")', '? @@( o1.Content() )']),
 E("SortingOrder", "Returns the order the items are in: :Ascending, :Descending or unsorted.",
   returns="a symbol, which prints in lowercase", see=["IsSortedInAscending", "IsSortedInDescending"],
   example=['? o1.SortingOrder()', 'o1 = new stzList([ 1, 2, 3 ])', '? o1.SortingOrder()']),
 E("FindNthPrevious", "Returns the position of the nth occurrence of the item, counting backward from a position.",
   params={"_n_": "which occurrence, counting from 1", "pItem": "the item to look for", "pnStartingAt": "the position to start from"},
   returns="a number; 0 when there are fewer than n", see=["FindPrevious", "FindNth"], example=['? o1.FindNthPrevious(1, "b", 4)', '? o1.FindNthPrevious(2, "b", 4)']),
 E("IsSortedInDescending", "TRUE if the items are in descending order.",
   returns="TRUE or FALSE", see=["IsSortedInAscending", "SortingOrder"], example=['o1 = new stzList([ 5, 3, 3, 1 ])', '? o1.IsSortedInDescending()', '? o1.IsSortedInAscending()']),
 E("NumberOfClasses", "Returns how many different items the list holds.",
   returns="a number", see=["Classify", "NumberOfItems"], example=['? o1.NumberOfClasses()']),
 E("RemoveAt", "Removes the item at position n, in place.",
   params={"_n_": "the position of the item to remove"}, returns="nothing; the list changes", see=["Remove", "RemoveSection"],
   example=['o1.RemoveAt(2)', '? @@( o1.Content() )']),
 E("SortedInDescending", "Returns a copy of the list sorted in descending order; the list is unchanged.",
   returns="a list", see=["Sorted", "IsSortedInDescending"], example=['? @@( o1.SortedInDescending() )']),
 E("UnionWith", "Returns the items of both lists, each once; the list is unchanged.",
   params={"paOtherList": "the list to merge in"}, returns="a list, in order of first appearance",
   see=["CommonItems"], example=['? @@( o1.UnionWith([ "b", "z" ]) )', '? @@( o1.Content() )']),
 E("CommonItems", "Returns the items of the list that also occur in the given list, each once, in this list's order.",
   params={"pNamedWith": "the other list, or :With = list"}, returns="a list", see=["UnionWith"],
   example=['? @@( o1.CommonItems([ "b", "z", "a" ]) )']),
 E("Extract", "Takes every occurrence of the item out of the list, in place, and returns the item.",
   params={"pItem": "the item to extract"}, returns="the item that was taken out", see=["Remove"],
   example=['? o1.Extract("b")', '? @@( o1.Content() )']),
 E("Median", "Returns the median of the numbers of the list.",
   returns="a number; 0 for an empty list", see=["Mean", "Max"], example=[RN, '? o1.Median()']),
 E("MostFrequent", "Returns the item that occurs most often.",
   returns="an item", see=["Mode"], example=['? o1.MostFrequent()']),
 E("WithoutDuplication", "Returns a copy of the list with every item once, in order of first appearance; the list is unchanged.",
   returns="a list", see=["RemoveDuplicates"], example=['? @@( o1.WithoutDuplication() )']),
 E("ShowShort", "Prints an abbreviated form of the list: its first three items, then \"...\", then its last three.",
   returns="nothing; the list is printed", note=["a list of six items or fewer is printed whole"], see=["Show"],
   example=['o1 = new stzList([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 ])', 'o1.ShowShort()'], printing=True),
 E("BoundsOf", "Returns, for each occurrence of the item, the n items before it and the n after it, as [ before, after ].",
   params={"pItem": "the item to look around", "pUpTo": "how many items on each side; :UpToNItems = n is accepted"},
   returns="a list of [ before, after ] pairs, one per occurrence; a side without room for n items comes out empty", see=["Bounds", "Section"],
   example=['o1 = new stzList([ "*", "a", "b", "c", "*", "d", "e" ])', '? @@( o1.BoundsOf("*", 2) )']),
 E("Product", "Returns the product of the numbers of the list.",
   returns="a number", see=["Sum", "Reduce"], example=[RN, '? o1.Product()']),
 E("Stddev", "Returns the sample standard deviation of the numbers of the list.",
   returns="a number: the square root of Variance", see=["Variance", "Mean"], example=[RN, '? o1.Stddev()']),
 E("Variance", "Returns the sample variance of the numbers of the list, dividing by n - 1.",
   returns="a number", see=["Stddev", "Mean"], example=[RN, '? o1.Variance()']),
 E("DeepFind", "Returns the path to every occurrence of the item, at any depth of nested lists.",
   params={"pItem": "the item to look for"}, returns="a list of paths, each a list of positions from the top down", see=["Find", "DeepReplace"],
   example=['o1 = new stzList([ "a", [ "b", "a" ] ])', '? @@( o1.DeepFind("a") )']),
 E("DeepReplace", "Replaces every occurrence of the item, at any depth of nested lists, in place.",
   params={"pOld": "the item to replace", "pNew": "the item to put instead; :By = item is accepted"}, returns="nothing; the list changes", see=["DeepFind", "Replace"],
   example=['o1 = new stzList([ "a", [ "b", "a" ] ])', 'o1.DeepReplace("a", :By = "X")', '? @@( o1.Content() )']),
 E("FindNthOccurrence", "Returns the position of the nth occurrence of the item, as FindNth does.",
   params={"_n_": "which occurrence, counting from 1", "pItem": "the item to look for"}, returns="a number; 0 when there are fewer than n",
   see=["FindNth"], example=['? o1.FindNthOccurrence(2, "b")']),
 E("FindObjects", "Returns the positions of the items that are objects.",
   returns="a list of numbers; [ ] when no item is an object", see=["Types"], example=['? @@( o1.FindObjects() )']),
 E("GroupBy", "Groups the positions of the items by the value of an expression.",
   params={"pcExpr": "the expression, as text, where @item stands for the current item"},
   returns="a list of [ value as text, positions ] pairs, in order of first appearance", note=["it groups the positions, not the items"],
   see=["Classify"], example=[RN, '? @@( o1.GroupBy("@item % 2") )']),
 E("DuplicatesRemoved", "Returns a copy of the list without its repeated items, keeping the first of each; the list is unchanged.",
   returns="a list", see=["RemoveDuplicates", "WithoutDuplication"], example=['? @@( o1.DuplicatesRemoved() )']),
 E("SortInDescending", "Sorts the items in descending order, in place.",
   returns="nothing; the list changes", see=["SortedInDescending", "Sort"], example=[RN, 'o1.SortInDescending()', '? @@( o1.Content() )']),
 E("Trimmed", "Returns a copy of the list without the empty items at both ends; the list is unchanged.",
   returns="a list", see=["Trim"], example=['o1 = new stzList([ "", "a", "" ])', '? @@( o1.Trimmed() )']),
 E("Types", "Returns the type of every item: \"NUMBER\", \"STRING\", \"LIST\" or \"OBJECT\".",
   returns="a list of type names, one per item", see=["FindObjects"], example=['o1 = new stzList([ 1, "a", [ 2 ] ])', '? @@( o1.Types() )']),
 E("Reduce", "Returns the sum of the numbers of the list.",
   returns="a number", see=["Sum", "Product"], example=[RN, '? o1.Reduce()']),
 E("SplitAfter", "Splits the list after each occurrence of the item, but a known defect makes the call do nothing today.",
   params={"pItem": "the item that closes each part"}, returns="nothing today",
   warning=["known defect: the call changes nothing and returns nothing, because it splits a copy of the list; SplitAt and SplitBeforePositions work"],
   see=["SplitAt", "SplitBeforePositions"]),
 E("SplitBefore", "Splits the list before each occurrence of the item, but a known defect makes the call do nothing today.",
   params={"pItem": "the item that opens each part"}, returns="nothing today",
   warning=["known defect: the call changes nothing and returns nothing, because it splits a copy of the list; SplitAt and SplitBeforePositions work"],
   see=["SplitAt", "SplitBeforePositions"]),

]}
