R = 'o1 = new stzString("banana")'
RT = 'o1 = new stzString("the quick fox")'
RU = 'o1 = new stzString("<<a>> and <<b>>")'

def E(name, brief, params=None, returns=None, example=None, note=None, see=None, warning=None, **kw):
    d = {"name": name, "brief": brief}
    if params: d["params"] = params
    if returns: d["returns"] = returns
    if note: d["note"] = note
    if warning: d["warning"] = warning
    if see: d["see"] = see
    if example: d["example"] = example
    d.update(kw)
    return d

DOC = {
"class": "stzString",
"receiver": R,
"class_block": {
    "brief": "Holds a text and finds, cuts, edits, splits and compares it, character by character, in Unicode.",
    "detail": "A stzString counts characters, not bytes: positions, lengths and sections are in Unicode codepoints, so Hebrew, Arabic, Chinese and emoji behave like Latin letters. Active forms change the text in place (Remove, Uppercase), passive forms return a changed copy (Uppercased), and the Q forms return the object so calls chain. Reach for it before writing a loop over a text.",
    "receiver": R,
    "example": ['? @@( o1.Find("an") )', '#--> [ 2, 4 ]'],
    "see": ["stzList", "stzText", "stzChar"],
},
"entries": [
 E("Content", "Returns the text the object holds.", returns="a string", see=["Copy", "Show"], example=['? o1.Content()']),
 E("Show", "Prints the text on its own line.", returns="nothing; the text is printed", see=["Content"], example=['o1.Show()'], printing=True),
 E("Find", "Returns the positions of every occurrence of the substring, as a list of numbers.",
   params={"pcSubStr": "the text to look for, or a list of texts to look for together"}, returns="a list of numbers; [ ] when it is absent",
   note=["positions are in characters, not bytes", "case-sensitive: FindCS takes the flag"], see=["FindFirst", "FindLast", "FindNth", "Contains", "Count"],
   example=['? @@( o1.Find("an") )', '? @@( o1.Find("z") )']),
 E("Count", "Returns how many times the substring occurs in the text.",
   params={"pcSubStr": "the text to count"}, returns="a number", see=["Find", "NumberOfOccurrence"],
   example=['? o1.Count("an")', '? o1.Count("z")']),
 E("Section", "Returns the characters from position n1 to position n2, both included.",
   params={"_n1_": "the first position, or :From = text to start at the first occurrence of a text", "_n2_": "the last position, or :To = text to end at the last occurrence of a text"},
   returns="a string", see=["Range", "RemoveSection", "Sections"], example=['? o1.Section(2, 4)', 'o1 = new stzString("SOFTANZA")', '? o1.Section(:From = "F", :To = "A")']),
 E("Contains", "TRUE if the text contains the given substring.",
   params={"pcSubStr": "the text to look for"}, returns="TRUE or FALSE", note=["case-sensitive: ContainsCS takes the flag"], see=["Find", "ContainsThese"],
   example=['? o1.Contains("nan")', '? o1.Contains("NAN")']),
 E("Replace", "Replaces every occurrence of a substring by another, in place.",
   params={"pcSubStr": "the text to replace, or a list of texts", "pcNewSubStr": "the text to put instead; :By = text is accepted, and :By = list replaces the occurrences one by one"},
   returns="nothing; the text changes. ReplaceQ returns the object for chaining", see=["ReplaceAt", "ReplaceByMany", "Remove"],
   example=['o1.Replace("an", "AN")', '? o1.Content()', 'o1 = new stzString("banana")', 'o1.Replace("an", :By = "XY")', '? o1.Content()']),
 E("FindFirst", "Returns the position of the first occurrence of the substring.",
   params={"pcSubStr": "the text to look for"}, returns="a number; -1 when the substring is absent", see=["Find", "FindLast", "FindNth"],
   example=['? o1.FindFirst("an")', '? o1.FindFirst("z")']),
 E("Remove", "Removes every occurrence of a substring, in place.",
   params={"pcSubStr": "the text to remove"}, returns="nothing; the text changes. RemoveQ returns the object for chaining", see=["RemoveAll", "RemoveAt", "RemoveSection", "Replace"],
   example=['o1.Remove("an")', '? o1.Content()']),
 E("Copy", "Returns a new stzString with the same text, so the copy can change without touching this one.",
   returns="a new stzString", example=['o2 = o1.Copy()', 'o2.Append("!")', '? o1.Content()', '? o2.Content()']),
 E("IsEqualTo", "TRUE if the text equals the given string, letter case included.",
   params={"pcStr": "the string to compare with"}, returns="TRUE or FALSE", note=["IsEqualToCS takes a case-sensitivity flag"], see=["IsStrictlyEqualTo"],
   example=['? o1.IsEqualTo("banana")', '? o1.IsEqualTo("Banana")']),
 E("FindLast", "Returns the position of the last occurrence of the substring.",
   params={"pcSubStr": "the text to look for"}, returns="a number; 0 when the substring is absent", see=["FindFirst", "Find", "FindNth"],
   example=['? o1.FindLast("an")', '? o1.FindLast("z")']),
 E("NumberOfChars", "Returns the length of the text in characters.",
   returns="a number of Unicode characters, not bytes", see=["SizeInBytes"], example=['? o1.NumberOfChars()', 'o1 = new stzString("héllo")', '? o1.NumberOfChars()']),
 E("Split", "Returns the parts of the text around a separator.",
   params={"pcSep": "the separator; :Using = sep and :By = sep are accepted"}, returns="a list of strings; the separator is not in the parts", see=["SplitAt", "Words", "Lines"],
   example=[RT, '? @@( o1.Split(" ") )', '? @@( o1.Split(:Using = " ") )']),
 E("FindNth", "Returns the position of the nth occurrence of the substring.",
   params={"n": "which occurrence, counting from 1", "pcSubStr": "the text to look for"}, returns="a number; -1 when there are fewer than n occurrences", see=["Find", "FindFirst", "FindLast"],
   example=['? o1.FindNth(2, "an")', '? o1.FindNth(3, "an")']),
 E("Check", "TRUE if an expression holds for every character of the text.",
   params={"pcExpr": "the expression, as text, where @char stands for the current character"}, returns="TRUE or FALSE; TRUE when the expression is empty", see=["Chars"],
   example=['? o1.Check("@char != \'z\'")', '? o1.Check("@char = \'a\'")']),
 E("BoundedBy", "Returns the pieces of text found between each opening bound and its closing bound.",
   params={"pacBounds": "the two bounds, [ open, close ]"}, returns="a list of strings, one per bounded piece", note=["the bounds themselves are not part of the pieces"], see=["Between", "IsBoundedBy", "FindAnyBoundedBy"],
   example=[RU, '? @@( o1.BoundedBy([ "<<", ">>" ]) )']),
 E("Uppercased", "Returns a copy of the text in uppercase; the text is unchanged.",
   returns="a string", note=["it follows Unicode rules: the German sharp s becomes SS"], see=["Uppercase", "Lowercased"],
   example=['? o1.Uppercased()', '? o1.Content()', 'o1 = new stzString("straße")', '? o1.Uppercased()']),
 E("RemoveDuplicates", "Is meant to remove the repeated characters of the text, in place.",
   returns="nothing today",
   warning=["known defect: the call raises error R14 today, because it calls UpdateWith, which this class does not define"],
   see=["Duplicates", "Remove"]),
 E("Uppercase", "Puts the text in uppercase, in place.",
   returns="nothing; the text changes. UppercaseQ returns the object for chaining", see=["Uppercased", "Lowercase"], example=['o1.Uppercase()', '? o1.Content()']),
 E("IsLowercase", "TRUE if the text is in lowercase.",
   returns="TRUE or FALSE", see=["IsUppercase", "Lowercased"], example=['? o1.IsLowercase()', 'o1 = new stzString("Banana")', '? o1.IsLowercase()']),
 E("IsEmpty", "TRUE if the text holds no character.",
   returns="TRUE or FALSE", see=["NumberOfChars"], example=['? o1.IsEmpty()', 'o1 = new stzString("")', '? o1.IsEmpty()']),
 E("NumberOfOccurrence", "Returns how many times the substring occurs in the text.",
   params={"pcSubStr": "the text to count; :Of = text is accepted"}, returns="a number", see=["Count"], example=['? o1.NumberOfOccurrence("a")']),
 E("Chars", "Returns the characters of the text, one per item.",
   returns="a list of one-character strings", see=["Unicodes", "NumberOfChars"], example=['? @@( o1.Chars() )']),
 E("FindAsSections", "Returns the occurrences of the substring as [ start, end ] sections.",
   params={"pcSubStr": "the text to look for"}, returns="a list of [ start, end ] pairs", see=["Find", "FindAsSection", "Sections"], example=['? @@( o1.FindAsSections("an") )']),
 E("Reversed", "Returns a copy of the text with its characters in reverse order; the text is unchanged.",
   returns="a string", see=["Reverse"], example=['? o1.Reversed()']),
 E("Script", "Returns the writing system the text is written in, such as latin or arabic.",
   returns="a symbol, which prints in lowercase", example=['? o1.Script()', 'o1 = new stzString("مرحبا")', '? o1.Script()']),
 E("Lowercased", "Returns a copy of the text in lowercase; the text is unchanged.",
   returns="a string", see=["Lowercase", "Uppercased"], example=['o1 = new stzString("Banana Split")', '? o1.Lowercased()']),
 E("Duplicates", "Returns the substrings that occur more than once, each listed once.",
   returns="a list of strings", see=["NumberOfDuplicates", "ContainsDuplicates", "FindDuplicates"], example=['? @@( o1.Duplicates() )']),
 E("StzType", "Returns the Softanza type symbol of the object, always :stzString.",
   returns="the symbol :stzString, which prints as stzstring", example=['? o1.StzType()']),
 E("AddXT", "Inserts a text at a place given by a named parameter, in place.",
   params={"p1": "the text to insert", "p2": "where: :After = text, :Before = text, :To = text, :AfterEach = text or :BeforeEach = text"},
   returns="nothing; the text changes", see=["InsertBefore", "Append"], example=['o1.AddXT("X", :After = "ba")', '? o1.Content()']),
 E("MultiplyBy", "Repeats the text n times, in place; a list distributes the text over its items.",
   params={"n": "a number: how many times the text is repeated; a list: each item is appended to a copy of the text in turn"},
   returns="nothing; the text changes", see=["Repeated"], example=['o1.MultiplyBy(2)', '? o1.Content()', 'o1 = new stzString("a")', 'o1.MultiplyBy([ "b", "c" ])', '? o1.Content()']),
 E("Spacify", "Puts a space between the characters of the text, in place.",
   returns="nothing; the text changes. SpacifyQ returns the object for chaining", example=['o1.Spacify()', '? o1.Content()']),
 E("SubStrings", "Returns every substring of the text, by start position then by length.",
   returns="a list of strings, with repeats", see=["NumberOfSubStrings", "Duplicates"], example=['o1 = new stzString("abc")', '? @@( o1.SubStrings() )']),
 E("IsUppercase", "TRUE if the text is in uppercase.",
   returns="TRUE or FALSE", see=["IsLowercase", "Uppercased"], example=['? o1.IsUppercase()', 'o1 = new stzString("BANANA")', '? o1.IsUppercase()']),
 E("FindNext", "Returns the position of the next occurrence of the substring after a position.",
   params={"pcSubStr": "the text to look for", "_nStart_": "the position to search after"}, returns="a number; 0 when there is none", see=["FindPrevious", "FindNth"],
   example=['? o1.FindNext("an", 2)', '? o1.FindNext("an", 4)']),
 E("FindDuplicates", "Returns the positions of the characters that already occurred earlier in the text.",
   returns="a list of numbers", see=["Duplicates", "NumberOfDuplicates"], example=['? @@( o1.FindDuplicates() )']),
 E("Unicode", "Returns the codepoint of a one-character text, or the list of codepoints of a longer one.",
   returns="a number, or a list of numbers when the text has more than one character", see=["Unicodes"],
   example=['o1 = new stzString("a")', '? o1.Unicode()', 'o1 = new stzString("ab")', '? @@( o1.Unicode() )']),
 E("Extend", "Appends a text, or pads the text with spaces up to a length, in place.",
   params={"pWith": "a string to append, or a number: the length to pad to"}, returns="nothing; the text changes", see=["Append"],
   example=['o1.Extend("!")', '? o1.Content()']),
 E("ToList", "Returns the list the text stands for: a list literal is evaluated, a range expands, any other text gives its characters.",
   returns="a list", see=["Chars", "IsListInString"], example=['o1 = new stzString("[1,2,3]")', '? @@( o1.ToList() )']),
 E("Sections", "Returns the pieces of text at the given [ start, end ] sections.",
   params={"_aSections_": "a list of [ start, end ] pairs; :Of = text gives the sections of that text"}, returns="a list of strings",
   see=["Section", "FindAsSections"], example=['? @@( o1.Sections([ [ 1, 2 ], [ 4, 6 ] ]) )']),
 E("RemoveAll", "Removes every occurrence of a substring, in place, as Remove does.",
   params={"pcSubStr": "the text to remove"}, returns="nothing; the text changes", see=["Remove"], example=['o1.RemoveAll("an")', '? o1.Content()']),
 E("Lines", "Returns the lines of the text, one per item.",
   returns="a list of strings", see=["NumberOfLines", "Words", "Split"], example=['o1 = new stzString("a" + nl + "b")', '? @@( o1.Lines() )']),
 E("Boxed", "Returns a copy of the text drawn inside a box; the text is unchanged.",
   returns="a string of three lines", example=['? o1.Boxed()'], printing=True),
 E("VizFind", "Returns the text followed by a line of marks that points at the start of each occurrence of the substring.",
   params={"pcSub": "the text to point at"}, returns="a string of two lines: ^ under the first character of a match, - elsewhere", see=["Find"], example=['? o1.VizFind("an")'], printing=True),
 E("FindAnyBoundedBy", "Returns the position where each bounded piece starts, the bounds left out.",
   params={"pacBounds": "the two bounds, [ open, close ], or one text used for both"}, returns="a list of numbers", see=["BoundedBy", "FindAnyBoundedByAsSections"],
   example=[RU, '? @@( o1.FindAnyBoundedBy([ "<<", ">>" ]) )']),
 E("ReplaceAt", "Replaces the substring that sits at position n by a new one, in place.",
   params={"n": "the position, or a list of positions", "pcOld": "the text expected at that position", "pcNew": "the text to put there; :By = text is accepted"},
   returns="nothing; the text changes", see=["Replace", "ReplaceSection"], example=['o1.ReplaceAt(2, "an", "XY")', '? o1.Content()']),
 E("Swap", "Exchanges the characters at two positions, in place.",
   params={"_n1_": "the first position", "_n2_": "the second position"}, returns="nothing; the text changes. SwapQ returns the object for chaining",
   example=['o1.Swap(1, 6)', '? o1.Content()']),
 E("SortInAscending", "Sorts the characters of the text in ascending order, in place.",
   returns="nothing; the text changes", see=["Sort", "SortedInAscending"], example=['o1.SortInAscending()', '? o1.Content()']),
 E("Repeated", "Returns the text repeated n times; the text is unchanged.",
   params={"n": "how many times; n :Times is accepted"}, returns="a string", see=["MultiplyBy"], example=['? o1.Repeated(2)', '? o1.Content()']),
 E("AndQ", "Returns the object itself, as a connecting word in a chain of calls.",
   returns="the object itself", example=['? o1.AndQ().Content()']),
 E("EndsWith", "TRUE if the text ends with the given suffix.",
   params={"pcSubStr": "the suffix to test"}, returns="TRUE or FALSE", see=["StartsWith"], example=['? o1.EndsWith("na")', '? o1.EndsWith("ba")']),
 E("IsNumberInString", "TRUE if the text is a number written as text.",
   returns="TRUE or FALSE", see=["IsNumericString", "NumericValue"], example=['o1 = new stzString("42")', '? o1.IsNumberInString()', 'o1 = new stzString("4x")', '? o1.IsNumberInString()']),
 E("Range", "Returns a number of characters from a start position.",
   params={"_nStart_": "the first position", "_nRange_": "how many characters to take"}, returns="a string", see=["Section"], example=['? o1.Range(2, 3)']),
 E("IsLetter", "TRUE if the text is a single letter.",
   returns="TRUE or FALSE", see=["IsNotLetter"], example=['o1 = new stzString("a")', '? o1.IsLetter()', 'o1 = new stzString("ab")', '? o1.IsLetter()']),
 E("NumberOfSubStrings", "Returns how many substrings the text has, repeats included: n(n+1)/2 for n characters.",
   returns="a number", see=["SubStrings"], example=['? o1.NumberOfSubStrings()']),
 E("Bounds", "Returns the run of identical characters at the start and the run at the end of the text.",
   returns="a list of two strings, [ leading run, trailing run ]", see=["BoundsOf", "LeadingCharsAsString"],
   example=['o1 = new stzString("**ab**")', '? @@( o1.Bounds() )']),
 E("Sort", "Sorts the characters of the text in ascending order, in place.",
   returns="nothing; the text changes. SortQ returns the object for chaining", see=["SortInAscending", "SortedInAscending"], example=['o1.Sort()', '? o1.Content()']),
 E("ReplaceSection", "Replaces the characters from position n1 to position n2 by a new text, in place.",
   params={"_n1_": "the first position of the section", "_n2_": "the last position of the section", "pcNewSubStr": "the text that takes its place; :With = text is accepted"},
   returns="nothing; the text changes", see=["Section", "ReplaceAt", "RemoveSection"], example=['o1.ReplaceSection(2, 4, "-")', '? o1.Content()']),
 E("RemoveSpaces", "Removes every space from the text, in place.",
   returns="nothing; the text changes. RemoveSpacesQ returns the object for chaining", see=["Trim"], example=[RT, 'o1.RemoveSpaces()', '? o1.Content()']),
 E("StartsWith", "TRUE if the text starts with the given prefix.",
   params={"pcSubStr": "the prefix to test"}, returns="TRUE or FALSE", see=["EndsWith"], example=['? o1.StartsWith("ba")', '? o1.StartsWith("na")']),
 E("Unicodes", "Returns the codepoint of every character, as a list.",
   returns="a list of numbers", see=["Unicode", "Chars"], example=['? @@( o1.Unicodes() )']),
 E("FindPrevious", "Returns the position of the last occurrence of the substring that ends before a position.",
   params={"pcSub": "the text to look for", "_nFrom_": "the position to look before; :StartingAt = n is accepted"}, returns="a number; 0 when there is none", see=["FindNext", "FindNthPrevious"],
   example=['? o1.FindPrevious("an", 5)', '? o1.FindPrevious("an", 2)']),
 E("ReplaceManyByMany", "Replaces each of several substrings by the one at the same place in a second list, in place.",
   params={"paSubStr": "the texts to replace", "paNewSubStr": "the replacements, in the same order"}, returns="nothing; the text changes", see=["Replace", "ReplaceByMany"],
   example=['o1.ReplaceManyByMany([ "b", "n" ], [ "B", "N" ])', '? o1.Content()']),
 E("Reverse", "Reverses the order of the characters, in place.",
   returns="nothing; the text changes. ReverseQ returns the object for chaining", see=["Reversed"], example=['o1.Reverse()', '? o1.Content()']),
 E("ToHex", "Returns the bytes of the text written in hexadecimal.",
   returns="a string of two hexadecimal digits per byte", example=['? o1.ToHex()']),
 E("Trim", "Removes the whitespace at both ends of the text, in place.",
   returns="nothing; the text changes. TrimQ returns the object for chaining", see=["Trimmed", "RemoveSpaces"], example=['o1 = new stzString("  hi  ")', 'o1.Trim()', '? "[" + o1.Content() + "]"']),
 E("SplitAt", "Returns the parts of the text cut at a separator or at a position.",
   params={"pcSepOrPos": "a separator, or a position: the character at that position is dropped; :Section = [ n1, n2 ] cuts out a section"},
   returns="a list of strings", see=["Split", "SplitBeforePositions", "SplitAtSections"], example=[RT, '? @@( o1.SplitAt(4) )', '? @@( o1.SplitAt(" ") )']),
 E("BoundsOf", "Returns the runs of identical characters on the left and on the right of a substring, for each occurrence bounded on both sides.",
   params={"pcSub": "the substring to look around"}, returns="a flat list: left run, right run, for each such occurrence", see=["Bounds"],
   example=['o1 = new stzString("**ab**")', '? @@( o1.BoundsOf("ab") )']),
 E("NumberOfLines", "Returns how many lines the text holds.",
   returns="a number", see=["Lines"], example=['o1 = new stzString("a" + nl + "b")', '? o1.NumberOfLines()']),
 E("FindAnyBoundedByAsSections", "Returns the [ start, end ] section of each bounded piece, the bounds left out.",
   params={"pacBounds": "the two bounds, [ open, close ], or one text used for both"}, returns="a list of [ start, end ] pairs", see=["FindAnyBoundedBy", "BoundedBy"],
   example=[RU, '? @@( o1.FindAnyBoundedByAsSections([ "<<", ">>" ]) )']),
 E("ReplaceAll", "Replaces every occurrence of a substring by another, in place, as Replace does.",
   params={"pcSubStr": "the text to replace", "pcNewSubStr": "the text to put instead"}, returns="nothing; the text changes", see=["Replace"],
   example=['o1.ReplaceAll("an", "AN")', '? o1.Content()']),
 E("Between", "Returns the text between the first occurrence of the first bound and the last occurrence of the second.",
   params={"pBound1": "the opening bound", "pBound2": "the closing bound"}, returns="a string",
   note=["it reads from the first opening bound to the last closing one: BoundedBy returns each bounded piece instead"], see=["BoundedBy"],
   example=[RU, '? o1.Between("<<", ">>")']),
 E("IsBoundedBy", "TRUE if the text begins with the opening bound and ends with the closing one.",
   params={"pacBounds": "the two bounds, [ open, close ]"}, returns="TRUE or FALSE", see=["BoundedBy", "Bounds"],
   example=[RU, '? o1.IsBoundedBy([ "<<", ">>" ])', '? o1.IsBoundedBy([ "<<", "!" ])']),
 E("FindInSection", "Returns the positions of the substring inside a section of the text, counted from the start of the whole text.",
   params={"pcSubStr": "the text to look for", "_n1_": "the first position of the section", "_n2_": "the last position of the section"}, returns="a list of numbers", see=["Find", "Section"],
   example=['? @@( o1.FindInSection("a", 2, 5) )']),
 E("Numbers", "Returns the numbers found in the text, each as a string.",
   returns="a list of strings", see=["NumbersComingAfter"], example=['o1 = new stzString("a1b22c")', '? @@( o1.Numbers() )']),
 E("FirstChar", "Returns the first character of the text.",
   returns="a one-character string", example=['? o1.FirstChar()']),
 E("NumbersComingAfter", "Returns the numbers that come right after the given substring, each as a string.",
   params={"pcSubStr": "the text the numbers follow"}, returns="a list of strings", see=["Numbers"],
   example=['o1 = new stzString("x 12 y 7")', '? @@( o1.NumbersComingAfter("x") )']),
 E("ReplaceByMany", "Replaces the occurrences of a substring one by one by the items of a list, in place.",
   params={"pcSubStr": "the text to replace", "paReplacements": "the replacements, used one per occurrence; :By = list is accepted"}, returns="nothing; the text changes", see=["Replace", "ReplaceManyByMany"],
   example=['o1.ReplaceByMany("an", [ "1", "2" ])', '? o1.Content()']),
 E("SplitBeforePositions", "Returns the parts of the text that begin at each of the given positions.",
   params={"anPos": "the positions where a new part begins"}, returns="a list of strings", see=["SplitAt", "SplitAtSections"],
   example=[RT, '? @@( o1.SplitBeforePositions([ 5, 11 ]) )']),
 E("FindAntiSections", "Returns the pieces of text outside the occurrences of a substring.",
   params={"pcSubStr": "the text whose occurrences are cut out"}, returns="a list of strings", see=["FindAsSections", "Sections"],
   example=['? @@( o1.FindAntiSections("an") )']),
 E("IsNumericString", "TRUE if the text is a number written as text.",
   returns="TRUE or FALSE", see=["IsNumberInString", "NumericValue"], example=['o1 = new stzString("42")', '? o1.IsNumericString()']),
 E("SortedInAscending", "Returns a copy of the text with its characters sorted in ascending order; the text is unchanged.",
   returns="a string", see=["SortInAscending", "SortedInDescending"], example=['? o1.SortedInAscending()']),
 E("Words", "Returns the words of the text, split at whitespace.",
   returns="a list of strings", see=["NumberOfWords", "Split"], example=[RT, '? @@( o1.Words() )']),
 E("NumericValue", "Returns the text as a number.",
   returns="a number", see=["IsNumberInString"], example=['o1 = new stzString("12.5")', '? o1.NumericValue()']),
 E("Append", "Appends a text at the end, in place.",
   params={"pcStr": "the text to append"}, returns="nothing; the text changes. AppendQ returns the object for chaining", see=["Extend", "InsertBefore"],
   example=['o1.Append("!")', '? o1.Content()']),
 E("NumberOfWords", "Returns how many words the text holds.",
   returns="a number", see=["Words"], example=[RT, '? o1.NumberOfWords()']),
 E("IsPositive", "TRUE if the text reads as positive in tone.",
   returns="TRUE or FALSE", note=["it judges the sentiment of the words, through the text layer"], see=["NamedEntities", "Language"],
   example=['o1 = new stzString("I love this")', '? o1.IsPositive()', 'o1 = new stzString("I hate this")', '? o1.IsPositive()']),
 E("NamedEntities", "Returns the people, places and other named things the text mentions, with their kind.",
   returns="a list of [ name, kind ] pairs", see=["Language", "IsPositive"], example=['o1 = new stzString("Paris and Bob")', '? @@( o1.NamedEntities() )']),
 E("InsertBefore", "Inserts a text before position n, in place.",
   params={"n": "the position to insert before, or a text to insert before; :Position = n is accepted", "pcSubStr": "the text to insert"}, returns="nothing; the text changes",
   see=["AddXT", "Append"], example=['o1.InsertBefore(1, ">")', '? o1.Content()']),
 E("IsSortedInAscending", "TRUE if the characters are in ascending order.",
   returns="TRUE or FALSE", see=["IsSortedInDescending", "SortingOrder"], example=['? o1.IsSortedInAscending()', 'o1 = new stzString("abc")', '? o1.IsSortedInAscending()']),
 E("RemoveAt", "Removes the substring that sits at position n, in place.",
   params={"n": "the position, or a list of positions", "pcSub": "the text expected at that position"}, returns="nothing; the text changes",
   note=["both arguments are needed: RemoveAt(n) with one argument raises an error"], see=["Remove", "RemoveSection"], example=['o1.RemoveAt(2, "an")', '? o1.Content()']),
 E("RemoveSection", "Removes the characters from position n1 to position n2, in place.",
   params={"_n1_": "the first position of the section", "_n2_": "the last position of the section"}, returns="nothing; the text changes. RemoveSectionQ returns the object for chaining",
   see=["Section", "RemoveSections"], example=['o1.RemoveSection(2, 4)', '? o1.Content()']),
 E("ReplaceSectionsByMany", "Replaces several sections by as many new texts, in place.",
   params={"_aSections_": "the sections to replace, ascending and not overlapping, each [ start, end ]", "paReplacements": "the new texts, one per section"}, returns="nothing; the text changes",
   warning=["unsorted or overlapping sections raise an error"], see=["ReplaceSection"], example=['o1.ReplaceSectionsByMany([ [ 1, 1 ], [ 4, 4 ] ], [ "B", "A" ])', '? o1.Content()']),
 E("Positions", "Returns the positions of every occurrence of the substring, as Find does.",
   params={"pcSub": "the text to look for; :Of = text is accepted"}, returns="a list of numbers", see=["Find"], example=['? @@( o1.Positions("an") )']),
 E("ContainsThese", "TRUE if the text contains every one of the given substrings.",
   params={"pacSubStrings": "the texts to look for"}, returns="TRUE or FALSE", see=["Contains", "ContainsOneOfThese"],
   example=['? o1.ContainsThese([ "ba", "na" ])', '? o1.ContainsThese([ "ba", "z" ])']),
 E("Language", "Returns the language the text is written in, as a symbol.",
   returns="a symbol such as english or french; unknown when it cannot tell", see=["Script", "NamedEntities"],
   example=['o1 = new stzString("The quick brown fox jumps over the lazy dog and the cat")', '? o1.Language()']),
 E("ContainsOneOfThese", "TRUE if the text contains at least one of the given substrings.",
   params={"paSubStr": "the texts to look for"}, returns="TRUE or FALSE", see=["Contains", "ContainsThese"],
   example=['? o1.ContainsOneOfThese([ "zz", "na" ])', '? o1.ContainsOneOfThese([ "zz", "yy" ])']),
 E("IsStrictlyEqualTo", "TRUE if the given value is a string with exactly the same text.",
   params={"pOther": "the value to compare with"}, returns="TRUE or FALSE; FALSE when the value is not a string", see=["IsEqualTo"],
   example=['? o1.IsStrictlyEqualTo("banana")', '? o1.IsStrictlyEqualTo(12)']),
 E("Marquers", "Returns the #N markers found in the text.",
   returns="a list of strings such as \"#1\"", example=['o1 = new stzString("x #1 y #2")', '? @@( o1.Marquers() )']),
 E("SortingOrder", "Returns the order the characters are in: :Ascending, :Descending or unsorted.",
   returns="a symbol, which prints in lowercase", see=["IsSortedInAscending", "IsSortedInDescending"], example=['? o1.SortingOrder()', 'o1 = new stzString("abc")', '? o1.SortingOrder()']),
 E("@", "Sets the substring that the narrative methods such as @RemoveItQ act on, and returns the object.",
   params={"pcSub": "the substring to act on"}, returns="the object itself", see=["AndQ"],
   example=['o1 = new stzString("soft__ware")', '? o1.@("__").@RemoveItQ().AndThenQ().UppercaseQ().TheString()']),
 E("FindNthPrevious", "Returns the position of the nth occurrence of the substring, counting backward from a position.",
   params={"n": "which occurrence, counting from 1", "pcSub": "the text to look for", "_nFrom_": "the position to look before; :StartingAt = n is accepted"}, returns="a number; 0 when there are fewer than n",
   see=["FindPrevious", "FindNth"], example=['? o1.FindNthPrevious(1, "an", 5)', '? o1.FindNthPrevious(2, "an", 5)']),
 E("FindSubStringBoundedBy", "Returns the positions of a text that is the whole content of a bounded piece.",
   params={"pcWhat": "the text to look for", "pacBounds": "the two bounds, [ open, close ]"}, returns="a list of numbers",
   note=["an occurrence inside a longer bounded piece does not count"], see=["BoundedBy", "FindAnyBoundedBy"], example=[RU, '? @@( o1.FindSubStringBoundedBy("a", [ "<<", ">>" ]) )']),
 E("FindAsSection", "Returns the [ start, end ] section of the first occurrence of the substring.",
   params={"pcSubStr": "the text to look for"}, returns="a pair of numbers", see=["FindAsSections", "FindFirst"], example=['? @@( o1.FindAsSection("an") )']),
 E("NumberOfDuplicates", "Returns how many different substrings occur more than once.",
   returns="a number", note=["it counts the distinct duplicated substrings, as Duplicates lists them"], see=["Duplicates", "ContainsDuplicates"], example=['? o1.NumberOfDuplicates()']),
 E("IsSortedInDescending", "TRUE if the characters are in descending order.",
   returns="TRUE or FALSE", see=["IsSortedInAscending", "SortingOrder"], example=['? o1.IsSortedInDescending()', 'o1 = new stzString("cba")', '? o1.IsSortedInDescending()']),
 E("SizeInBytes", "Returns the size of the text in bytes, in UTF-8.",
   returns="a number", see=["NumberOfChars"], example=['o1 = new stzString("héllo")', '? o1.SizeInBytes()', '? o1.NumberOfChars()']),
 E("ContainsDuplicates", "TRUE if some substring occurs more than once.",
   returns="TRUE or FALSE", see=["Duplicates", "NumberOfDuplicates"], example=['? o1.ContainsDuplicates()', 'o1 = new stzString("abc")', '? o1.ContainsDuplicates()']),
 E("SortedInDescending", "Returns a copy of the text with its characters sorted in descending order; the text is unchanged.",
   returns="a string", see=["SortInDescending", "SortedInAscending"], example=['? o1.SortedInDescending()']),
 E("NFirstOccurrences", "Returns the positions of the first n occurrences of the substring.",
   params={"n": "how many occurrences", "pNamedOf": "the substring, as :Of = text"}, returns="a list of numbers", see=["Find"], example=['? @@( o1.NFirstOccurrences(1, :Of = "an") )']),
 E("CommonItems", "Returns the characters this text has in common with another text, each once, in this text's order.",
   params={"pNamed": "the other text, as :With = text"}, returns="a list of one-character strings", example=['? @@( o1.CommonItems(:With = "band") )']),
 E("PartsAndPartitionersUsingXT", "Returns each part of the text with the value of the expression that made it a part.",
   params={"pcExpr": "the expression, as text, where @char stands for the current character"}, returns="a list of [ part, value ] pairs", see=["PartsUsing"],
   example=['o1 = new stzString("ab12cd")', '? @@( o1.PartsAndPartitionersUsingXT("@char = \'1\' or @char = \'2\'") )']),
 E("IsMadeOf", "TRUE if the whole text can be cut into the given substrings.",
   params={"acSubStr": "the substrings the text should be made of"}, returns="TRUE or FALSE", see=["Contains"],
   example=['? o1.IsMadeOf([ "ba", "na" ])', '? o1.IsMadeOf([ "ba" ])']),
 E("Lowercase", "Puts the text in lowercase, in place.",
   returns="nothing; the text changes. LowercaseQ returns the object for chaining", see=["Lowercased", "Uppercase"],
   example=['o1 = new stzString("Banana Split")', 'o1.Lowercase()', '? o1.Content()']),
 E("FindSubStringsBoundedBy", "Returns the position where each bounded piece starts, the bounds left out.",
   params={"pacBounds": "the two bounds, [ open, close ], or one text used for both"}, returns="a list of numbers", see=["FindAnyBoundedBy", "BoundedBy"],
   example=[RU, '? @@( o1.FindSubStringsBoundedBy([ "<<", ">>" ]) )']),
 E("IsNotLetter", "TRUE if the text is not a single letter.",
   returns="TRUE or FALSE", see=["IsLetter"], example=['? o1.IsNotLetter()', 'o1 = new stzString("a")', '? o1.IsNotLetter()']),
 E("PartsUsing", "Returns the parts of the text, cutting wherever the value of the expression changes from one character to the next.",
   params={"pcExpr": "the expression, as text, where @char stands for the current character"}, returns="a list of strings", see=["PartsAndPartitionersUsingXT", "Split"],
   example=['o1 = new stzString("ab12cd")', '? @@( o1.PartsUsing("@char = \'1\' or @char = \'2\'") )']),
 E("RepresentsHexNumber", "TRUE if the text is a hexadecimal number literal.",
   returns="TRUE or FALSE", example=['o1 = new stzString("0xFF")', '? o1.RepresentsHexNumber()', 'o1 = new stzString("FF")', '? o1.RepresentsHexNumber()']),
 E("FindNthOccurrence", "Returns the position of the nth occurrence of the substring, as FindNth does.",
   params={"n": "which occurrence, counting from 1", "pcSub": "the text to look for; :Of = text is accepted"}, returns="a number; -1 when there are fewer than n", see=["FindNth"],
   example=['? o1.FindNthOccurrence(2, "an")']),
 E("LeadingCharsAsString", "Returns the run of the same character at the start of the text, or an empty string when the first character is not repeated.",
   returns="a string", see=["Bounds"], example=['o1 = new stzString("----Ring")', '? o1.LeadingCharsAsString()']),
 E("RemoveSections", "Removes the characters of each given [ start, end ] section, in place.",
   params={"_aSections_": "the sections to remove, each [ start, end ]; overlapping ones are merged first"}, returns="nothing; the text changes", see=["RemoveSection"],
   example=['o1.RemoveSections([ [ 1, 2 ], [ 5, 6 ] ])', '? o1.Content()']),
 E("SortInDescending", "Sorts the characters of the text in descending order, in place.",
   returns="nothing; the text changes. SortInDescendingQ returns the object for chaining", see=["SortedInDescending"], example=['o1.SortInDescending()', '? o1.Content()']),
 E("Trimmed", "Returns a copy of the text without the whitespace at both ends; the text is unchanged.",
   returns="a string", see=["Trim"], example=['o1 = new stzString("  hi  ")', '? "[" + o1.Trimmed() + "]"']),
 E("IsListInString", "TRUE if the text is a list literal, such as [ 1, 2 ].",
   returns="TRUE or FALSE", see=["ToList"], example=['o1 = new stzString("[1,2]")', '? o1.IsListInString()', 'o1 = new stzString("12")', '? o1.IsListInString()']),
 E("NumberOfBytes", "Returns the size of the text in bytes, in UTF-8, as SizeInBytes does.",
   returns="a number", see=["SizeInBytes", "NumberOfChars"], example=['? o1.NumberOfBytes()']),
 E("ExistsInList", "TRUE if the text is one of the items of the given list.",
   params={"paList": "the list of strings to look in"}, returns="TRUE or FALSE", see=["Contains"],
   example=['? o1.ExistsInList([ "apple", "banana" ])', '? o1.ExistsInList([ "apple" ])']),
 E("SplitAfter", "Returns the parts of the text, each ending with an occurrence of the substring.",
   params={"pcSubStr": "the text that closes each part"}, returns="a list of strings", see=["SplitBefore", "SplitAt"], example=['? @@( o1.SplitAfter("an") )']),
 E("SplitAtSections", "Returns the parts of the text left once the given sections are cut out.",
   params={"_aSections_": "the sections to cut at, each [ start, end ]"}, returns="a list of strings", see=["SplitAt", "SplitBeforePositions"], example=['? @@( o1.SplitAtSections([ [ 2, 3 ] ]) )']),
 E("SplitBefore", "Returns the parts of the text, each starting with an occurrence of the substring.",
   params={"pcSubStr": "the text that opens each part"}, returns="a list of strings", see=["SplitAfter", "SplitAt"], example=['? @@( o1.SplitBefore("an") )']),
 E("HowMany", "Returns how many times the substring occurs in the text.",
   params={"pcSub": "the text to count"}, returns="a number", see=["Count"], example=['? o1.HowMany("an")']),
 E("CharCase", "Returns the case of a one-character text: :Lowercase, :Uppercase or :Mixed.",
   returns="a symbol, which prints in lowercase; mixed for a text of more than one character", example=['o1 = new stzString("a")', '? o1.CharCase()', 'o1 = new stzString("A")', '? o1.CharCase()']),
]}
