R = 'o1 = new stzNumber(12)'

DOC = {
"class": "stzNumber",
"receiver": R,
"class_block": {
    "brief": "Holds one number, exact or rounded, and answers questions about it and its written form.",
    "detail": "A stzNumber keeps the number as text, with its own round (the decimals it prints), so what you put in is what it holds. Reach for it when the value matters as a number AND as written: signs, digits, bases, exactness. For plain arithmetic on many numbers use stzListOfNumbers.",
    "receiver": R,
    "example": ['? o1.IsDividableBy(4)', '#--> TRUE'],
    "see": ["stzListOfNumbers", "stzString", "stzDecimalToBinary"],
},
"entries": [
 {"name": "Content",
  "brief": "Returns the number as it is held: a string, exactly as given.",
  "returns": "a string; use NumericValue for a Ring number",
  "see": ["NumericValue", "StringValue"],
  "example": ['? @@( o1.Content() )', 'o1 = new stzNumber("007.50")', '? @@( o1.Content() )']},
 {"name": "WhyNotExact",
  "brief": "Returns a plain sentence saying what was lost and where, or an empty string when the value is exact.",
  "returns": "a string; empty when IsExact is TRUE",
  "see": ["IsExact"],
  "example": ['? @@( o1.WhyNotExact() )', 'o1 = new stzNumber(1)', 'o1.DivideBy(3)', '? o1.IsExact()', '? @@( o1.WhyNotExact() )']},
 {"name": "StringValue",
  "brief": "Returns the number as a string, rounded to the number's own round (2 decimals by default).",
  "returns": "a string",
  "warning": ["the call also replaces the held content by the rounded text: after it, Content returns 3.14, not 3.14159"],
  "see": ["Content", "NumericValue", "Round"],
  "example": ['o1 = new stzNumber(3.14159)', '? o1.StringValue()', '? o1.Content()']},
 {"name": "NumericValue",
  "brief": "Returns the number as a Ring number, an approximation when the content is a fraction.",
  "returns": "a number",
  "note": ["a fraction such as 1/3 is divided out, so the result is an approximation of an exact value"],
  "see": ["Content", "StringValue"],
  "example": ['? o1.NumericValue() + 1']},
 {"name": "Contains",
  "brief": "TRUE if the written form of the number contains the given digit or run of digits.",
  "params": {"pcDigit": "a digit, or a run of digits, given as text"},
  "returns": "TRUE or FALSE",
  "note": ["give the digit as text: Contains(2) with a number answers FALSE even for 12"],
  "example": ['? o1.Contains("2")', '? o1.Contains("5")']},
 {"name": "Copy",
  "brief": "Returns a new stzNumber with the same content, so the copy can change without touching this one.",
  "returns": "a new stzNumber",
  "example": ['o2 = o1.Copy()', 'o2.Add(1)', '? o1.Content()', '? o2.Content()']},
 {"name": "IsEqualTo",
  "brief": "TRUE if the number is equal to the given one, compared at this number's round.",
  "params": {"pOtherNumber": "a number, or a number written as text"},
  "returns": "TRUE or FALSE; FALSE when the argument is not a number",
  "see": ["IsEqual", "IsBetween"],
  "example": ['? o1.IsEqualTo(12)', '? o1.IsEqualTo("12.0")', '? o1.IsEqualTo("abc")']},
 {"name": "Add",
  "brief": "Adds the given number to this one, in place.",
  "params": {"pOtherNumber": "the number to add, or a number written as text"},
  "returns": "nothing; the number changes. AddQ does the same and returns the object for chaining",
  "see": ["MultiplyBy", "Increment"],
  "example": ['o1.Add(8)', '? o1.Content()']},
 {"name": "MultiplyBy",
  "brief": "Multiplies this number by the given one, in place.",
  "params": {"pOtherNumber": "the factor, or a list of factors (then MultiplyByMany does the work)"},
  "returns": "nothing; the number changes",
  "see": ["Add", "Inverse"],
  "example": ['o1.MultiplyBy(3)', '? o1.Content()']},
 {"name": "stzType",
  "brief": "Returns the Softanza type symbol of the object, always :stzNumber.",
  "returns": "the symbol :stzNumber, which prints as stznumber",
  "example": ['? o1.stzType()']},
 {"name": "Unicode",
  "brief": "Returns the number read as a Unicode codepoint, and raises when it is not one.",
  "returns": "the number itself, when it is a whole number from 0 to 1114111",
  "warning": ["a fraction or a number outside the Unicode range raises an error"],
  "see": ["Unicodes"],
  "example": ['o1 = new stzNumber(65)', '? o1.Unicode()']},
 {"name": "IsBetween",
  "brief": "TRUE if the number lies strictly between the two given numbers, bounds excluded.",
  "params": {"pNumber1": "the lower bound, a number or a number written as text", "pNumber2": "the upper bound, in the same forms"},
  "returns": "TRUE or FALSE",
  "note": ["the bounds themselves do not count: IsBetweenIB includes them"],
  "see": ["IsBoundedBy", "IsEqualTo"],
  "example": ['? o1.IsBetween(10, 20)', '? o1.IsBetween(12, 20)', '? o1.IsBetweenIB(12, 20)']},
 {"name": "ToBinaryForm",
  "brief": "Returns the number written in base 2, with the 0b prefix.",
  "returns": "a string such as 0b1100",
  "see": ["ToHex", "ToOctalForm"],
  "example": ['? o1.ToBinaryForm()']},
 {"name": "IsLetter",
  "brief": "Always FALSE: a number is not a letter, answered so a number can stand where a character is expected.",
  "returns": "FALSE",
  "example": ['? o1.IsLetter()']},
 {"name": "RemoveSpaces",
  "brief": "Removes the spaces inside the written form of the number, in place.",
  "returns": "nothing; the number changes",
  "note": ["a number accepted by stzNumber holds no space, so on one built the usual way the call changes nothing"],
  "example": ['o1.RemoveSpaces()', '? o1.Content()']},
 {"name": "Unicodes",
  "brief": "Returns the codepoints of the number's written form, one per digit.",
  "returns": "a list of numbers: 65 gives the codepoints of the characters 6 and 5",
  "note": ["a different question from Unicode, which reads the number itself as a codepoint"],
  "see": ["Unicode"],
  "example": ['o1 = new stzNumber(65)', '? @@( o1.Unicodes() )']},
 {"name": "ToHex",
  "brief": "Returns the number written in base 16, with the 0x prefix.",
  "returns": "a string such as 0xFF",
  "see": ["ToBinaryForm", "ToOctalForm"],
  "example": ['o1 = new stzNumber(255)', '? o1.ToHex()']},
 {"name": "IsBoundedBy",
  "brief": "TRUE if the number lies between the two given numbers, bounds included.",
  "params": {"_n1_": "the lower bound, a number or a number written as text", "_n2_": "the upper bound, in the same forms"},
  "returns": "TRUE or FALSE",
  "see": ["IsBetween"],
  "example": ['? o1.IsBoundedBy(12, 20)', '? o1.IsBoundedBy(13, 20)']},
 {"name": "IsPositive",
  "brief": "TRUE if the number carries no sign or a plus sign.",
  "returns": "TRUE or FALSE",
  "note": ["zero counts as positive"],
  "see": ["Sign"],
  "example": ['? o1.IsPositive()', 'o1 = new stzNumber(-12)', '? o1.IsPositive()', 'o1 = new stzNumber(0)', '? o1.IsPositive()']},
 {"name": "IsANumber",
  "brief": "Always TRUE: the object holds a number, answered so a number can be told from a text.",
  "returns": "TRUE",
  "example": ['? o1.IsANumber()']},
 {"name": "Round",
  "brief": "Returns the round of the number: how many decimals it prints.",
  "returns": "a number",
  "see": ["StringValue"],
  "example": ['? o1.Round()']},
 {"name": "Increment",
  "brief": "Adds 1 to the number, in place.",
  "returns": "nothing; the number changes. IncrementQ returns the object for chaining",
  "see": ["Add"],
  "example": ['o1.Increment()', '? o1.Content()']},
 {"name": "Sign",
  "brief": "Returns the sign written in front of the number, or an empty string when there is none.",
  "returns": "\"+\", \"-\" or an empty string",
  "note": ["the sign is read from the written form: 12 has no sign, +12 has one"],
  "see": ["IsPositive"],
  "example": ['? @@( o1.Sign() )', 'o1 = new stzNumber("+12")', '? @@( o1.Sign() )', 'o1 = new stzNumber(-12)', '? @@( o1.Sign() )']},
 {"name": "IsEqual",
  "brief": "TRUE if the number is equal to the given one, which may be given as :To = n.",
  "params": {"pOtherNumber": "a number, a number written as text, or the named form :To = n"},
  "returns": "TRUE or FALSE",
  "see": ["IsEqualTo"],
  "example": ['? o1.IsEqual(12)', '? o1.IsEqual(:To = 13)']},
 {"name": "IsADigit",
  "brief": "TRUE if the number is a single digit, from 0 to 9.",
  "returns": "TRUE or FALSE",
  "example": ['? o1.IsADigit()', 'o1 = new stzNumber(7)', '? o1.IsADigit()']},
 {"name": "IsDividableBy",
  "brief": "TRUE if the number divides evenly by n.",
  "params": {"n": "the divisor, a number or a number written as text"},
  "returns": "TRUE or FALSE",
  "example": ['? o1.IsDividableBy(4)', '? o1.IsDividableBy(5)']},
 {"name": "ToOctalForm",
  "brief": "Returns the number written in base 8, with its prefix.",
  "returns": "a string",
  "see": ["ToBinaryForm", "ToHex"],
  "example": ['o1 = new stzNumber(8)', '? o1.ToOctalForm()']},
 {"name": "Inverse",
  "brief": "Returns the inverse of the number, 1 divided by the number, and leaves the number unchanged.",
  "drop_body": ["The multiplicative inverse (1/n) of the number (mutating)"],
  "returns": "a number",
  "see": ["MultiplyBy"],
  "example": ['o1 = new stzNumber(4)', '? o1.Inverse()', '? o1.Content()']},
 {"name": "IsExact",
  "brief": "TRUE unless an operation on the number lost precision, such as a division that does not terminate.",
  "returns": "TRUE or FALSE",
  "see": ["WhyNotExact"],
  "example": ['? o1.IsExact()', 'o1 = new stzNumber(1)', 'o1.DivideBy(3)', '? o1.IsExact()']},
 {"name": "IsItemOf",
  "brief": "TRUE if the number occurs in the given list.",
  "params": {"paList": "the list to look in"},
  "returns": "TRUE or FALSE",
  "example": ['? o1.IsItemOf([ 3, 12, 40 ])', '? o1.IsItemOf([ 3, 40 ])']},
]}
