load "../stzbase.ring"

/*

Main thematic sections of this test file:

- Basic folder creation and information retrieval
- Navigation operations 
- File and folder operations (listing, counting, checking existence)
- Folder creation and removal (single, multiple, recursive)
- Search and filtering (patterns, extensions)
- Information display 
- Utility methods (Copy, Clone, Refresh, chaining)
- Advanced scenarios (different drives, special folders, error handling)
- Complete workflow example

#AI: Generated by ClaudeAI

*/

#================================#
#  BASIC FOLDER CREATION & INFO  #
#================================#

/*--- Basic Folder Creation and Information

pr()

o1 = new stzFolder("C:\MyTestFolder")
o1 {

    ? @@NL( Info() )
    #-->
	' [
		[ "name", "MyTestFolder" ],
		[ "path", "C:/MyTestFolder" ],
		[ "absolutepath", "C:/MyTestFolder" ],
		[ "count", 0 ],
		[ "files", 0 ],
		[ "folders", 0 ],
		[ "isempty", 1 ],
		[ "isreadable", 1 ],
		[ "isroot", 0 ],
		[ "exists", 1 ]
	]'
    

	? Name()
    #--> MyTestFolder
    
    ? IsEmpty()
    #--> TRUE
    
    ? Count() # Or Size()
    #--> 0
}

pf()
# Executed in 0.01 second(s) in Ring 1.22

/*--- Getting Folder Names and Paths

pr()

o1 = new stzFolder("C:\MyTestFolder\Documents\Projects")
o1 {

    ? Name()
    #--> Projects
    
    ? Path()
    #--> C:\Users\John\Documents\Projects
    
    ? FullPath() # Or AbsolutePath()
    #--> C:\Users\John\Documents\Projects
    
    ? IsAbsolute()
    #--> TRUE
    
    ? IsRoot()
    #--> FALSE
}

pf()
# Executed in almost 0 second(s) in Ring 1.22

/*--- Folder Status Checks

pr()

o1 = new stzFolder("C:\Windows")
o1 {
    ? IsReadable()
    #--> TRUE
    
    ? Exists("System32")
    #--> TRUE
    
    ? HasFiles() # Or ContainsFiles()
    #--> TRUE
    
    ? HasFolders() # Or HasDirs()
    #--> TRUE

pf()
# Executed in almost 0 second(s) in Ring 1.22

#=====================#
#  FOLDER NAVIGATION  #
#=====================#

/*--- Basic Navigation

pr()

o1 = new stzFolder("C:\Users")
o1 {
    # Current path
	? Path()
    #--> C:\Users
    
    GoTo("Public") # Or MoveTo() or cd()
	? Path()
    #--> C:\Users\Public
    
    Up() # Or GoUp() or cdUp()
    ? Path()
    #--> C:\Users
    
    GoHome()
    ? Path()
    #--> C:\Users\[Username]
}

pf()
# Executed in almost 0 second(s) in Ring 1.22

#==================================#
#  FILE & FOLDER OPERATIONS       #
#==================================#

/*--- Listing Files and Folders

pr()

o1 = new stzFolder("C:\Windows\System32")
o1 {

	? CountFiles()

    aFiles = Files()
	? First3(aFiles)
    #--> calc.exe
    #    notepad.exe
    #    cmd.exe
    
	CountFolders()

    aFolders = Folders() # Or Dirs() or SubFolders()
	? First3(aFolders)
    #--> drivers
    #    config
    #    Tasks
}

pf()
# Executed in 0.07 second(s) in Ring 1.22

/*--- Counting Contents

pr()

o1 = new stzFolder("C:\Program Files")
o1 {

	# Counting files and forlders at the current level

    ? Count() # Or CountFilesAndFolders()
    #--> 42
    
    ? CountFiles()
    #--> 1
    
    ? CountFolders() + NL # Or CountDirs()
    #--> 41

	# Counting files and folders indepth/recursively

	? CountXT() # or DeepCount()
	#--> 16309

	? CountFilesXT() # or DeepCountFiles()
	#--> 14392

	? CountFoldersXT() # Or DeepCountFolders()
	#--> 1917

}

pf()
# Executed in 0.74 second(s) in Ring 1.22

/*--- Checking for Specific Content

pr()

o1 = new stzFolder("C:\Windows")
o1 {
    ? Contains("System32") # Or Has()
    #--> TRUE
    
    ? ContainsFile("explorer.exe")
    #--> TRUE
    
    ? ContainsFolder("System32") + NL # Or ContainsDir()
    #--> TRUE

	? DeepContains("Boot") # Takes most of the execution time!
	#--> TRUE
}

pf()
# Executed in 8.45 second(s) in Ring 1.22

#=============================#
#  FOLDER CREATION & REMOVAL  #
#=============================#

/*--- Creating Single Folders

pr()

o1 = new stzFolder("C:\TestArea")
o1 {
    oNewFolder = CreateFolder("TestSubFolder") # Or mkdir() or MakeFolder()
    ? oNewFolder.Name()
    #--> TestSubFolder
}

pf()
# Executed in almost 0 second(s) in Ring 1.22

/*--- Creating Multiple Folders

pr()

o1 = new stzFolder("C:\TestArea")
o1 {

    aCreated = CreateFolders([ "Docs", "Images", "Videos", "Music" ])
    
    for oFolder in aCreated
        ? oFolder.Name()
    next
    #--> Docs
    #    Images
    #    Videos
    #    Music
}

pf()
# Executed in almost 0 second(s) in Ring 1.22

/*--- Creating Folder Paths

pr()

o1 = new stzFolder("C:\")
o1 {
    # Creating deep path...
    oDeepFolder = CreatePath("TestArea\Level1\Level2\Level3") # Or mkpath()
    ? oDeepFolder.Name()
    #--> Level3
}

pf()
# Executed in 0.01 second(s) in Ring 1.22

/*--- Removing Files and Folders

pr()

o1 = new stzFolder("C:\TestArea")
o1 {
    # Create test content first
    CreateFolder("ToDelete")
	? CountFolders()
    #--> 6
    
    RemoveFolder("ToDelete") # Or rmdir() or DeleteFolder()
    ? CountFolders()
    #--> 5
    
    # Test file removal

	? FileExists("test.txt") #--> FALSE

	# RemoveFile("test.txt") # Or DeleteFile()
    #--> ERROR: File 'test.txt' doesn't exist here.

	CreateFile("test.txt")
	? FileExists("test.txt") #--> TRUE
	
}

pf()
# Executed in 0.01 second(s) in Ring 1.22

/*--- Recursive Removal

pr()

o1 = new stzFolder("C:\TestArea\Level1")
o1 {
    # Current path before removal
	? Path()
    #--> C:\TestArea\Level1
    
    # Removing all the folder and its subfolders (recursively)

    bSuccess = DeepRemoveAll() # Or DeleteRecursively()
    ? bSuccess
    #--> Removal successful: TRUE
}

pf()
# Executed in almost 0 second(s) in Ring 1.22

#======================#
#  SEARCH & FILTERING  #
#======================#

/*--- Basic Search Operations

pr()

o1 = new stzFolder("C:\Windows\System32")
o1 {
    # Finding all .exe files

    acExeFiles = FindFiles("*.exe")
    ? CountFiles() #--> 4696

    ? @FirstN(5, acExeFiles)
    #--> calc.exe
    #    notepad.exe
    #    cmd.exe
    #    ping.exe
    #    ipconfig.exe
}

pf()
# Executed in 0.17 second(s) in Ring 1.23
# Executed in 0.19 second(s) in Ring 1.22

/*--- Specialized Search Methods
*/
pr()

o1 = new stzFolder("C:\Windows\System32")
o1 {
    # Finding .dll files
    aDlls = FindFiles("*.dll")
    ? len(aDlls)
    #--> 3611
    
    # Finding folders starting with 'config'
    aConfigFolders = FindFolders("config*")
    ? len(aConfigFolders)
    #--> Config folders: 2
    
    ? @@(aConfigFolders)
    #--> [ "config", "Configuration" ]
}

pf()
# Executed in 0.17 second(s) in Ring 1.23
# Executed in 0.18 second(s) in Ring 1.22

/*--- Files by Extension

pr()

o1 = new stzFolder("C:\Windows\System32")
o1 {
    ? "Getting .exe files..."
    aExeFiles = FilesByExtension(".exe")
    ? "EXE files count: " + len(aExeFiles)
    #--> EXE files count: 247
    
    ? "Getting .dll files (without dot)..."
    aDllFiles = FilesByExtension("dll")  # Extension with or without dot works
    ? "DLL files count: " + len(aDllFiles)
    #--> DLL files count: 1847
}

pf()

#==================================#
#  INFORMATION & DISPLAY         #
#==================================#

/*--- Detailed Information

pr()

o1 = new stzFolder("C:\Windows")
o1 {
    ? "Getting detailed info..."
    aInfo = Info()
    
    ? "Name: " + aInfo[:Name]
    ? "Path: " + aInfo[:Path]
    ? "Absolute Path: " + aInfo[:AbsolutePath]
    ? "Total Count: " + aInfo[:Count]
    ? "Is Empty: " + aInfo[:IsEmpty]
    ? "Is Readable: " + aInfo[:IsReadable]
    ? "Is Root: " + aInfo[:IsRoot]
    #--> Name: Windows
    #    Path: C:\Windows
    #    Absolute Path: C:\Windows
    #    Total Count: 156
    #    Is Empty: FALSE
    #    Is Readable: TRUE
    #    Is Root: FALSE
}

pf()

/*--- Tree Display

pr()

o1 = new stzFolder("C:\TestArea")
o1 {
    ? "Tree view (level 2):"
    Show(2)
    #--> 📁 TestArea
    #      📁 Docs
    #      📁 Images
    #        📁 Thumbnails
    #      📁 Videos
    #      📁 Music
    #        📁 Rock
    #        📁 Jazz
}

pf()

#==================================#
#  UTILITY METHODS              #
#==================================#

/*--- Copy and Clone

pr()

o1 = new stzFolder("C:\Windows\System32")
o2 = o1.Copy() # Or Clone()

? "Original path: " + o1.Path()
#--> Original path: C:\Windows\System32

? "Copy path: " + o2.Path()
#--> Copy path: C:\Windows\System32

? "Are they the same object: " + (o1 = o2)
#--> Are they the same object: FALSE

pf()

/*--- Refresh Operation

pr()

o1 = new stzFolder("C:\TestArea")
o1 {
    ? "Count before refresh: " + Count()
    #--> Count before refresh: 4
    
    # Simulate external changes to folder
    CreateFolder("NewlyAdded")
    
    Refresh()
    ? "Count after refresh: " + Count()
    #--> Count after refresh: 5
}

pf()

/*--- Method Chaining

pr()

o1 = new stzFolder("C:\")
o1 {
    GoTo("Windows").GoTo("System32").Up().GoTo("Temp")
    ? "Final path after chaining: " + Path()
    #--> Final path after chaining: C:\Windows\Temp
    
    # Chain with creation
    CreateFolder("ChainTest").GoTo("ChainTest").CreateFolder("SubTest")
    ? "Path after create chain: " + Path()
    #--> Path after create chain: C:\Windows\Temp\ChainTest
}

pf()

#==================================#
#  COMPREHENSIVE WORKFLOW        #
#==================================#

/*--- Complete Folder Management Workflow

pr()

? "=== COMPREHENSIVE FOLDER WORKFLOW ==="

# 1. Create main project folder
oProject = new stzFolder("C:\MyProject")
oProject {
    Info()
    
    # 2. Create project structure
    ? ""
    ? "Creating project structure..."
    aFolders = ["src", "docs", "tests", "build", "assets"]
    CreateFolders(aFolders)
    
    ? "Project structure created. Contents:"
    for folder in Folders()
        ? "  " + folder
    next
    
    # 3. Navigate and create sub-structure
    ? ""
    ? "Creating sub-structures..."
    GoTo("src")
    CreateFolders(["models", "views", "controllers"])
    
    Up()
    GoTo("assets")
    CreateFolders(["images", "css", "js"])
    
    # 4. Go back to root and show final structure
    Up()
    ? ""
    ? "Final project tree:"
    Show(2)
    
    # 5. Get comprehensive info
    ? ""
    ? "Project statistics:"
    aInfo = Info()
    ? "Total items: " + aInfo[:Count]
    ? "Folders: " + CountFolders()
    ? "Files: " + CountFiles()
    
    # 6. Search for specific patterns
    ? ""
    ? "Searching for all folders containing 'view':"
    aViewFolders = FindFolders("*view*")
    for folder in aViewFolders
        ? "  " + folder
    next
    
    # 7. Cleanup (commented out for safety)
    # ? ""
    # ? "Cleaning up project..."
    # bRemoved = RemoveRecursively()
    # ? "Cleanup successful: " + bRemoved
}

pf()

? "=== ALL TESTS COMPLETED ==="
