
load "../stzbase.ring"

/*

Main thematic sections of this test file:

- Basic folder creation and information retrieval
- Navigation operations 
- File and folder operations (listing, counting, checking existence)
- Folder creation and removal (single, multiple, recursive)
- Search and filtering (patterns, extensions)
- Information display 
- Utility methods (Copy, Clone, Refresh, chaining)
- Advanced scenarios (different drives, special folders, error handling)
- Complete workflow example

#AI: Generated by ClaudeAI

*/

#================================#
#  BASIC FOLDER CREATION & INFO  #
#================================#

/*--- Basic Folder Creation and Information

pr()

o1 = new stzFolder("C:\MyTestFolder")
o1 {

    ? @@NL( Info() )
    #-->
	' [
		[ "name", "MyTestFolder" ],
		[ "path", "C:/MyTestFolder" ],
		[ "absolutepath", "C:/MyTestFolder" ],
		[ "count", 0 ],
		[ "files", 0 ],
		[ "folders", 0 ],
		[ "isempty", 1 ],
		[ "isreadable", 1 ],
		[ "isroot", 0 ],
		[ "exists", 1 ]
	]'
    

	? Name()
    #--> MyTestFolder
    
    ? IsEmpty()
    #--> TRUE
    
    ? Count() # Or Size()
    #--> 0
}

pf()
# Executed in 0.01 second(s) in Ring 1.22

/*--- Getting Folder Names and Paths

pr()

o1 = new stzFolder("C:\MyTestFolder\Documents\Projects")
o1 {

    ? Name()
    #--> Projects
    
    ? Path()
    #--> C:\Users\John\Documents\Projects
    
    ? FullPath() # Or AbsolutePath()
    #--> C:\Users\John\Documents\Projects
    
    ? IsAbsolute()
    #--> TRUE
    
    ? IsRoot()
    #--> FALSE
}

pf()
# Executed in almost 0 second(s) in Ring 1.22

/*--- Folder Status Checks

pr()

o1 = new stzFolder("C:\Windows")
o1 {
    ? IsReadable()
    #--> TRUE
    
    ? Exists("System32")
    #--> TRUE
    
    ? HasFiles() # Or ContainsFiles()
    #--> TRUE
    
    ? HasFolders() # Or HasDirs()
    #--> TRUE

pf()
# Executed in almost 0 second(s) in Ring 1.22

#=====================#
#  FOLDER NAVIGATION  #
#=====================#

/*--- Basic Navigation

pr()

o1 = new stzFolder("C:\Users")
o1 {
    # Current path
	? Path()
    #--> C:\Users
    
    GoTo("Public") # Or MoveTo() or cd()
	? Path()
    #--> C:\Users\Public
    
    Up() # Or GoUp() or cdUp()
    ? Path()
    #--> C:\Users
    
    GoHome()
    ? Path()
    #--> C:\Users\[Username]
}

pf()
# Executed in almost 0 second(s) in Ring 1.22

#==================================#
#  FILE & FOLDER OPERATIONS       #
#==================================#

/*--- Listing Files and Folders

pr()

o1 = new stzFolder("C:\Windows\System32")
o1 {

	? CountFiles()

    aFiles = Files()
	? First3(aFiles)
    #--> calc.exe
    #    notepad.exe
    #    cmd.exe
    
	CountFolders()

    aFolders = Folders() # Or Dirs() or SubFolders()
	? First3(aFolders)
    #--> drivers
    #    config
    #    Tasks
}

pf()
# Executed in 0.07 second(s) in Ring 1.22

/*--- Counting Contents

pr()

o1 = new stzFolder("C:\Program Files")
o1 {

	# Counting files and forlders at the current level

    ? Count() # Or CountFilesAndFolders()
    #--> 42
    
    ? CountFiles()
    #--> 1
    
    ? CountFolders() + NL # Or CountDirs()
    #--> 41

	# Counting files and folders indepth/recursively

	? DeepCount()
	#--> 16309

	? DeepCountFiles()
	#--> 14392

	? DeepCountFolders()
	#--> 1917

}

pf()
# Executed in 0.74 second(s) in Ring 1.22

/*--- Checking for Specific Content

pr()

o1 = new stzFolder("C:\Windows")
o1 {
    ? Contains("System32") # Or Has()
    #--> TRUE
    
    ? ContainsFile("explorer.exe")
    #--> TRUE
    
    ? ContainsFolder("System32") + NL # Or ContainsDir()
    #--> TRUE

	? DeepContains("Boot") # Takes most of the execution time!
	#--> TRUE
}

pf()
# Executed in 8.45 second(s) in Ring 1.22

#=============================#
#  FOLDER CREATION & REMOVAL  #
#=============================#

/*--- Creating Single Folders

pr()

o1 = new stzFolder("C:\TestArea")
o1 {
    oNewFolder = CreateFolder("TestSubFolder") # Or mkdir() or MakeFolder()
    ? oNewFolder.Name()
    #--> TestSubFolder
}

pf()
# Executed in almost 0 second(s) in Ring 1.22

/*--- Creating Multiple Folders

pr()

o1 = new stzFolder("C:\TestArea")
o1 {

    aCreated = CreateFolders([ "Docs", "Images", "Videos", "Music" ])
    
    for oFolder in aCreated
        ? oFolder.Name()
    next
    #--> Docs
    #    Images
    #    Videos
    #    Music
}

pf()
# Executed in almost 0 second(s) in Ring 1.22

/*--- Creating Folder Paths

pr()

o1 = new stzFolder("C:\")
o1 {
    # Creating deep path...
    oDeepFolder = CreatePath("TestArea\Level1\Level2\Level3") # Or mkpath()
    ? oDeepFolder.Name()
    #--> Level3
}

pf()
# Executed in 0.01 second(s) in Ring 1.22

/*--- Removing Files and Folders

pr()

o1 = new stzFolder("C:\TestArea")
o1 {
    # Create test content first
    CreateFolder("ToDelete")
	? CountFolders()
    #--> 6
    
    RemoveFolder("ToDelete") # Or rmdir() or DeleteFolder()
    ? CountFolders()
    #--> 5
    
    # Test file removal

	? FileExists("test.txt") #--> FALSE

	# RemoveFile("test.txt") # Or DeleteFile()
    #--> ERROR: File 'test.txt' doesn't exist here.

	CreateFile("test.txt")
	? FileExists("test.txt") #--> TRUE
	
}

pf()
# Executed in 0.01 second(s) in Ring 1.22

/*--- Recursive Removal

pr()

o1 = new stzFolder("C:\TestArea\Level1")
o1 {
    # Current path before removal
	? Path()
    #--> C:\TestArea\Level1
    
    # Removing all the folder and its subfolders (recursively)

    bSuccess = DeepRemoveAll()
    ? bSuccess
    #--> Removal successful: TRUE
}

pf()
# Executed in almost 0 second(s) in Ring 1.22

#======================#
#  SEARCH & FILTERING  #
#======================#

/*--- Basic Search Operations

pr()

o1 = new stzFolder("C:\Windows\System32")
o1 {
    # Finding all .exe files

    acExeFiles = FindFiles("*.exe")
    ? CountFiles() #--> 4696

    ? @FirstN(5, acExeFiles)
    #--> calc.exe
    #    notepad.exe
    #    cmd.exe
    #    ping.exe
    #    ipconfig.exe
}

pf()
# Executed in 0.17 second(s) in Ring 1.23
# Executed in 0.19 second(s) in Ring 1.22

/*--- Specialized Search Methods

pr()

o1 = new stzFolder("C:\Windows\System32")
o1 {
    # Finding .dll files
    aDlls = FindFiles("*.dll")
    ? len(aDlls)
    #--> 3611
    
    # Finding folders starting with 'config'
    aConfigFolders = FindFolders("config*")
    ? len(aConfigFolders)
    #--> Config folders: 2
    
    ? @@(aConfigFolders)
    #--> [ "config", "Configuration" ]
}

pf()
# Executed in 0.17 second(s) in Ring 1.23
# Executed in 0.18 second(s) in Ring 1.22

/*--- Files by Extension

pr()

o1 = new stzFolder("C:\Windows\System32")
o1 {
    # Getting .exe files
    aExeFiles = FilesByExtension(".exe")
    ? len(aExeFiles)
    #--> 642
    
    # Getting .dll files (without dot)
    aDllFiles = FilesByExtension("dll")  # Extension with or without dot works
    ? len(aDllFiles)
    #--> 3382
}

pf()
# Executed in 0.04 second(s) in Ring 1.22

/*--- Specialized Search Methods

pr()

o1 = new stzFolder("C:\Windows\System32") #TODO Error
o1 {
    # Finding .dll files
    ? VizSearchFiles("*.dll")
    
    # Finding folders starting with 'config'
    ? FindFolders("config*")

}


pf()

/*---

pr()

o1 = new stzFolder("D:\GitHub\stzlib\libraries\stzlib\core\")
? o1.VizSearchFiles("*memory*")

pf()
# Executed in 0.01 second(s) in Ring 1.22

#==========================#
#  INFORMATION & DISPLAY   #
#==========================#

/*--- Detailed Information

pr()

o1 = new stzFolder("C:\Windows")
? @@NL(o1.Info())
#-->'
[
	[ "name", "Windows" ],
	[ "path", "C:/Windows" ],
	[ "absolutepath", "C:/Windows" ],
	[ "count", 118 ],
	[ "files", 32 ],
	[ "folders", 86 ],
	[ "isempty", 0 ],
	[ "isreadable", 1 ],
	[ "isroot", 0 ],
	[ "exists", 1 ]
]
'

pf()
# Executed in 0.01 second(s) in Ring 1.22

/*--- Short and long folders and files names
*/
pr()

o1 = new stzFolder("c:/testarea")
# This method returns the folder original path

? o1.Path()	# Or Home() or Root() or Folder()
#--> c:/testarea

# The name itself is just the name of the folder
# without any path noise

? o1.Name()
#--> testarea

# Now, Softanza enforces a convention when listing
# folders and files. Folders always start with "/"
# and end with "/"

? @@NL( o1.Folders() )
#-->
'
[
	"/docs/",
	"/images/",
	"/more/",
	"/music/",
	"/notes/",
	"/tempo/",
	"/videos/"
]
'
# And you can add the long paths with XT()

? @@NL( o1.FoldersXT() )
#-->
'
[
	"c:/testarea/docs/",
	"c:/testarea/images/",
	"c:/testarea/more/",
	"c:/testarea/music/",
	"c:/testarea/notes/",
	"c:/testarea/tempo/",
	"c:/testarea/videos/"
]
'

# While files start with "/" but does not end with an "/"
# Let's see it in the full lis tof files at any level
# of the folder tree (using Deep prefix)

? @@NL( o1.DeepFiles() )
#-->
'
[
	"/test.txt",
	"/Images/image1.png",
	"/Images/image2.png",
	"/tempo/temp1.txt",
	"/tempo/temp2.txt",
	"/Images/notes/howto.txt",
	"/Images/notes/sources.txt"
]
'

# This convention make folders distinsguishable from folders

# Similarilty you can list the files with their long paths+names

? @@NL( o1.DeepFilesXT() )
#-->
'
[
	"c:/testarea/test.txt",
	"c:/testarea/Images/image1.png",
	"c:/testarea/Images/image2.png",
	"c:/testarea/tempo/temp1.txt",
	"c:/testarea/tempo/temp2.txt",
	"c:/testarea/Images/notes/howto.txt",
	"c:/testarea/Images/notes/sources.txt"
]
'

pf()
# Executed in 0.01 second(s) in Ring 1.22

/*--- Folder Tree Display
*/
pr()

# Softanza embraces a visual grammer for folder tree display
# that is both expressive and practical.

# the grammer can be understood from the @aDisplatChars attribute
# you can find in the class and here is its content:
#
#	@acDisplayChars = [
#
#		# The folder tree lines use these chars
#		:VerticlalChar = "│",
#		:VerticalCharTick = "├",
#		:ClosingChar = "╰",
#
#		# File uses one of these two icons
#		:File = " 🗋",		# file icon by default
#		:FileFound = "📄",	# file icon when a file is found
#
#		# Root folder uses one of these two icons
#		:FolderRoot = "🗀",		# folder icon by default (when Show() is used)
#		:FolderRootXT = "📁",	# folder icon when ShowXT() is used and an info
#								# is added between parenthesis to the right
#
#		# An expanded folder uses one of these two icons
#		:FolderOpened = "🗁",		# when no found files exists inside it
#		:FolderOpenedFound = "📂",	# when files are found inside it
#
#		# A closed folder uses one of these two icons
#		:FolderClosedEmpty = "🗀", 	# when the folder is empty
#		:FolderClosedFull = "🖿",	# when the folder contains files
#
#		# After a VizSearch use this icon in the root stat label
#		:FolderRootSearchSymbol = "",
#
#		# Each found file is proceeded by this icon
#		:FileFoundSymbol = "👉"
#
#	]

# Here is an example:

o1 = new stzFolder("c:/testarea")

# Showing the tree structure (first level folders collapsed by default)

? o1.Show() + NL
#-->
'
🗀 TestArea
├─ 🗋 test.txt
├─🗀 Docs	# <-- 🗀 means the folder is empty
├─🖿 Images # <-- 🖿 means the folder is not empty
├─🗀 Music
├─🗀 Videos
╰─🖿 tempo
'

# Showing meta-statistics

? o1.ShowXT()
#-->
'
📁 TestArea (6) # <-- 📁 ~> XT mode / contains 8 elements at its root (files + folders)
├─ 🗋 test.txt
├─🗀 Docs
├─🖿 Images (4)
├─🗀 Music
├─🗀 Videos
╰─🖿 tempo (2)
'

# change the stats pattern

o1.SetDisplayStat('@CountFiles files, @CountFolders folders')
? o1.ShowXT()
'
📁 TestArea (1 files, 5 folders)	# <-- Your stats added here
├─ 🗋 test.txt
├─🗀 Docs
├─🖿 Images (2 files, 2 folders)	# <-- and here
├─🗀 Music
├─🗀 Videos
╰─🖿 tempo (2 files, 0 folders)		# <-- and here
'

# More interestingly, we can show the ratio of root count over the deep count:

o1.SetDisplayStat('@CountFiles:@DeepCountFiles files, @CountFolders:@DeepCountFolders folders')
? o1.ShowXT()
#-->
'
📁 testarea (1:7 files, 5:7 folders)
├─ 🗋 test.txt
├─🗀 Docs
├─🖿 Images (2:4 files, 2:2 folders)
├─🗀 Music
├─🗀 Videos
╰─🖿 tempo (2:2 files, 0:0 folders)
'

# Expanding the Image folder

o1.ExpandFolder("Images")
? o1.ShowXT()
#-->
'
📁 testarea (1:7 files, 5:7 folders)
├─ 🗋 test.txt
├─🗀 Docs
├─🗁 Images (2:4 files, 2:2 folders)
│ ├─ 🗋 image1.png
│ ├─ 🗋 image2.png
│ ├─🗀 more
│ ╰─🖿 notes (2:2 files, 0:0 folders)
├─🗀 Music
├─🗀 Videos
╰─🖿 tempo (2:2 files, 0:0 folders)
'

# Expanding both "Images" and "Tempo" (without stats)

o1.ExpandFolders([ "Images", "tempo" ])
? o1.Show()
#-->
'
🗀 testarea
├─ 🗋 test.txt
├─🗀 Docs
├─🗁 Images
│ ├─ 🗋 image1.png
│ ├─ 🗋 image2.png
│ ├─🗀 more
│ ╰─🖿 notes
├─🗀 Music
├─🗀 Videos
╰─🗁 tempo
  ├─ 🗋 temp1.txt
  ╰─ 🗋 temp2.txt
'
# NOTE: if you you show the tree again it maintaines the last
# display options and displays the same thing

? o1.Show()
'
🗀 testarea
├─ 🗋 test.txt
├─🗀 Docs
├─🗁 Images
│ ├─ 🗋 image1.png
│ ├─ 🗋 image2.png
│ ├─🗀 more
│ ╰─🖿 notes
├─🗀 Music
├─🗀 Videos
╰─🗁 tempo
  ├─ 🗋 temp1.txt
  ╰─ 🗋 temp2.txt
'

# Expanding "Images" and its "notes" subfolder

o1.Collapse()
o1.ExpandFolders([ "Images", "notes" ])
? o1.Show()
#-->
'
🗀 testarea
├─ 🗋 test.txt
├─🗀 Docs
├─🗁 Images
│ ├─ 🗋 image1.png
│ ├─ 🗋 image2.png
│ ├─🗀 more
│ ╰─🗁 notes
│   ├─ 🗋 howto.txt
│   ╰─ 🗋 sources.txt
├─🗀 Music
├─🗀 Videos
╰─🖿 tempo
'

# Laternatively you exapand the folder Imaages and all it's subfolder1
# in one call using DeepExpand() method like this:

o1.Collapse()
o1.DeepExpandFolder("Images")
? o1.Show()
#-->
'
🗀 testarea
├─ 🗋 test.txt
├─🗀 Docs
├─🗁 Images
│ ├─ 🗋 image1.png
│ ├─ 🗋 image2.png
│ ├─🗁 more
│ ╰─🗁 notes
│   ├─ 🗋 howto.txt
│   ╰─ 🗋 sources.txt
├─🗀 Music
├─🗀 Videos
╰─🖿 tempo
'

# Let's expand all the folder tree in one shot:

o1.DeepExpandAll()
? o1.ShowXT() # Now with statistics
#-->
'
📁 testarea (1:7 files, 5:7 folders)
├─ 🗋 test.txt
├─🗁 Docs
├─🗁 Images (2:4 files, 2:2 folders)
│ ├─ 🗋 image1.png
│ ├─ 🗋 image2.png
│ ├─🗁 more
│ ╰─🗁 notes (2:2 files, 0:0 folders)
│   ├─ 🗋 howto.txt
│   ╰─ 🗋 sources.txt
├─🗁 Music
├─🗁 Videos
╰─🗁 tempo (2:2 files, 0:0 folders)
  ├─ 🗋 temp1.txt
  ╰─ 🗋 temp2.txt
'

pf()

/*---

pr()

o1 = new stzFolder("c:/testarea")

# Geetting the files at the root with a simplified path
? @@( o1.Files() )
#--> [ "/test.txt" ]

# The same thing but with complete path

? @@( o1.FilesXT() )
#--> [ "c:/testarea/test.txt" ]

# Now we check the list of all files at any level

? @@NL( o1.DeepFiles() )
#--> a list of simlified paths
'
[
	"/test.txt",
	"/Images/image1.png",
	"/Images/image2.png",
	"/tempo/temp1.txt",
	"/tempo/temp2.txt",
	"/Images/notes/howto.txt",
	"/Images/notes/sources.txt"
]
'

# We add the XT extension and we get files with full path

? @@NL( o1.DeepFilesXT() )
#-->
'
[
	"c:/testarea/test.txt",
	"c:/testarea/Images/image1.png",
	"c:/testarea/Images/image2.png",
	"c:/testarea/tempo/temp1.txt",
	"c:/testarea/tempo/temp2.txt",
	"c:/testarea/Images/notes/howto.txt",
	"c:/testarea/Images/notes/sources.txt"
]
'

pf()
# Executed in 0.01 second(s) in Ring 1.22

/*---

pr()

o1 = new stzFolder("c:/testarea")
? @@NL( o1.FilesXT() )


? o1.IsFile("test.txt")
#--> FALSE

? o1.IsFile("c:/testarea/test.txt")


pf()

#--

pr()

o1 = new stzFolder("c:/testarea")

? o1.NormalizefileName("test.txt")
#--> /test.txt

? o1.NormalizeFolderName("images") + NL
#--> /images/

? o1.Folders()

? o1.IsFolderPath("/images")
#--> TRUE

? o1.IsFolderPath("images")
#--> TRUE

pf()

/*---
*/

pr()

o1 = new stzFolder("C:\TestArea")

? @@( o1.FindFiles(["test.txt"]) )
#--> [ "test.txt" ]

? @@NL( o1.FindFiles("*.txt") )
#-->
'
[
	"../Images/image1.png",
	"../Images/image2.png",
	"../Images/notes/howto.txt",
	"../Images/notes/sources.txt",
	"../tempo/temp1.txt",
	"../tempo/temp2.txt",
	"../test.txt"
]
'
? @@NL( o1.FindFolders("*m*") )
#-->
'[
	"../Images/",
	"../Images/more/",
	"../Music/",
	"../tempo/"
]'

/*
FindFolders
SearchFolders

Find
Search
*/



pf()
# Executed in 0.07 second(s) in Ring 1.22

/*---- VISUAL FINDING
*/
pr()

o1 = new stzFolder("C:\TestArea")

# VizSearching images in png format
o1.SetDisplayOrder(:FileFirstAscending)
? o1.VizSearchFiles("*.png") + NL
#-->
"
📁 TestArea (🔍 0 file matches for '*.png')
├─📁 Docs
├─🔍📁 Images
│  ╰─🎯📄 image.png
├─📁 Music
├─📁 NewlyAdded
├─📁 Videos
╰─📄 test.txt
"

# VizSearching folders with an 'i' letter in their name

? o1.VizSearchFolders("*i*")

pf()

#===================#
#  UTILITY METHODS  #
#===================#


/*--- Copy and Clone

pr()

o1 = new stzFolder("C:\Windows\System32")
o2 = o1.Copy() # Or Clone()

# Original path
? o1.Path()
#--> C:\Windows\System32

# Copy path
? o2.Path()
#--> C:\Windows\System32

pf()
# Executed in almost 0 second(s) in Ring 1.22

/*--- Refresh Operation

pr()

o1 = new stzFolder("C:\TestArea")
o1 {
    # Count before refresh
	? Count() # or CountFilesAndFolders()
    #-->  5
    
    CreateFolder("NewlyAdded")
    
    Refresh()
    ? Count()
    #--> 6
}

pf()
# Executed in almost 0 second(s) in Ring 1.23
# Executed in 0.02 second(s) in Ring 1.22

/*--- Folder creation and navigation logic
   Demonstrates how to use the stzFolder class to navigate the file system,
   create folders, and track the current path. Highlights support for
   both sequential navigation and scoped (block-based) folder creation.

pr()

o1 = new stzFolder("C:\")  # Start from root directory
o1 {

    GoTo("Windows")        # Navigate into 'Windows' folder
    GoTo("System32")       # Further descend into 'System32' (example of deep navigation)
    Up()                   # Move one level up (back to 'Windows')
    GoTo("Temp")           # Enter 'Temp' folder — final target before creation

	# Confirm current path before folder operations
    ? Path()
    #--> C:/Windows/Temp

    # Chain folder creation without changing the current location
    CreateFolder("ChainTest")  
    # Creates 'ChainTest' inside 'Temp' — current path remains at 'Temp'

    GoTo("ChainTest")       
    # Manually enter 'ChainTest' after creation

    CreateFolder("SubTest") {  
        # Create 'SubTest' inside 'ChainTest' and *immediately* enter it via block scope
        ? Path() 
        # Outputs full path from inside the 'SubTest' block
    }

    # After the block, we are still inside 'SubTest'
    ? Path()
    #--> C:/Windows/Temp/ChainTest/SubTest
    # Confirms persistent navigation after block exit
}

pf()
# Executed in almost 0 second(s) in Ring 1.22

#==========================#
#  COMPREHENSIVE WORKFLOW  #
#==========================#

/*--- Complete Folder Management Workflow
*/
pr()

# 1. Create main project folder
oProject = new stzFolder("C:\MyProject")
oProject {

    ? @@NL( Info() ) + NL
    
    # 2. Create project structure

    aFolders = ["src", "docs", "tests", "build", "assets"]
    CreateFolders(aFolders)
   
	? @@( Folders() ) + NL
    
    # 3. Navigate and create sub-structure

    GoTo("src")
    CreateFolders(["models", "views", "controllers"])
    
    Up()
    GoTo("assets")
    CreateFolders(["images", "css", "js"])
    
    # Go back to root and show final structure
    Up()

    # Final project tree
    ShowXT(2)
    
    # 5. Get comprehensive info
    ? ""
    ? @@NL( Info() ) + NL
    
    # 6. Search for specific patterns

    ? @@NL( FindFolders("*view*") )
    
    # 7. Cleanup (commented out for safety)

    ? DeepRemoveAll() # TRUE
    ? Count() #--> 0 #Now the folder is empy!

}

pf()
# Executed in 0.01 second(s) in Ring 1.23
