#--------------------------------------------------------------#
#        SOFTANZA LIBRARY (V0.9) - STZEDUREADER                #
#   An accelerative library for Ring applications, and more!   #
#--------------------------------------------------------------#
#                                                              #
#   Description  : The READER: one self-contained HTML page    #
#                  for a course, generated by Softanza. It     #
#                  stores NO output, and every cell says where #
#                  it runs, as the guard OBSERVED it.          #
#   Version      : V0.9 (2026)                                 #
#   Author       : Mansour Ayouni (kalidianow@gmail.com)       #
#                                                              #
#--------------------------------------------------------------#
#
# The page follows the ayouni reader's patterns (articles switched by the
# URL hash, no build tool, print through @media print) with no Python at
# build time or at run time (law 1). It loads nothing from the network:
# a page opened from a folder shows everything it has.
#
# What the page never holds: an output. A cell's output area carries a
# fixed sentence saying the page stores none. The promises (`#-->` lines)
# stay, because they are the author's EXPECTATION, part of the source --
# not a result some run once produced.
#
#   oReader = new stzEduReader(oCourse)
#   oReader.AddChapter(oChapterEn)     # chapters that were RUN and OBSERVED
#   oReader.AddQuestion("remove duplicates", "stzList")
#   oReader.WriteTo("reader.html")

func _EduLangName(pcLang)
	switch pcLang
	on "en" return "English"
	on "fr" return "Fran&ccedil;ais"
	on "ar" return "&#1575;&#1604;&#1593;&#1585;&#1576;&#1610;&#1577;"
	on "ha" return "Hausa"
	off
	return pcLang

# A code cell, escaped, with every non-ASCII string literal isolated in
# <bdi>: inside a left-to-right code block, an Arabic string otherwise
# lets the bidi algorithm reorder the numbers around it, and a monospace
# font with no Arabic glyphs draws its letters unjoined. Both were SEEN
# in the first render of the Arabic chapter (2026-09-23), not assumed.
func _EduCodeToHtml(pcCode)
	_acParts_ = StzSplit(pcCode, '"')
	_c_ = ""
	_nL_ = len(_acParts_)
	for _i_ = 1 to _nL_
		if _i_ > 1
			_c_ += "&quot;"
		ok
		_seg_ = _acParts_[_i_]
		_bWide_ = 0
		if _i_ % 2 = 0
			_nB_ = len(_seg_)
			for _k_ = 1 to _nB_
				if ascii(_seg_[_k_]) > 127
					_bWide_ = 1
					exit
				ok
			next
		ok
		if _bWide_
			_c_ += "<bdi>" + _EduEsc(_seg_) + "</bdi>"
		else
			_c_ += _EduEsc(_seg_)
		ok
	next
	return _c_

func _EduEsc(pcText)
	_c_ = StzReplace("" + pcText, "&", "&amp;")
	_c_ = StzReplace(_c_, "<", "&lt;")
	_c_ = StzReplace(_c_, ">", "&gt;")
	_c_ = StzReplace(_c_, '"', "&quot;")
	return _c_

# `code`, **bold** and *emphasis*, escaped segment by segment.
func _EduInline(pcText)
	_acParts_ = StzSplit(pcText, "`")
	_c_ = ""
	_nL_ = len(_acParts_)
	for _i_ = 1 to _nL_
		if _i_ % 2 = 0
			_c_ += "<code>" + _EduEsc(_acParts_[_i_]) + "</code>"
		else
			_acB_ = StzSplit(_acParts_[_i_], "**")
			_nB_ = len(_acB_)
			for _j_ = 1 to _nB_
				_acE_ = StzSplit(_acB_[_j_], "*")
				_cSeg_ = ""
				_nE_ = len(_acE_)
				for _k_ = 1 to _nE_
					if _k_ % 2 = 0
						_cSeg_ += "<em>" + _EduEsc(_acE_[_k_]) + "</em>"
					else
						_cSeg_ += _EduEsc(_acE_[_k_])
					ok
				next
				if _j_ % 2 = 0
					_c_ += "<b>" + _cSeg_ + "</b>"
				else
					_c_ += _cSeg_
				ok
			next
		ok
	next
	return _c_

# Headings, paragraphs, lists, block quotes and indented code.
func _EduProseToHtml(pcText)
	_acL_ = StzSplit(StzReplace(pcText, char(13), ""), char(10))
	_c_ = ""
	_cPara_ = ""
	_bList_ = 0
	_nL_ = len(_acL_)
	for _i_ = 1 to _nL_
		_raw_ = _acL_[_i_]
		_t_ = ring_trim(_raw_)
		_bFlush_ = (_t_ = "" or StzLeft(_t_, 1) = "#" or StzLeft(_t_, 2) = "- " or StzLeft(_t_, 2) = "> " or StzLeft(_raw_, 4) = "    ")
		if _bFlush_ and _cPara_ != ""
			if _bList_
				_c_ += "<li>" + _EduInline(_cPara_) + "</li>"
			else
				_c_ += "<p>" + _EduInline(_cPara_) + "</p>" + char(10)
			ok
			_cPara_ = ""
		ok
		if _bList_ and (_t_ = "" or StzLeft(_t_, 1) = "#")
			_c_ += "</ul>" + char(10)
			_bList_ = 0
		ok
		if _t_ = ""
			loop
		ok
		if StzLeft(_t_, 4) = "### "
			_c_ += "<h3>" + _EduInline(StzRight(_t_, StzLen(_t_) - 4)) + "</h3>" + char(10)
		but StzLeft(_t_, 3) = "## "
			_c_ += "<h2>" + _EduInline(StzRight(_t_, StzLen(_t_) - 3)) + "</h2>" + char(10)
		but StzLeft(_t_, 2) = "# "
			_c_ += "<h1>" + _EduInline(StzRight(_t_, StzLen(_t_) - 2)) + "</h1>" + char(10)
		but StzLeft(_t_, 2) = "> "
			_c_ += "<blockquote>" + _EduInline(StzRight(_t_, StzLen(_t_) - 2)) + "</blockquote>" + char(10)
		but StzLeft(_raw_, 4) = "    " and NOT _bList_
			_c_ += '<pre dir="ltr">' + _EduEsc(_t_) + "</pre>" + char(10)
		but StzLeft(_t_, 2) = "- "
			if NOT _bList_
				_c_ += "<ul>"
				_bList_ = 1
			ok
			_cPara_ = StzRight(_t_, StzLen(_t_) - 2)
		else
			if _cPara_ != ""
				_cPara_ += " "
			ok
			_cPara_ += _t_
		ok
	next
	if _cPara_ != ""
		if _bList_
			_c_ += "<li>" + _EduInline(_cPara_) + "</li>"
		else
			_c_ += "<p>" + _EduInline(_cPara_) + "</p>" + char(10)
		ok
	ok
	if _bList_
		_c_ += "</ul>" + char(10)
	ok
	return _c_

func _EduReaderCss()
	return ":root{--paper:#f7f6f2;--panel:#ffffff;--ink:#1d2320;--ink2:#46504b;--line:#d9ddd9;--accent:#1b6b72;--code:#f1f3f1;--desk:#8a5a12;--desk-bg:#f7ecd8;--web:#2e7d5b;--web-bg:#e3f1e9}" +
	       "@media (prefers-color-scheme:dark){:root{--paper:#131715;--panel:#1b201e;--ink:#e9ede9;--ink2:#b5beb9;--line:#303935;--accent:#63b6bc;--code:#171c1a;--desk:#e0b268;--desk-bg:#322712;--web:#6cc095;--web-bg:#1a2f24}}" +
	       "*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:17px/1.6 system-ui,-apple-system,'Segoe UI',Tahoma,sans-serif}" +
	       "header{position:sticky;top:0;display:flex;flex-wrap:wrap;gap:8px 20px;align-items:center;justify-content:space-between;padding:12px 16px;background:var(--panel);border-bottom:1px solid var(--line)}" +
	       ".brand{font-weight:700;color:var(--accent)}nav a{margin-inline-end:14px;color:var(--ink2);text-decoration:none;font-weight:600}nav a.on{color:var(--accent);text-decoration:underline}" +
	       "main{max-width:820px;margin:0 auto;padding:16px}article{display:none}article.on{display:block}h1{font-size:2rem;line-height:1.2}h2{margin-top:2rem}" +
	       "code{font-family:ui-monospace,Consolas,monospace;background:var(--code);padding:1px 5px;border-radius:4px}pre{background:var(--code);border:1px solid var(--line);border-radius:8px;padding:12px;overflow-x:auto;margin:0}pre code{background:none;padding:0}bdi{font-family:system-ui,'Segoe UI',Tahoma,sans-serif}" +
	       "figure.cell{margin:14px 0;border:1px solid var(--line);border-radius:10px;overflow:hidden;background:var(--panel)}figure.cell figcaption{font-size:14px;font-weight:700;padding:6px 12px}" +
	       "figure[data-where=desktop] figcaption{color:var(--desk);background:var(--desk-bg)}figure[data-where=browser] figcaption{color:var(--web);background:var(--web-bg)}" +
	       "figure.cell pre{border:0;border-radius:0}.out{padding:8px 12px;color:var(--ink2);border-top:1px dashed var(--line);font-size:15px}" +
	       "aside.exercise{border-inline-start:4px solid var(--accent);background:var(--panel);padding:4px 16px 8px;margin:22px 0;border-radius:8px}.note{color:var(--ink2);font-size:15px}" +
	       "blockquote{margin:10px 0;padding:6px 12px;border-inline-start:3px solid var(--line);color:var(--ink2)}.qa{border-top:1px solid var(--line);margin-top:30px}" +
	       "@media print{header{position:static}article{display:block;page-break-after:always}}"

func _EduReaderJs()
	return "(function(){var arts=document.querySelectorAll('article'),links=document.querySelectorAll('nav a');" +
	       "function show(l){var hit=false;arts.forEach(function(a){var on=a.getAttribute('data-lang')===l;a.classList.toggle('on',on);if(on)hit=true;});" +
	       "if(!hit&&arts.length){arts[0].classList.add('on');l=arts[0].getAttribute('data-lang');}" +
	       "links.forEach(function(a){a.classList.toggle('on',a.getAttribute('data-go')===l);});}" +
	       "window.addEventListener('hashchange',function(){show(location.hash.slice(1));});show(location.hash.slice(1));})();"

class stzEduReader from stzObject

	@oCourse
	@aChapters = []
	@aQandA = []     # [ question, class, method, explanation ]

	def init(poCourse)
		@oCourse = poCourse

	def AddChapter(poChapter)
		if len(poChapter.Where()) = 0
			StzRaise("A chapter enters the reader only after ObserveWhere(): runs-where is observed, never assumed.")
		ok
		@aChapters + poChapter

		def AddChapterQ(poChapter)
			This.AddChapter(poChapter)
			return This

	# A Q&A generated from the library itself, when the page is built.
	def AddQuestion(pcQuestion, pcClass)
		_oDoc_ = StzSelfDocQ(pcClass)
		_aA_ = _oDoc_.Ask(pcQuestion)
		if len(_aA_) = 0
			StzRaise("The library has no answer to '" + pcQuestion + "' in " + pcClass + "; a page may not invent one.")
		ok
		_cMethod_ = _aA_[1][1]
		@aQandA + [ pcQuestion, pcClass, _cMethod_, _oDoc_.ExplainMethod(_cMethod_) ]

	def QandA()
		return @aQandA

	def Html()
		_c_ = '<!doctype html>' + char(10) + '<html lang="en"><head><meta charset="utf-8">' +
		      '<meta name="viewport" content="width=device-width,initial-scale=1">' +
		      '<title>' + _EduEsc(@oCourse.Slug()) + '</title>' + char(10) +
		      '<style>' + _EduReaderCss() + '</style></head><body>' + char(10)
		_c_ += '<header><div class="brand">Softanza &middot; ' + _EduEsc(@oCourse.Slug()) + '</div><nav>'
		# one link per LANGUAGE, whatever the number of chapters in it --
		# the first course page showed 24 links for 4 languages (2026-09-24)
		_acSeen_ = []
		_nL_ = len(@aChapters)
		for _i_ = 1 to _nL_
			_cL_ = @aChapters[_i_].Language()
			if StzFindFirst(_cL_, _acSeen_) > 0
				loop
			ok
			_acSeen_ + _cL_
			_c_ += '<a href="#' + _cL_ + '" data-go="' + _cL_ + '">' + _EduLangName(_cL_) + '</a>'
		next
		_c_ += '</nav></header>' + char(10) + '<main>' + char(10)
		for _i_ = 1 to _nL_
			_c_ += This._Article(@aChapters[_i_])
		next
		if len(@aQandA) > 0
			_c_ += '<section class="qa"><h2>Q&amp;A, generated from the library</h2>'
			_nQ_ = len(@aQandA)
			for _i_ = 1 to _nQ_
				_c_ += '<p><b>' + _EduEsc(@aQandA[_i_][1]) + '</b> &rarr; <code>' + _EduEsc(@aQandA[_i_][2]) + '.' +
				       _EduEsc(@aQandA[_i_][3]) + '()</code><br>' + _EduEsc(@aQandA[_i_][4]) + '</p>'
			next
			_c_ += '</section>' + char(10)
		ok
		_c_ += '</main>' + char(10) + '<script>' + _EduReaderJs() + '</script></body></html>' + char(10)
		return _c_

	def WriteTo(pcFile)
		write(pcFile, This.Html())
		return pcFile

	def _Article(poCh)
		_cL_ = poCh.Language()
		_cDir_ = "ltr"
		if _cL_ = "ar"
			_cDir_ = "rtl"
		ok
		_c_ = '<article data-lang="' + _cL_ + '" lang="' + _cL_ + '" dir="' + _cDir_ + '">' + char(10)
		_aB_ = poCh.Blocks()
		_nB_ = len(_aB_)
		for _i_ = 1 to _nB_
			_cKind_ = _aB_[_i_][1]
			if _cKind_ = "prose"
				_c_ += _EduProseToHtml(_aB_[_i_][2])
			but _cKind_ = "cell"
				_n_ = _aB_[_i_][2]
				_cW_ = poCh.RunsWhere(_n_)
				_c_ += '<figure class="cell" data-where="' + _cW_ + '"><figcaption>' +
				       _EduEsc(_EduSay(_cL_, "cell-" + _cW_, "")) + '</figcaption>' +
				       '<pre dir="ltr"><code>' + _EduCodeToHtml(poCh.Cell(_n_)) + '</code></pre>' +
				       '<div class="out">' + _EduEsc(_EduSay(_cL_, "cell-no-output", "")) + '</div></figure>' + char(10)
			but _cKind_ = "exercise"
				_oEx_ = @oCourse.ExerciseQ(_aB_[_i_][2])
				_c_ += '<aside class="exercise">' + _EduProseToHtml(_oEx_.Task(_cL_)) +
				       '<p class="note">' + _EduEsc(_EduSay(_cL_, "exercise-note", "")) + '</p></aside>' + char(10)
			but _cKind_ = "fence"
				_c_ += '<pre dir="ltr">' + _EduEsc(_aB_[_i_][2]) + '</pre>' + char(10)
			ok
		next
		_c_ += '</article>' + char(10)
		return _c_

