load "../../stzBase.ring"
load "../_narrated.ring"

# PY5, stage (a) of the payments plane: THE LIVE ADAPTER, AGAINST THE TWIN SERVED OVER HTTP.
#
# The adapter is the other backend of the port: the same Request(method, path, query, body) the
# twin answers in-process, over the wire, to any participant. Here the participant is the twin
# behind stzAppServer in a REAL separate process (stzPiSpiHttpFront), with what a participant
# puts in front of the contract: an OAuth 2.0 token endpoint, an API key, scopes, and, in a
# second process, mutual TLS.
#
# THREE STAGES, each reported by its own name:
#   (a) this guard: the twin over HTTP, plain and mutual TLS
#   (b) the conformance run, under DIKO's sandbox account, by a named person: UNPERCEIVED until
#       that person has watched a payment land in the sandbox dashboard (payments_conformance_run.ring)
#   (c) BIA in production: never from this plane, only inside DIKO's amendment
#
# Every credential below is GENERATED by this guard at run time and handed to the server process
# in a temporary script that is deleted at the end. The only key material in the repository this
# touches is the engine's throwaway TEST-ONLY mutual-TLS fixture (engine/src/mtls_certs), which
# the mTLS guard of the cluster plane already uses.

$cCertDir = $cEngineDir + "/src/mtls_certs"
$cNodeCrt = $cCertDir + "/node.crt.pem"
$cNodeKey = $cCertDir + "/node.key.pem"
$cCACrt   = $cCertDir + "/ca.crt.pem"
$cWrongCA = $cCertDir + "/server.crt.pem"
$nPortA   = 46300 + (StzEngineTimeNowMs() % 150)
$nPortB   = 46500 + (StzEngineTimeNowMs() % 150)
$cClientId = "diko-" + StzEngineCryptoRandomHex(4)
$cClientSecret = StzEngineCryptoRandomHex(16)
$cApiKey = StzEngineCryptoRandomHex(12)
$oSpawner = new stzReactor()
$oSpawnerB = new stzReactor()      # one spawner per long-lived server: a spawner runs its jobs one after another
$oGuardTls = new stzReactor()

$nJobA = SpawnFront("plain", $nPortA)
$nJobB = SpawnFront("mtls", $nPortB)
bUpA = WaitFront("plain", $nPortA, 30000)
bUpB = WaitFront("mtls", $nPortB, 30000)

Scenario("two real server processes are up")
	Then("the plain front answers its control surface", bUpA, TRUE)
	Then("the mutual-TLS front answers a client that presents a certificate", bUpB, TRUE)
	aS = Ctl($nPortA, "GET", "state", [])
	Then("a front starts with the platform's 50 000 000 virtual francs", pzVal(aS, "balance"), 50000000)
	Then("...and has issued no token yet", pzVal(aS, "tokensIssued"), 0)
EndScenario()

Scenario("OAuth client credentials: asked once, cached, refreshed, retried once on a revoked token")
	oAd = MkAdapter($nPortA, "piz/", [])
	oPay = UngovernedPort(oAd)
	aAcc = oPay.Accounts()
	Then("the first call fetches a token and the contract answers: two accounts", len(aAcc), 2)
	Then("...one token was fetched", oAd.TokensFetched(), 1)
	oPay.Accounts()
	oPay.Participants()
	Then("the next calls reuse it", oAd.TokensFetched(), 1)
	Then("...the front issued exactly one", pzVal(Ctl($nPortA, "GET", "state", []), "tokensIssued"), 1)

	Ctl($nPortA, "POST", "token-ttl", [ ["seconds", 30] ])
	oAd.ForgetToken()
	oPay.Accounts()
	Then("a token that lives under a minute is not kept: it is fetched again", oAd.TokensFetched(), 2)
	oPay.Accounts()
	Then("...every call, because it is already inside the refresh margin", oAd.TokensFetched(), 3)
	Ctl($nPortA, "POST", "token-ttl", [ ["seconds", 3600] ])
	oAd.ForgetToken()
	oPay.Accounts()
	oPay.Accounts()
	Then("a long-lived token is fetched once and kept", oAd.TokensFetched(), 4)

	Ctl($nPortA, "POST", "revoke-tokens", [])
	aAfter = oPay.Accounts()
	Then("when the hub revokes the token the call still succeeds", len(aAfter), 2)
	Then("...by dropping it, fetching one fresh and retrying ONCE", oAd.TokensFetched(), 5)

	oBad = MkAdapterWith($nPortA, "piz/", [], $cClientId, "not-the-secret", $cApiKey)
	bRaised = FALSE
	cWhy = ""
	try
		UngovernedPort(oBad).Accounts()
	catch
		bRaised = TRUE
		cWhy = cCatchError
	done
	Then("a wrong client secret is refused at the token endpoint", bRaised, TRUE)
	Then("...and the adapter says so, not 'no accounts'", StzFindFirst("token endpoint answered 401", cWhy) > 0, TRUE)

	oNoKey = MkAdapterWith($nPortA, "piz/", [], $cClientId, $cClientSecret, "a-wrong-api-key")
	bKey = FALSE
	try
		UngovernedPort(oNoKey).Accounts()
	catch
		bKey = TRUE
	done
	Then("a wrong API key is refused by the hub", bKey, TRUE)
	oStoreLess = StzPispiHttpAdapterQ()
	oStoreLess.WithBaseUrl("http://127.0.0.1:" + $nPortA + "/piz/v1")
	bNo = FALSE
	cNo = ""
	try
		UngovernedPort(oStoreLess).Accounts()
	catch
		bNo = TRUE
		cNo = cCatchError
	done
	Then("an adapter given no credentials refuses to guess", bNo, TRUE)
	Then("...naming what is missing", StzFindFirst("no credentials", cNo) > 0, TRUE)
EndScenario()

Scenario("scopes are the hub's, and a narrower token is a narrower adapter")
	oRead = MkAdapter($nPortA, "piz/", [ "paiement.read" ])
	oPayR = UngovernedPort(oRead)
	Then("a token with paiement.read lists payments", len(oPayR.SentPayments([])), 0)
	bScope = FALSE
	try
		oPayR.Accounts()
	catch
		bScope = TRUE
	done
	Then("...and is refused on accounts, which need compte.read", bScope, TRUE)
	oProb = StzLastPaymentsProblem()
	Then("...as the reference's 401 problem", oProb.Status(), 401)
	Then("...naming the scope the operation needed", StzFindFirst("compte.read", oProb.Detail()) > 0, TRUE)

	bWrite = FALSE
	aAl = Ctl($nPortA, "GET", "alias", [])
	try
		oPayR.Pay( MkOrderA(aAl, "SC-1", "fatou", 1000) )
	catch
		bWrite = TRUE
	done
	Then("a read-only token cannot pay", bWrite, TRUE)
	Then("...and nothing left the account", pzVal(Ctl($nPortA, "GET", "state", []), "balance"), 50000000)

	oNoPrefix = MkAdapter($nPortA, "", [])
	bPrefix = FALSE
	try
		UngovernedPort(oNoPrefix).Accounts()
	catch
		bPrefix = TRUE
	done
	Then("the sandbox's piz/ prefix is part of the scope: without it the hub refuses", bPrefix, TRUE)
EndScenario()

Scenario("the whole contract crosses the wire: pay, request, return, cancel, bulk, aliases, lists")
	oAd = MkAdapter($nPortA, "piz/", [])
	oPay = UngovernedPort(oAd)
	aAl = Ctl($nPortA, "GET", "alias", [])
	nB0 = pzVal(Ctl($nPortA, "GET", "state", []), "balance")

	oOrder = MkOrderA(aAl, "W-1", "fatou", 150000)
	aR = oPay.Pay(oOrder)
	Then("a payment is ENVOYE, the hub's own word", aR["statut"], "ENVOYE")
	Then("...with a 35-character end2endId", len(aR["end2endId"]), 35)
	Ctl($nPortA, "POST", "advance", [ ["seconds", 25] ])
	Then("twenty seconds later it is IRREVOCABLE", pzVal(oPay.StatusOf(aR["end2endId"]), "statut"), "IRREVOCABLE")
	Then("...and 150 000 left the account", pzVal(Ctl($nPortA, "GET", "state", []), "balance"), nB0 - 150000)
	Then("a replay through the port reads, and pays nothing", pzVal(oPay.Pay(oOrder), "replayed"), 1)
	Then("...so the balance did not move", pzVal(Ctl($nPortA, "GET", "state", []), "balance"), nB0 - 150000)

	aDup = oAd.Request("POST", "/paiements-envoyes", [], oOrder.AsBody())
	Then("the same txId at the hub, over the wire, is 200", pzNth(aDup, 1), 200)
	Then("...REJETE", pzVal(pzNth(aDup, 2), "statut"), "REJETE")
	Then("...DU03", pzVal(pzNth(aDup, 2), "statutRaison"), "DU03")

	aBodyBad = oOrder.AsBody()
	aBodyBad + [ "devise", "XOF" ]
	aBad = oAd.Request("POST", "/paiements-envoyes", [], aBodyBad)
	Then("a field the schema does not know is a 400 over the wire too", pzNth(aBad, 1), 400)
	aInv = pzVal(pzNth(aBad, 2), "invalid-params")
	Then("...and the problem names it", pzVal(pzNth(aInv, 1), "name"), "devise")

	bBig = FALSE
	try
		oPay.Pay( MkOrderA(aAl, "W-BIG", "fatou", 20000000) )
	catch
		bBig = TRUE
	done
	Then("the ceiling is a 403 problem the port raises", bBig, TRUE)
	Then("...with the reference's detail", StzLastPaymentsProblem().Detail(), "Plafond de paiement depasse")

	oUtf = MkOrderA(aAl, "W-UTF", "fatou", 2000)
	oUtf.Motive("Salaire de mars - equipe " + "caf" + char(195) + char(169))
	oPay.Pay(oUtf)
	Then("a motive with an accent crosses the wire intact", pzVal(oPay.SentPayment("W-UTF"), "motif"), "Salaire de mars - equipe caf" + char(195) + char(169))

	oRtp = StzPaymentRequestQ()
	oRtp.WithTxId("W-R1")
	oRtp.FromAlias(pzVal(aAl, "fatou"))
	oRtp.ToAlias(pzVal(aAl, "business"))
	oRtp.WithAmount(StzAmountQ("25000", "XOF"))
	oRtp.InCategory("401")
	oRtp.PayableBy("2026-10-31")
	oRtp.WithoutConfirmation()
	Then("a request to pay is ENVOYE", pzVal(oPay.RequestPayment(oRtp), "statut"), "ENVOYE")
	Ctl($nPortA, "POST", "advance", [ ["seconds", 25] ])
	Then("...and the payer pays it", pzVal(oPay.RequestedPayment("W-R1"), "statut"), "IRREVOCABLE")

	aIn = Ctl($nPortA, "POST", "incoming-payment", [ ["who", "fatou"], ["amount", 40000], ["motif", "Don"] ])
	aRet = oPay.ReturnFunds(pzVal(aIn, "end2endId"))
	Then("a return starts: INITIE", aRet["retourStatut"], "INITIE")

	aC1 = oPay.Pay( MkOrderA(aAl, "W-C1", "fatou", 30000) )
	Ctl($nPortA, "POST", "advance", [ ["seconds", 25] ])
	aCan = oPay.RequestCancellation(aC1["end2endId"], "DUPL")
	Then("a cancellation is a request: ENVOYE", aCan["annulationStatut"], "ENVOYE")
	Ctl($nPortA, "POST", "advance", [ ["seconds", 25] ])
	Then("...accepted by the payee", pzVal(oPay.StatusOf(aC1["end2endId"]), "annulationStatut"), "ACCEPTE")

	oOne = StzPaymentBatchQ()
	oOne.WithInstructionId("W-B1")
	oOne.FromAlias(pzVal(aAl, "business"))
	oOne.WithoutConfirmation()
	oOne.Add( MkOrderA(aAl, "W-B1-1", "kdi", 3000) )
	aB1 = oPay.PayInBulk(oOne)
	Then("a bulk of ONE item is still an array on the wire", aB1["transactionsTotal"], 1)
	Then("...CONFIRME at once", aB1["statut"], "CONFIRME")
	oTwo = StzPaymentBatchQ()
	oTwo.WithInstructionId("W-B2")
	oTwo.FromAlias(pzVal(aAl, "business"))
	oTwo.WithConfirmation()
	oTwo.Add( MkOrderA(aAl, "W-B2-1", "fatou", 1000) )
	oTwo.Add( MkOrderA(aAl, "W-B2-2", "kdi", 2000) )
	Then("a bulk with confirmation waits: INITIE", pzVal(oPay.PayInBulk(oTwo), "statut"), "INITIE")
	Then("...and confirming it is the boolean true on the wire", pzVal(oPay.ConfirmBulk("W-B2", TRUE), "transactionsEnvoyees"), 2)

	aAcc = oPay.Accounts()
	Then("accounts, over the wire", len(aAcc), 2)
	aNew = oPay.CreateAlias(pzVal(aAl, "account"), "SHID")
	Then("an alias can be created", aNew["type"], "SHID")
	Then("...and deleted", oPay.DeleteAlias(pzVal(aAl, "account"), aNew["cle"]), 1)
	Then("the participants list has five", len(oPay.Participants()), 5)
	aWho = oPay.ResolveAlias(pzVal(aAl, "fatou"))
	Then("an alias resolves to a client", pzVal(pzVal(aWho, "client"), "nom"), "Fatou Diop")

	aPage = oPay.SentPaymentsPage([ ["size", "2"], ["page", "1"], ["sort", "-montant"] ])
	Then("paging: a page of two", len(pzVal(aPage, "data")), 2)
	Then("...sorted by montant descending, the biggest first", pzVal(pzNth(pzVal(aPage, "data"), 1), "montant"), 150000)
	Then("...with the meta the reference describes", pzVal(pzVal(aPage, "meta"), "size"), 2)
	aBig = oPay.SentPayments([ ["montant[gte]", "100000"] ])
	Then("a filter with brackets on the wire: montant[gte]", len(aBig), 1)
	Then("...keeps the one payment of 150 000", pzVal(pzNth(aBig, 1), "txId"), "W-1")
	Then("a filter on the status", len(oPay.SentPayments([ ["statut", "IRREVOCABLE"], ["txId[beginsWith]", "W-"] ])) > 0, TRUE)

	bUnknown = FALSE
	try
		oPay.SentPayment("NO-SUCH-TX")
	catch
		bUnknown = TRUE
	done
	Then("an unknown payment is a 404 problem", bUnknown, TRUE)
	Then("...with the status in it", StzLastPaymentsProblem().Status(), 404)

	Ctl($nPortA, "POST", "advance", [ ["seconds", 120] ])      # clear the twin's one-minute window
	Ctl($nPortA, "POST", "rate-limit", [ ["perMin", 3], ["perDay", 10000] ])
	oPay.Accounts()
	oPay.Accounts()
	oPay.Accounts()
	bQuota = FALSE
	try
		oPay.Accounts()
	catch
		bQuota = TRUE
	done
	Then("the quota is a 429 over the wire", bQuota, TRUE)
	Then("...and the problem says so", StzLastPaymentsProblem().Status(), 429)
	Ctl($nPortA, "POST", "rate-limit", [ ["perMin", 100], ["perDay", 10000] ])
	Ctl($nPortA, "POST", "advance", [ ["seconds", 70] ])
	Then("a minute later the hub answers again", len(oPay.Accounts()), 2)
EndScenario()

Scenario("webhooks over the wire: the twelve events the reference describes")
	oAd = MkAdapter($nPortA, "piz/", [])
	oPay = UngovernedPort(oAd)
	aAl = Ctl($nPortA, "GET", "alias", [])
	aH = oPay.RegisterWebhook( StzWebhookQ().CallingBack("https://diko.example/pispi") )
	Then("a webhook is registered over the wire", aH["id"] != "", TRUE)
	Then("...and the hub's secret came back once, to the port", len(oPay.Webhooks()) > 0, TRUE)
	Ctl($nPortA, "POST", "settle", [])
	Ctl($nPortA, "GET", "deliveries", [])

	# PAIEMENT_ENVOYE and PAIEMENT_REJETE
	oPay.Pay( MkOrderA(aAl, "E-1", "fatou", 5000) )
	oPay.Pay( MkOrderA(aAl, "E-2", "blocked", 5000) )
	# PAIEMENT_RECU (a customer pays us) and RETOUR_ENVOYE (we return it), RETOUR_REJETE (we return one the payer's side refuses)
	aP1 = Ctl($nPortA, "POST", "incoming-payment", [ ["who", "fatou"], ["amount", 4000], ["motif", "a"] ])
	oPay.ReturnFunds(pzVal(aP1, "end2endId"))
	aP2 = Ctl($nPortA, "POST", "incoming-payment", [ ["who", "blocked"], ["amount", 4000], ["motif", "b"] ])
	oPay.ReturnFunds(pzVal(aP2, "end2endId"))
	# RTP_RECU, RTP_REPONSE_REJETE
	eRq = pzVal(Ctl($nPortA, "POST", "incoming-request", [ ["who", "kdi"], ["amount", 1000], ["motif", "r"] ]), "end2endId")
	Ctl($nPortA, "POST", "fail-next-answer", [])
	oPay.AnswerRequest(eRq, FALSE, "AM09")
	# RTP_REJETE (a request to a payer who refuses)
	oRtp = StzPaymentRequestQ()
	oRtp.WithTxId("E-R1")
	oRtp.FromAlias(pzVal(aAl, "blocked"))
	oRtp.ToAlias(pzVal(aAl, "business"))
	oRtp.WithAmount(StzAmountQ("2000", "XOF"))
	oRtp.InCategory("401")
	oRtp.PayableBy("2026-10-31")
	oRtp.WithoutConfirmation()
	oPay.RequestPayment(oRtp)
	# ANNULATION_DEMANDE, ANNULATION_REPONSE_REJETE
	aP3 = Ctl($nPortA, "POST", "incoming-payment", [ ["who", "fatou"], ["amount", 1500], ["motif", "c"] ])
	Ctl($nPortA, "POST", "cancellation-request", [ ["end2endId", pzVal(aP3, "end2endId")], ["motif", "DUPL"] ])
	Ctl($nPortA, "POST", "fail-next-answer", [])
	oPay.AnswerCancellation(pzVal(aP3, "end2endId"), FALSE)
	# RETOUR_RECU (our cancellation is accepted) and ANNULATION_REJETE (it is refused)
	aC1 = oPay.Pay( MkOrderA(aAl, "E-C1", "fatou", 1000) )
	aC2 = oPay.Pay( MkOrderA(aAl, "E-C2", "stubborn", 1000) )
	Ctl($nPortA, "POST", "advance", [ ["seconds", 25] ])
	oPay.RequestCancellation(aC1["end2endId"], "DUPL")
	oPay.RequestCancellation(aC2["end2endId"], "SVNR")
	Ctl($nPortA, "POST", "advance", [ ["seconds", 25] ])
	Ctl($nPortA, "POST", "settle", [])

	aDel = pzVal(Ctl($nPortA, "GET", "deliveries", []), "data")
	Then("the hub queued signed events", len(aDel) >= 12, TRUE)
	aSeen = []
	nAccepted = 0
	for i = 1 to len(aDel)
		aV = oPay.ReceiveWebhook(pzVal(aDel[i], "body"), pzVal(aDel[i], "signature"))
		if aV["accepted"] = 1
			nAccepted++
			aEv = aV["events"]
			cCode = pzVal(aEv[1], "evCode")
			if ring_find(aSeen, cCode) = 0
				aSeen + cCode
			ok
		ok
	next
	Then("every one was believed by the port, fetched over the wire and verified by the engine's HMAC", nAccepted, len(aDel))
	aWant = [ "PAIEMENT_RECU", "PAIEMENT_ENVOYE", "PAIEMENT_REJETE", "RTP_RECU", "RTP_REJETE", "RTP_REPONSE_REJETE",
		"ANNULATION_DEMANDE", "ANNULATION_REPONSE_REJETE", "RETOUR_ENVOYE", "RETOUR_REJETE", "RETOUR_RECU", "ANNULATION_REJETE" ]
	nMissing = 0
	cMissing = ""
	for i = 1 to len(aWant)
		if ring_find(aSeen, aWant[i]) = 0
			nMissing++
			cMissing += aWant[i] + " "
		ok
	next
	Then("all twelve event codes of the reference arrived", nMissing, 0)
	if nMissing > 0
		? "    missing: " + cMissing
	ok
	Then("...twelve distinct", len(aSeen) >= 12, TRUE)
EndScenario()

Scenario("the platform's own webhook endpoint: 204 when believed, 401 when not, 400 when it is not an event")
	oAd = MkAdapter($nPortA, "piz/", [])
	oPay = UngovernedPort(oAd)
	aAl = Ctl($nPortA, "GET", "alias", [])
	oPay.RegisterWebhook( StzWebhookQ().CallingBack("https://diko.example/pispi2") )
	Ctl($nPortA, "GET", "deliveries", [])
	oPay.Pay( MkOrderA(aAl, "H-1", "fatou", 1000) )
	Ctl($nPortA, "POST", "advance", [ ["seconds", 25] ])
	aDel = pzVal(Ctl($nPortA, "GET", "deliveries", []), "data")
	cBody = ""
	cSig = ""
	for i = 1 to len(aDel)
		if pzVal(aDel[i], "callbackUrl") = "https://diko.example/pispi2"
			cBody = pzVal(aDel[i], "body")
			cSig = pzVal(aDel[i], "signature")
		ok
	next

	oSrv = new stzAppServer()
	StzPaymentsWebhookRoute(oSrv, "/pispi/webhook", oPay)

	Then("a signed, new event is answered 204", HandleWebhook(cBody, cSig), 204)
	Then("the same event again is answered 401: a replay", HandleWebhook(cBody, cSig), 401)
	Then("a forged signature is answered 401", HandleWebhook(cBody, "00ff00ff"), 401)
	Then("an unsigned event is answered 401", HandleWebhook(cBody, ""), 401)
	cSecret = ""
	cJunk = "not json"
	Then("a body altered in transit is answered 401", HandleWebhook(StzReplace(cBody, "1000", "9000"), cSig), 401)
	Then("the port believed exactly one event", len(oPay.Events()), 1)
EndScenario()

Scenario("a response lost after the request was sent: the txId is journaled, and a retry READS")
	oAd = MkAdapter($nPortA, "piz/", [])
	oPay = UngovernedPort(oAd)
	aAl = Ctl($nPortA, "GET", "alias", [])
	nB0 = pzVal(Ctl($nPortA, "GET", "state", []), "balance")
	oAd.DropNextResponse()
	oOrder = MkOrderA(aAl, "L-1", "fatou", 7000)
	bLost = FALSE
	cWhy = ""
	try
		oPay.Pay(oOrder)
	catch
		bLost = TRUE
		cWhy = cCatchError
	done
	Then("the platform is told the transport failed", bLost, TRUE)
	Then("...in the word the port recognises", StzFindFirst("stzPispiHttpAdapter transport", cWhy) > 0, TRUE)
	Then("the txId was journaled, because money may have moved", oPay.JournalSize(), 1)
	Then("...and it had", pzVal(Ctl($nPortA, "GET", "state", []), "balance"), nB0 - 7000)
	aRetry = oPay.Pay(oOrder)
	Then("a retry READS the payment instead of sending it", aRetry["replayed"], 1)
	Then("...and finds it, ENVOYE", aRetry["statut"], "ENVOYE")
	Then("...so the money left once", pzVal(Ctl($nPortA, "GET", "state", []), "balance"), nB0 - 7000)

	oAdDead = StzPispiHttpAdapterQ()
	oAdDead.WithParticipant("bia")
	oAdDead.WithBaseUrl("http://127.0.0.1:1/piz/v1")
	oAdDead.WithSecretsFrom(MkStore($cClientId, $cClientSecret, $cApiKey), HumanActor("tresorier"))
	bDead = FALSE
	try
		UngovernedPort(oAdDead).Accounts()
	catch
		bDead = TRUE
	done
	Then("a participant that cannot be reached is a transport failure, not a payment problem", bDead, TRUE)

	oHubL = StzPiSpiSandboxQ()
	oPortL = UngovernedPort(oHubL)
	oPortL._Remember("pay", "N-1", "")
	aN = oPortL.Pay( MkOrderLocal(oHubL, "N-1", "fatou", 1000) )
	Then("when the first attempt NEVER ARRIVED the hub says 404 and the retry sends it for real", aN["replayed"], 0)
	Then("...and the payment exists now", aN["statut"], "ENVOYE")
EndScenario()

Scenario("mutual TLS: the participant that requires a certificate")
	oStore = MkStore($cClientId, $cClientSecret, $cApiKey)
	oCert = StzPispiSecretQ("bia", "mtls-cert")
	oCert.FromFile($cNodeCrt)
	oCert.SetExpiry(StzEngineTimeNowMs() / 1000 + 365 * 86400)
	oStore.Register(oCert)
	oKeyD = StzPispiSecretQ("bia", "mtls-key")
	oKeyD.FromFile($cNodeKey)
	oStore.Register(oKeyD)

	oAd = StzPispiHttpAdapterQ()
	oAd.WithParticipant("bia")
	oAd.WithBaseUrl("https://127.0.0.1:" + $nPortB + "/piz/v1")
	oAd.WithScopePrefix("piz/")
	oAd.WithSecretsFrom(oStore, HumanActor("tresorier"))
	oAd.WithCertificateFrom(oStore)
	oAd.WithCaFile($cCACrt)
	oAd.AsLive()
	oPay = UngovernedPort(oAd)
	Then("a live adapter says it needs a certificate, and which", oPay.CertificateSecretName(), "pispi-bia-mtls-cert")
	aAcc = oPay.Accounts()
	Then("with the certificate, the token and the call both go over mutual TLS", len(aAcc), 2)
	Then("...and the contract answers as it does over plain HTTP", pzVal(pzNth(aAcc, 1), "numero"), "NE2344256727788288822")
	aS = oPay.Pay( MkOrderTls("T-1", "fatou", 12000) )
	Then("a payment over mutual TLS is ENVOYE", aS["statut"], "ENVOYE")

	oNoCert = StzPispiHttpAdapterQ()
	oNoCert.WithParticipant("bia")
	oNoCert.WithBaseUrl("https://127.0.0.1:" + $nPortB + "/piz/v1")
	oNoCert.WithScopePrefix("piz/")
	oNoCert.WithSecretsFrom(MkStore($cClientId, $cClientSecret, $cApiKey), HumanActor("tresorier"))
	oNoCert.WithCaFile($cCACrt)
	oNoCert.AsLive()
	bNoCert = FALSE
	cWhy = ""
	try
		UngovernedPort(oNoCert).Accounts()
	catch
		bNoCert = TRUE
		cWhy = cCatchError
	done
	Then("a client that presents no certificate is refused by the server", bNoCert, TRUE)
	Then("...and the adapter says what that looks like", StzFindFirst("client certificate", cWhy) > 0, TRUE)

	oWrong = StzPispiHttpAdapterQ()
	oWrong.WithParticipant("bia")
	oWrong.WithBaseUrl("https://127.0.0.1:" + $nPortB + "/piz/v1")
	oWrong.WithScopePrefix("piz/")
	oWrong.WithSecretsFrom(oStore, HumanActor("tresorier"))
	oWrong.WithCertificateFrom(oStore)
	oWrong.WithCaFile($cWrongCA)
	oWrong.AsLive()
	bWrong = FALSE
	cWhy2 = ""
	try
		UngovernedPort(oWrong).Accounts()
	catch
		bWrong = TRUE
		cWhy2 = cCatchError
	done
	Then("a client that does not trust the server's CA aborts the handshake", bWrong, TRUE)
	Then("...and the adapter says the TLS failed", StzFindFirst("TLS to", cWhy2) > 0, TRUE)

	When("the registry is asked about the live binding")
	oReg = StzServiceRegistryQ("diko")
	oReg.BindLive(:payments, oPay, "pispi-bia-client")
	Then("a live port whose certificate is in the store and valid is sound", oReg.IsSoundVia(oStore), TRUE)
	oBare = MkStore($cClientId, $cClientSecret, $cApiKey)
	Then("...and without the certificate descriptor the registry refuses it before the first call", oReg.IsSoundVia(oBare), FALSE)
	aF = oReg.FindingsVia(oBare)
	Then("...naming the invariant", StzFindFirst("live-without-certificate", @@(aF)) > 0, TRUE)

	oAdC = MkAdapter($nPortA, "piz/", [])
	oRegC = StzServiceRegistryQ("diko-c")
	oRegC.Bind(:payments, StzPaymentsPortQ(oAdC))
	Then("a conformance adapter bound without a word is read as conformance", oRegC.PostureOf(:payments), :conformance)
	oRegC.SetPhase(:production)
	Then("...and production refuses it", StzFindFirst("conformance-in-production", @@(oRegC.Findings())) > 0, TRUE)
EndScenario()

Scenario("the wire codec, on its own")
	Then("an empty array stays an array", StzPispiJson([ ["transactions", []], ["x", 1] ]), '{"transactions":[],"x":1}')
	Then("a one-pair array of objects stays an array of objects",
		StzPispiJson([ ["transactions", [ [ ["txId", "a"], ["montant", 1] ] ]] ]), '{"transactions":[{"txId":"a","montant":1}]}')
	Then("a list of strings is an array", StzPispiJson([ ["events", ["A", "B"]] ]), '{"events":["A","B"]}')
	Then("confirmation is a JSON boolean", StzPispiJson([ ["confirmation", 0], ["decision", 1] ]), '{"confirmation":false,"decision":true}')
	Then("a number that is not a boolean key stays a number", StzPispiJson([ ["montant", 0] ]), '{"montant":0}')
	Then("a quote and a backslash are escaped", StzPispiJson([ ["motif", 'say "hi" \ ok'] ]), '{"motif":"say \"hi\" \\ ok"}')
	Then("an empty body is no body", StzPispiJson([]), "")

	Then("a space and an ampersand are percent-encoded", _StzPiPctEncode("a b&c=d"), "a%20b%26c%3Dd")
	Then("the brackets of the reference's filters are not", _StzPiPctEncode("montant[gte]"), "montant[gte]")
	Then("decoding is the inverse", _StzPiPctDecode("a%20b%26c%3Dd"), "a b&c=d")
	cUtf = "caf" + char(195) + char(169) + " ?"
	Then("an accent survives the round trip", _StzPiPctDecode(_StzPiPctEncode(cUtf)), cUtf)

	cChunked = "5" + char(13) + char(10) + "hello" + char(13) + char(10) + "6" + char(13) + char(10) + " world" + char(13) + char(10) + "0" + char(13) + char(10) + char(13) + char(10)
	Then("a chunked body is decoded", _StzPiDechunk(cChunked), "hello world")
	cRaw = "HTTP/1.1 200 OK" + char(13) + char(10) + "Transfer-Encoding: chunked" + char(13) + char(10) + char(13) + char(10) + cChunked
	aP = _StzPiParseHttp(cRaw)
	Then("a chunked response is parsed: status", aP[1], 200)
	Then("...and its body", aP[3], "hello world")
	Then("a Content-Length response is parsed as it comes",
		pzNth(_StzPiParseHttp("HTTP/1.1 404 Not Found" + char(13) + char(10) + "Content-Length: 2" + char(13) + char(10) + char(13) + char(10) + "{}"), 1), 404)
	aU = _StzPiSplitUrl("https://api.example.ne:8443/piz/v1")
	Then("a URL splits into scheme", aU[1], "https")
	Then("...host", aU[2], "api.example.ne")
	Then("...port", aU[3], 8443)
	Then("...and path", aU[4], "/piz/v1")
	Then("https without a port is 443", pzNth(_StzPiSplitUrl("https://h/x"), 3), 443)
	Then("hex sizes parse", StzHexToNumber("1a"), 26)
EndScenario()

Scenario("stage (b) is UNPERCEIVED, and says so")
	cOut = StzSystem("ring payments_conformance_run.ring")
	Then("without DIKO's sandbox credentials the conformance run does not run", StzFindFirst("UNPERCEIVED", cOut) > 0, TRUE)
	Then("...it names what is missing, by variable", StzFindFirst("PISPI_CLIENT_SECRET", cOut) > 0, TRUE)
	Then("...it is not a failure and not a pass", StzFindFirst("STATUS: PASS", cOut), 0)
	Then("...and it prints no secret", StzFindFirst("secret=", StzLower(cOut)), 0)
EndScenario()

Scenario("teardown")
	$oSpawner.KillSpawnHard($nJobA)
	$oSpawnerB.KillSpawnHard($nJobB)
	Then("the server processes were told to stop", 1, 1)
EndScenario()

if fexists($cCertDir + "/.py5_front_plain.ring")  remove($cCertDir + "/.py5_front_plain.ring")  ok
if fexists($cCertDir + "/.py5_front_mtls.ring")   remove($cCertDir + "/.py5_front_mtls.ring")  ok
if fexists($cCertDir + "/.py5_front_plain.log")  remove($cCertDir + "/.py5_front_plain.log")  ok
if fexists($cCertDir + "/.py5_front_mtls.log")  remove($cCertDir + "/.py5_front_mtls.log")  ok
Summary()

# --- helpers (after Summary; Ring hoists func definitions) -------------------

func pzVal(aList, cKey)
	return _StzPiGet(aList, cKey, "")

func pzNth(aList, n)
	return aList[n]

func UngovernedPort(oBackend)
	oUg = StzPaymentsPortQ(oBackend)
	oUg.AllowUngovernedPayouts()
	return oUg

# a store with the platform's credentials for participant "bia", generated by this guard
func MkStore(cId, cSecret, cKey)
	oSt = StzSecretStoreQ("diko")
	oC = StzPispiSecretQ("bia", "client")
	oC.FromLiteral(cId + ":" + cSecret)
	oSt.Register(oC)
	oK = StzPispiSecretQ("bia", "api-key")
	oK.FromLiteral(cKey)
	oSt.Register(oK)
	return oSt

func MkAdapterWith(nPort, cPrefix, aScopes, cId, cSecret, cKey)
	oA = StzPispiHttpAdapterQ()
	oA.WithParticipant("bia")
	oA.WithBaseUrl("http://127.0.0.1:" + nPort + "/piz/v1")
	oA.WithScopePrefix(cPrefix)
	if len(aScopes) > 0
		oA.WithScopes(aScopes)
	ok
	oA.WithSecretsFrom(MkStore(cId, cSecret, cKey), HumanActor("tresorier"))
	oA.AsConformance()
	return oA

func MkAdapter(nPort, cPrefix, aScopes)
	return MkAdapterWith(nPort, cPrefix, aScopes, $cClientId, $cClientSecret, $cApiKey)

func MkOrderA(aAlias, cTx, cWho, nAmount)
	oO = StzPaymentOrderQ()
	oO.WithTxId(cTx)
	oO.FromAlias(pzVal(aAlias, "business"))
	oO.ToAlias(pzVal(aAlias, cWho))
	oO.WithAmount(StzAmountQ("" + nAmount, "XOF"))
	oO.WithoutConfirmation()
	return oO

# the control surface of the plain front: [ status ] body as a list
func Ctl(nPort, cMethod, cVerb, aBody)
	oH = new stzHttpClient()
	nM = $STZ_HTTP_METHOD_GET
	if cMethod = "POST"
		nM = $STZ_HTTP_METHOD_POST
	ok
	oH._Perform(nM, "http://127.0.0.1:" + nPort + "/_twin/" + cVerb, "application/json", StzPispiJson(aBody))
	cB = oH.ResponseBody()
	if cB = "" or NOT StzJsonIsValid(cB)
		return []
	ok
	return StzJsonToList(cB)

func SpawnFront(cMode, nPort)
	cScript = $cCertDir + "/.py5_front_" + cMode + ".ring"
	cEol = char(10)
	cLog = $cCertDir + "/.py5_front_" + cMode + ".log"
	if fexists(cLog)  remove(cLog)  ok
	cCode = 'try' + cEol + 'load "' + FrontBaseRing() + '"' + cEol +
		'oF = StzPiSpiHttpFrontQ()' + cEol +
		'oF.WithCredentials("' + $cClientId + '", "' + $cClientSecret + '", "' + $cApiKey + '")' + cEol +
		'oF.WithScopePrefix("piz/")' + cEol +
		'oF.EnableControl()' + cEol
	if cMode = "mtls"
		cCode += 'oF.StartTls(' + nPort + ', "127.0.0.1", "' + $cNodeCrt + '", "' + $cNodeKey + '", "' + $cCACrt + '", TRUE)' + cEol
	else
		cCode += 'oF.Start(' + nPort + ', "127.0.0.1")' + cEol
	ok
	cCode += 'write("' + cLog + '", "started")' + cEol + 'oF.RunFor(120000)' + cEol + 'oF.Stop()' + cEol +
		'catch' + cEol + 'write("' + cLog + '", "ERR " + cCatchError)' + cEol + 'done' + cEol
	write(cScript, cCode)
	if cMode = "mtls"
		return $oSpawnerB.SubmitSpawn([ FrontRingExe(), cScript ])
	ok
	return $oSpawner.SubmitSpawn([ FrontRingExe(), cScript ])

# A server announces itself by writing "started" to its log. It is NOT polled over HTTP: the engine's
# HTTP client ejects a host that refuses a few connections, and a poll of a server still loading
# would eject it for the whole run ("host ejected by outlier detector").
func WaitFront(cMode, nPort, nTimeoutMs)
	cLog = $cCertDir + "/.py5_front_" + cMode + ".log"
	nDeadline = StzEngineTimeNowMs() + nTimeoutMs
	while StzEngineTimeNowMs() < nDeadline
		if fexists(cLog)
			cSaid = read(cLog)
			if cSaid = "started"  return TRUE  ok
			if StzLeft(cSaid, 3) = "ERR"
				? "front " + cMode + " failed to start: " + cSaid
				return FALSE
			ok
		ok
		nJ = $oSpawner.SubmitTimer(300)
		$oSpawner.AwaitTimer(nJ, 600)
	end
	return FALSE

func FrontRingExe
	aA = sysargv
	nArgs = len(aA)
	for i = 1 to nArgs
		c = StzLower("" + aA[i])
		if StzFindFirst("ring.exe", c) > 0 or c = "ring"  return "" + aA[i]  ok
	next
	return "ring"

func FrontBaseRing
	nSlash = 0
	nChars = len($cEngineDir)
	for i = 1 to nChars
		if $cEngineDir[i] = "/"  nSlash = i  ok
	next
	return StzLeft($cEngineDir, nSlash - 1) + "/base/stzBase.ring"

# a request and a response, as the app server would hand them to the route's handler
func HandleWebhook(cBody, cSig)
	oReq = new stzAppRequest("POST", "/pispi/webhook", [ [ "X-Signature", cSig ] ], cBody)
	oResp = new stzAppResponse(0)
	StzPaymentsWebhookHandle(oReq, oResp)
	return oResp.StatusCode()

func MkOrderLocal(oHub, cTx, cWho, nAmount)
	oO = StzPaymentOrderQ()
	oO.WithTxId(cTx)
	oO.FromAlias(oHub.BusinessAlias())
	oO.ToAlias(oHub.Alias(cWho))
	oO.WithAmount(StzAmountQ("" + nAmount, "XOF"))
	oO.WithoutConfirmation()
	return oO

# the aliases of the twin behind the mutual-TLS front, over its control surface
func TlsAliases
	cRaw = $oGuardTls.TlsGet("127.0.0.1", $nPortB, "/_twin/alias", $cNodeCrt, $cNodeKey, $cCACrt, TRUE)
	aP = _StzPiParseHttp(cRaw)
	return StzJsonToList(aP[3])

func MkOrderTls(cTx, cWho, nAmount)
	return MkOrderA(TlsAliases(), cTx, cWho, nAmount)
