load "../../stzBase.ring"
load "../_narrated.ring"

# stzHashList defects from the doc register (DEFECTS.md, section stzHashList, 56 rows).
# Every scenario states what the method does AFTER the fix; a negative sibling sits beside
# each positive, so an answer that agrees by coincidence (an empty list, a 0) is caught.

Scenario("The class statistics on text values (IsStrictlyEqualTo was defined nowhere)")
	o = new stzHashList([ :a = "x", :b = "y", :c = "x", :d = 4 ])
	Then("Classes lists the distinct values as text", @@(o.Classes()), '[ "x", "y", "4" ]')
	Then("Classify groups the keys by value", @@(o.Classify()),
		'[ [ "x", [ "a", "c" ] ], [ "y", [ "b" ] ], [ "4", [ "d" ] ] ]')
	Then("Klass gives the keys of a class", @@(o.Klass("x")), '[ "a", "c" ]')
	Then("KlassQ gives them as a stzList", @@(o.KlassQ("x").Content()), '[ "a", "c" ]')
	Then("ClassifyQ wraps the classification", @@(o.ClassifyQ().Content()), @@(o.Classify()))
	Then("and a class that is absent gives none", @@(o.Klass("zz")), '[ ]')
	Then("a class matches the whole value, not a part of it", @@(o.Klass("")), '[ ]')
	Then("the class of a number answers by its written form", @@(o.Klass("4")), '[ "d" ]')
	Then("NumberOfValuesInClass counts its pairs", o.NumberOfValuesInClass("x"), 2)
	Then("and counts 0 for an absent class", o.NumberOfValuesInClass("zz"), 0)
	Then("ClassesSizes counts every class", @@(o.ClassesSizes()), '[ 2, 1, 1 ]')
	Then("KlassFreq is the share of one class", o.KlassFreq("x"), 0.5)
	Then("and 0 for an absent class", o.KlassFreq("zz"), 0)
	Then("ClassesFrequencies sums to 1", @@(o.ClassesFrequencies()), '[ 0.50, 0.25, 0.25 ]')
	Then("StrongestClass is the biggest", o.StrongestClass(), "x")
	Then("WeakestClass is not the biggest", o.WeakestClass() != "x", 1)
	Then("NStrongestClasses(1) starts with the biggest", o.NStrongestClasses(1)[1], "x")
	Then("NStrongestClasses gives n classes", len(o.NStrongestClasses(2)), 2)
	Then("NWeakestClasses puts the biggest last", o.NWeakestClasses(3)[3], "x")
	Then("Top3Classes starts with the biggest", o.Top3Classes()[1], "x")
	Then("Bottom3Classes ends with the biggest", o.Bottom3Classes()[3], "x")
EndScenario()

Scenario("The class statistics on list values count right")
	o = new stzHashList([ :a = [ 1, 2 ], :b = [ 3 ], :c = [ 1, 2 ] ])
	Then("a list class is written as its text form", @@(o.Classes()), '[ "[ 1, 2 ]", "[ 3 ]" ]')
	Then("Klass takes the list itself", @@(o.Klass([ 1, 2 ])), '[ "a", "c" ]')
	Then("or its written form, as Classes gives it", @@(o.Klass("[ 1, 2 ]")), '[ "a", "c" ]')
	Then("a list that is only part of a value is not its class", @@(o.Klass([ 1 ])), '[ ]')
	Then("ClassesSizes counts each list once per pair", @@(o.ClassesSizes()), '[ 2, 1 ]')
	Then("StrongestClass is the most frequent list", o.StrongestClass(), "[ 1, 2 ]")
	Then("WeakestClass is the least frequent", o.WeakestClass(), "[ 3 ]")
EndScenario()

Scenario("The 3-forms take no stray parameter")
	o = new stzHashList([ :a = "x", :b = "y", :c = "x", :d = "z", :e = "x", :f = "y" ])
	Then("Strongest3Classes is Top3Classes", @@(o.Strongest3Classes()), @@(o.Top3Classes()))
	Then("and starts with the biggest", o.Strongest3Classes()[1], "x")
	Then("Weakest3Classes is Bottom3Classes", @@(o.Weakest3Classes()), @@(o.Bottom3Classes()))
	Then("and starts with the smallest", o.Weakest3Classes()[1], "z")
	Then("Strongest3ClassesAndTheirFrequencies pairs a class with its share",
		@@(o.Strongest3ClassesAndTheirFrequencies()[1]), '[ "x", 0.50 ]')
	Then("Weakest3ClassesAndTheirFrequencies starts with the smallest share",
		o.Weakest3ClassesAndTheirFrequencies()[1][1], "z")
EndScenario()

Scenario("KlassInList finds the pairs whose list value holds an item")
	o = new stzHashList([ :a = [ 1, 2 ], :b = [ 3 ], :c = [ 2, 5 ] ])
	Then("KlassInList gives the keys", @@(o.KlassInList(2)), '[ "a", "c" ]')
	Then("and none for an absent item", @@(o.KlassInList(9)), '[ ]')
	Then("KalssInListQ gives them as a stzList", @@(o.KalssInListQ(2).Content()), '[ "a", "c" ]')
EndScenario()

Scenario("KeysForValue and KeysByValues")
	o = new stzHashList([ :a = "x", :b = "xy", :c = "x", :d = 4 ])
	Then("KeysForValue matches the whole value", @@(o.KeysForValue("x")), '[ "a", "c" ]')
	Then("and finds nothing for an absent value", @@(o.KeysForValue("q")), '[ ]')
	Then("a number value is found", @@(o.KeysForValue(4)), '[ "d" ]')
	Then("KeysByValues gathers the keys of several values, in order, a text found inside a longer one too", @@(o.KeysByValues([ 4, "x" ])),
		'[ "a", "b", "c", "d" ]')
	Then("KeysByValue finds a number value", @@(o.KeysByValue(4)), '[ "d" ]')
	Then("and not a number that differs", @@(o.KeysByValue(44)), '[ ]')
	Then("and none when no value occurs", @@(o.KeysByValues([ "q" ])), '[ ]')
EndScenario()

Scenario("The pair accessors")
	o = new stzHashList([ :a = "x", :b = "y", :c = 4 ])
	Then("FirstPair", @@(o.FirstPair()), '[ "a", "x" ]')
	Then("LastPair", @@(o.LastPair()), '[ "c", 4 ]')
	Then("KeyInPair gives the key of a real pair", o.KeyInPair([ "b", "y" ]), "b")
	Then("and raises for a pair that is not in the hash list", Raises('o.KeyInPair([ "b", "q" ])'), 1)
	Then("ValueInPair gives the value of a real pair", o.ValueInPair([ "b", "y" ]), "y")
	Then("and raises for a pair that is not in the hash list", Raises('o.ValueInPair([ "q", "y" ])'), 1)
	Then("ValueInNthPairQ wraps the value", o.ValueInNthPairQ(2).Content(), "y")
EndScenario()

Scenario("Finding typed values: a correctly typed argument is accepted")
	o = new stzHashList([ :a = "x", :b = 4, :c = "x", :d = 7, :e = 4 ])
	Then("FindNumber", @@(o.FindNumber(4)), '[ 2, 5 ]')
	Then("FindNumber of an absent number", @@(o.FindNumber(9)), '[ ]')
	Then("and a text argument is refused", Raises('o.FindNumber("4")'), 1)
	Then("NumberZ", @@(o.NumberZ(7)), '[ 7, [ 4 ] ]')
	Then("FindTheseNumbers", @@(o.FindTheseNumbers([ 7, 4 ])), '[ 2, 4, 5 ]')
	Then("and refuses a list holding text", Raises('o.FindTheseNumbers([ 7, "x" ])'), 1)
	Then("TheseNumbersZ", @@(o.TheseNumbersZ([ 7, 4 ])), '[ [ 7, [ 4 ] ], [ 4, [ 2, 5 ] ] ]')
	Then("FindString", @@(o.FindString("x")), '[ 1, 3 ]')
	Then("and a number argument is refused", Raises('o.FindString(4)'), 1)
	Then("StringZ", @@(o.StringZ("x")), '[ "x", [ 1, 3 ] ]')
	Then("FindTheseStrings", @@(o.FindTheseStrings([ "x" ])), '[ 1, 3 ]')
	Then("and refuses a list holding a number", Raises('o.FindTheseStrings([ "x", 4 ])'), 1)
	Then("TheseStringsZ", @@(o.TheseStringsZ([ "x" ])), '[ [ "x", [ 1, 3 ] ] ]')
	Then("FindLastOccurrenceOfValue", o.FindLastOccurrenceOfValue(4), 5)
	Then("and 0 for an absent value", o.FindLastOccurrenceOfValue(9), 0)
	Then("ContainsTheseValues when all occur", o.ContainsTheseValues([ "x", 7 ]), 1)
	Then("and not when one is absent", o.ContainsTheseValues([ "x", 9 ]), 0)
EndScenario()

Scenario("Updating values and keys")
	o = new stzHashList([ :a = "x", :b = "y", :c = "x", :d = "x" ])
	o.UpdateNthOccurrenceOfValue(2, "x", "N")
	Then("UpdateNthOccurrenceOfValue changes only the nth", @@(o.Values()), '[ "x", "y", "N", "x" ]')
	o.UpdateNthOccurrenceOfValue(5, "x", "Q")
	Then("and nothing when there are fewer occurrences", @@(o.Values()), '[ "x", "y", "N", "x" ]')
	o.UpdateFirstOccurrenceOfValue("x", "F")
	Then("UpdateFirstOccurrenceOfValue", @@(o.Values()), '[ "F", "y", "N", "x" ]')
	o.UpdateFirstValue("y", "G")
	Then("UpdateFirstValue", @@(o.Values()), '[ "F", "G", "N", "x" ]')
	o = new stzHashList([ :a = "x", :b = "y", :c = "x" ])
	o.UpdateLastValue("x", "L")
	Then("UpdateLastValue changes the last occurrence", @@(o.Values()), '[ "x", "y", "L" ]')
	o = new stzHashList([ :a = 1, :b = 2 ])
	o.UpdateKeys([ "b", "a" ])
	Then("UpdateKeys renames in order, a swap included", @@(o.Content()), '[ [ "b", 1 ], [ "a", 2 ] ]')
	Then("and refuses keys that are not text", Raises('o.UpdateKeys([ 1, 2 ])'), 1)
	o = new stzHashList([ :a = 1 ])
	o.UpdateAllPairsWith([ "z", 9 ])
	Then("UpdateAllPairsWith on a one-pair hash list", @@(o.Content()), '[ [ "z", 9 ] ]')
	o = new stzHashList([ :a = 1, :b = 2 ])
	Then("and raises when keys would repeat", Raises('o.UpdateAllPairsWith([ "z", 9 ])'), 1)
	Then("leaving the hash list as it was", @@(o.Content()), '[ [ "a", 1 ], [ "b", 2 ] ]')
EndScenario()

Scenario("Reversing keys and values")
	o = new stzHashList([ :a = "x", :b = 2 ])
	o.ReverseKeysAndValues()
	Then("the values become the keys", @@(o.Content()), '[ [ "x", "a" ], [ "2", "b" ] ]')
	o = new stzHashList([ :a = "x", :b = "x" ])
	Then("repeated values raise, as keys must stay distinct", Raises('o.ReverseKeysAndValues()'), 1)
	o = new stzHashList([ :a = [ 1 ] ])
	Then("a list value raises", Raises('o.ReverseKeysAndValues()'), 1)
EndScenario()

Scenario("Inserting and removing pairs")
	o = new stzHashList([ :a = 1, :c = 3 ])
	o.InsertBefore(2, [ "b", 2 ])
	Then("InsertBefore", @@(o.Keys()), '[ "a", "b", "c" ]')
	o.InsertBefore(1, [ "z", 0 ])
	Then("InsertBefore 1 puts the pair first", @@(o.Keys()), '[ "z", "a", "b", "c" ]')
	o.InsertAfter(4, [ "d", 4 ])
	Then("InsertAfter the last", @@(o.Keys()), '[ "z", "a", "b", "c", "d" ]')
	o.InsertAfter(9, [ "q", 4 ])
	Then("and nothing past the end", len(o.Keys()), 5)
	Then("the inserted pair can be found by its key", o.ValueByKey("d"), 4)
	o.RemovePair([ "a", 1 ])
	Then("RemovePair", @@(o.Keys()), '[ "z", "b", "c", "d" ]')
	o.RemovePair([ "b", 99 ])
	Then("and a pair with another value stays", @@(o.Keys()), '[ "z", "b", "c", "d" ]')
	o.RemovePairsByKeys([ "z", "c" ])
	Then("RemovePairsByKeys", @@(o.Keys()), '[ "b", "d" ]')
	Then("and refuses keys that are not text", Raises('o.RemovePairsByKeys([ 1 ])'), 1)
EndScenario()

Scenario("Replacing values and pairs")
	o = new stzHashList([ :a = "x", :b = "y", :c = "x" ])
	o.ReplaceValue("x", "N")
	Then("ReplaceValue changes the first occurrence", @@(o.Values()), '[ "N", "y", "x" ]')
	o.ReplaceValue("q", "Q")
	Then("and nothing for an absent value", @@(o.Values()), '[ "N", "y", "x" ]')
	o.ReplacePair([ "b", "y" ], [ "bb", "yy" ])
	Then("ReplacePair", @@(o.Content()), '[ [ "a", "N" ], [ "bb", "yy" ], [ "c", "x" ] ]')
	o.ReplacePair([ "q", "y" ], [ "r", "r" ])
	Then("and nothing for an absent pair", len(o.Content()), 3)
	o.ReplacePairByKey("c", [ "cc", 3 ])
	Then("ReplacePairByKey", @@(o.LastPair()), '[ "cc", 3 ]')
	Then("ReplacePairsW is reserved and says so", Raises('o.ReplacePairsW("true")'), 1)
EndScenario()

Scenario("Items inside list values")
	o = new stzHashList([ :a = [ 1, 2 ], :b = [ 3 ], :c = [ 2, 2 ] ])
	Then("FindLastItem", @@(o.FindLastItem(2)), @@(o.FindItem(2)[2]))
	Then("and 0 for an absent item", o.FindLastItem(9), 0)
	Then("FindFirstKeyByItemInList", o.FindFirstKeyByItemInList(2), 1)
	Then("FindLastKeyByItemInList", o.FindLastKeyByItemInList(2), 3)
	Then("and 0 for an absent item", o.FindLastKeyByItemInList(9), 0)
	Then("KeyByItemInList", o.KeyByItemInList(3), "b")
	Then("and empty text for an absent item", o.KeyByItemInList(9), "")
	Then("KeysByItemInList", @@(o.KeysByItemInList(2)), '[ "a", "c" ]')
	Then("KeysByItem is the same", @@(o.KeysByItem(2)), '[ "a", "c" ]')
	Then("and none for an absent item", @@(o.KeysByItem(9)), '[ ]')
EndScenario()

Summary()

func Raises(cCode)
	# Runs cCode with a hash list named o in scope; TRUE when it raises.
	try
		eval(cCode)
	catch
		return 1
	done
	return 0
