load "../../stzBase.ring"
load "../_narrated.ring"

# stzNumber defects that DOCREFORM probing found while the doc blocks were written.
# Every scenario states what the method does AFTER the fix.

Scenario("RoundUp and RoundDown go to the whole number above and below")
	o = new stzNumber(3.14159)
	Then("RoundUp goes up (it used to take the floor, then raise R24)", o.RoundUp(), "4")
	Then("RoundDown goes down", o.RoundDown(), "3")
	o = new stzNumber(-2.5)
	Then("RoundUp of a negative goes toward zero", o.RoundUp(), "-2")
	Then("RoundDown of a negative goes away from zero", o.RoundDown(), "-3")
	o = new stzNumber(7)
	Then("a whole number stays", o.RoundUp() + "-" + o.RoundDown(), "7-7")
EndScenario()

Scenario("The tangent family answers")
	o = new stzNumber(1)
	Then("ArcTangent of 1 is pi/4", o.ArcTangent(), "0.79")
	Then("ArcTangent2 takes the x side as its argument", o.ArcTangent2(1), "0.79")
	Then("ArcTangent2 of y = 1 and x = -1 is 3pi/4", o.ArcTangent2(-1), "2.36")
	Then("HyperbolicTangent of 1", o.HyperbolicTangent(), "0.76")
	o = new stzNumber(0)
	Then("and of 0 is 0", o.HyperbolicTangent(), "0")
EndScenario()

Scenario("Derivative gives the exact slope of a function of x at the number")
	o = new stzNumber(3)
	Then("x^2 at 3", o.Derivative("x^2"), "6")
	Then("x^3 at 3", o.Derivative("x^3"), "27")
	Then("a polynomial", o.Derivative("x^2 + 3*x"), "9")
	o = new stzNumber(0.5)
	Then("cos(0.5) comes back with the number's two decimals", o.Derivative("sin(x)"), "0.88")
EndScenario()

Scenario("IsQuietEqualTo compares within the quiet ratio")
	o = new stzNumber(3.14159)
	Then("equal to itself", o.IsQuietEqualTo(3.14159), 1)
	Then("equal to the same number written as text", o.IsQuietEqualTo("3.14159"), 1)
	Then("not equal to a distant one", o.IsQuietEqualTo(3.5), 0)
EndScenario()

Scenario("Incremented and Decremented answer the number plus and minus 1")
	o = new stzNumber(12)
	Then("Incremented", o.Incremented(), "13")
	Then("Decremented", o.Decremented(), "11")
	Then("the number itself is unchanged", o.Content(), 12)
EndScenario()

Scenario("Stringify answers the number as text")
	o = new stzNumber(12)
	Then("Stringify", o.Stringify(), "12")
	Then("DeepStringifiy is the same answer", o.DeepStringifiy(), "12")
EndScenario()

Scenario("The space and zero removers do not raise")
	o = new stzNumber("12.5")
	o.RemoveLeadingSpaces()
	Then("a number holds no spaces, so nothing leads: unchanged", o.Content(), "12.5")
	o.RemoveTrailingSpaces()
	Then("and nothing trails: unchanged", o.Content(), "12.5")
	Then("LeadingSpacesRemoved answers the written number", o.LeadingSpacesRemoved(), "12.5")
	Then("TrailingSpacesRemoved answers the written number", o.TrailingSpacesRemoved(), "12.5")
	o = new stzNumber("007.500")
	Then("ZerosRemoved drops the zeros at both ends", o.ZerosRemoved(), "7.5")
	Then("and leaves the number as written", o.Content(), "007.500")
EndScenario()

Scenario("isWeiferich and ToBytes answer")
	o = new stzNumber(1093)
	Then("1093 is a Wieferich prime", o.isWeiferich(0), 1)
	o = new stzNumber(7)
	Then("7 is not", o.isWeiferich(0), 0)
	o = new stzNumber(3.5)
	Then("ToBytes is the 8 bytes of a double", len(o.ToBytes()), 8)
EndScenario()

Summary()
