load "../../stzBase.ring"
load "../_narrated.ring"

# stzString defects that DOCREFORM probing found while the doc blocks were written.
# Every scenario states what the method does AFTER the fix.

Scenario("IsIncludedIn asks whether THIS string is inside the argument")
	o = new stzString("banana")
	Then("inside a longer string", o.IsIncludedIn("bananas"), 1)
	Then("inside itself", o.IsIncludedIn("banana"), 1)
	Then("not inside a shorter one (it used to answer TRUE for 'an')", o.IsIncludedIn("an"), 0)
	Then("not inside an unrelated one", o.IsIncludedIn("xyz"), 0)
	Then("a non-string is never a host", o.IsIncludedIn(5), 0)
EndScenario()

Scenario("Move puts the char AT the second position")
	o = new stzString("banana")
	o.Move(1, 3)
	Then("forward: the b lands third", o.Content(), "anbana")
	o = new stzString("banana")
	o.Move(3, 1)
	Then("backward: the n lands first", o.Content(), "nbaana")
	o = new stzString("banana")
	o.Move(2, 6)
	Then("to the end", o.Content(), "bnanaa")
	o = new stzString("banana")
	o.Move(6, 5)
	Then("one step back", o.Content(), "banaan")
	o = new stzString("ACB")
	o.Move(:CharFromPosition = 3, :To = 2)
	Then("the named form agrees", o.Content(), "ABC")
	o = new stzString("banana")
	o.Move(2, 2)
	Then("the same position changes nothing", o.Content(), "banana")
EndScenario()

Scenario("LeadingCharIs and TrailingCharIs compare the first and last char")
	o = new stzString("banana")
	Then("first char is b", o.LeadingCharIs("b"), 1)
	Then("first char is not a", o.LeadingCharIs("a"), 0)
	Then("last char is a", o.TrailingCharIs("a"), 1)
	Then("last char is not n", o.TrailingCharIs("n"), 0)
	o = new stzString("0000")
	Then("a run still counts", o.TrailingCharIs("0"), 1)
	o = new stzString("")
	Then("an empty string has neither", o.LeadingCharIs("a") + o.TrailingCharIs("a"), 0)
EndScenario()

Scenario("RemoveBlankLines drops the lines that hold nothing")
	o = new stzString("a" + char(10) + char(10) + "b" + char(10) + "  " + char(10) + "c")
	o.RemoveBlankLines()
	Then("only the text lines stay", o.Content(), "a" + char(10) + "b" + char(10) + "c")
EndScenario()

Scenario("SplitAroundCS_named splits with a case rule")
	o = new stzString("a-b-A-c")
	Then("the dashes are cut out", @@(o.SplitAroundCS_named("-", 1)), '[ "a", "b", "A", "c" ]')
	Then("with case: only the lower a matches", @@(o.SplitAroundCS_named("a", 1)), '[ "", "-b-A-c" ]')
	Then("without case: both a and A match", @@(o.SplitAroundCS_named("a", 0)), '[ "", "-b-", "-c" ]')
	Then("the named :CS form agrees", @@(o.SplitAroundCS_named("a", [ :CS, 0 ])), '[ "", "-b-", "-c" ]')
	Then("SplitAroundCS honours the rule itself", @@(o.SplitAroundCS("A", 0)), '[ "", "-b-", "-c" ]')
	Then("and SplitAround is case sensitive", @@(o.SplitAround("A")), '[ "a-b-", "-c" ]')
EndScenario()

Scenario("SplitToPartsOfNCharsXTOpt takes the one argument it documents")
	o = new stzString("abcdefgh")
	Then("a number of chars keeps the short last part", @@(o.SplitToPartsOfNCharsXTOpt(3)), '[ "abc", "def", "gh" ]')
	Then("a list that starts with it works too", @@(o.SplitToPartsOfNCharsXTOpt([ 3, :KeepRemainder ])), '[ "abc", "def", "gh" ]')
EndScenario()

Scenario("RemoveDuplicates keeps the first of each repeated char")
	o = new stzString("banana")
	o.RemoveDuplicates()
	Then("banana becomes ban", o.Content(), "ban")
	o = new stzString("Banana")
	o.RemoveDuplicatesCS(0)
	Then("the case rule is honoured", o.Content(), "Ban")
	o = new stzString("abc")
	o.RemoveDuplicates()
	Then("a text without repeats is unchanged", o.Content(), "abc")
EndScenario()

Summary()
