load "../../stzBase.ring"
load "../_narrated.ring"

# DOCREFORM wave 0 -- the stzList defects that probing found while the doc blocks were written
# (each was a method that raised or did nothing). Every scenario states what the method does AFTER the fix.

Scenario("The Split mutators change the list (they used to split a copy and drop it)")
	o = new stzList([ 1, 2, 3, 4, 5, 6 ])
	o.SplitAtPosition(3)
	Then("SplitAtPosition cuts before the position", @@(o.Content()), "[ [ 1, 2 ], [ 3, 4, 5, 6 ] ]")
	o = new stzList([ 1, 2, 3, 4, 5, 6 ])
	o.SplitBeforePosition(3)
	Then("SplitBeforePosition", @@(o.Content()), "[ [ 1, 2 ], [ 3, 4, 5, 6 ] ]")
	o = new stzList([ 1, 2, 3, 4, 5, 6 ])
	o.SplitAfterPosition(3)
	Then("SplitAfterPosition cuts after the position", @@(o.Content()), "[ [ 1, 2, 3 ], [ 4, 5, 6 ] ]")
	o = new stzList([ 1, 2, 3, 4, 5, 6 ])
	o.SplitToNParts(3)
	Then("SplitToNParts makes n parts", @@(o.Content()), "[ [ 1, 2 ], [ 3, 4 ], [ 5, 6 ] ]")
	o = new stzList([ 3, 1, 4, 1, 5, 9, 2, 6 ])
	o.SplitAtPacer(3, 1)
	Then("SplitAtPacer cuts every 3 items", @@(o.Content()), "[ [ 3, 1, 4 ], [ 1, 5, 9 ], [ 2, 6 ] ]")
	o = new stzList([ "a", "b", "c", "d" ])
	o.SplitCS("c", 1)
	Then("SplitCS cuts before the item", @@(o.Content()), '[ [ "a", "b" ], [ "c", "d" ] ]')
	o = new stzList([ 1, 2, 3, 4 ])
	Then("the passive forms still return and do not change", @@(o.SplittedAtPosition(2)), "[ [ 1 ], [ 2, 3, 4 ] ]")
	Then("and leave the list as it was", @@(o.Content()), "[ 1, 2, 3, 4 ]")
EndScenario()

Scenario("Insert puts the item before the position, as InsertBefore does")
	o = new stzList([ "a", "b", "c" ])
	o.Insert("Y", 2)
	Then("at 2", @@(o.Content()), '[ "a", "Y", "b", "c" ]')
	o = new stzList([ "a", "b", "c" ])
	o.Insert("Y", 1)
	Then("at 1 (it used to raise)", @@(o.Content()), '[ "Y", "a", "b", "c" ]')
	o = new stzList([ "a", "b", "c" ])
	o.Insert("Y", 4)
	Then("one past the end appends (it used to raise)", @@(o.Content()), '[ "a", "b", "c", "Y" ]')
	o = new stzList([ "a", "b", "c" ])
	o.Insert("Y", [ :After, 3 ])
	Then("after the last position appends", @@(o.Content()), '[ "a", "b", "c", "Y" ]')
	o = new stzList([ "a", "b", "c" ])
	o.Insert("Y", [ :After, 1 ])
	Then("after position 1 puts the item at 2", @@(o.Content()), '[ "a", "Y", "b", "c" ]')
	o = new stzList([ "a", "b", "c" ])
	o.InsertBefore(2, "Y")
	Then("InsertBefore is unchanged", @@(o.Content()), '[ "a", "Y", "b", "c" ]')
EndScenario()

Scenario("Extractors return what they removed")
	o = new stzList([ 3, 1, 4, 1, 5 ])
	Then("ExtractDuplicates returns the removed repeats", @@(o.ExtractDuplicates()), "[ 1 ]")
	Then("and the list keeps one of each", @@(o.Content()), "[ 3, 1, 4, 5 ]")
	o = new stzList([ 3, 1, 4, 1, 5 ])
	Then("ExtractFirstOccurrence returns the item", o.ExtractFirstOccurrence(1), 1)
	Then("and removes the first occurrence", @@(o.Content()), "[ 3, 4, 1, 5 ]")
	o = new stzList([ 3, 1, 4, 1, 5 ])
	Then("ExtractLastOccurrence returns the item", o.ExtractLastOccurrence(1), 1)
	Then("and removes the last occurrence", @@(o.Content()), "[ 3, 1, 4, 5 ]")
EndScenario()

Scenario("The repeated leading and trailing run")
	oX = new stzList([ "x", "x", "y" ])
	Then("RepeatedLeadingItem is the item of the run", oX.RepeatedLeadingItem(), "x")
	oY = new stzList([ "x", "y" ])
	Then("RepeatedLeadingItem is empty when there is no run", oY.RepeatedLeadingItem(), "")
	oB = new stzList([ "a", "b", "b" ])
	Then("RepeatedTrailingItem is the item of the run", oB.RepeatedTrailingItem(), "b")
	oT = new stzList([ "a", "b", "b", "b" ])
	Then("NumberOfRepeatedTrailingItems is the length of the run", oT.NumberOfRepeatedTrailingItems(), 3)
	Then("NumberOfRepeatedLeadingItems agrees on the other side", oX.NumberOfRepeatedLeadingItems(), 2)
EndScenario()

Scenario("AntiSection returns the runs outside a section")
	o6 = new stzList([ 1, 2, 3, 4, 5, 6 ])
	Then("outside 2..3 of 1..6", @@(o6.AntiSection(2, 3)), "[ [ 1 ], [ 4, 5, 6 ] ]")
	Then("FindAntiSection is unchanged", @@(o6.FindAntiSection(2, 3)), "[ [ 1, 1 ], [ 4, 6 ] ]")
EndScenario()

Summary()
