
# Propose examples showing realword applications of randomness:
#	- Generating unique passwords
#	- Randomizing data
#	- Monte Carlo simulations
#	- Randomizing game mechanics
#	- etc

# General functions

SeedRandom(n)
StzRandom()
StzRandom(nMin, nMax)
StzRandomIB(nMin, nMax)
NRandomNumbers(n, nMin, nMax)
NRandomNumbersIB(n, nMin, nMax)
3RandomNumbers(nMin, nMax)
3RandomNumbersIB(nMin, nMax)
RandomNumberLessThan(n)
RandomNumberGreaterThan(n)
NRandomNumbersGreaterThan(n, nValue)
3RandomNumbersGreaterThan(n)
NRandomNumbersLessThan(n, nValue)
3RandomNumbersLessThan(nValue)
RandomNumberOtherThan(n)

NRandomNumbersIn(n, panNumbers)
NRandomNumbersInZ(n, panNumbers)

NRandomNumbersInU(n, panNumbers)
NRandomNumbersInUZ(n, panNumbers)

#-- stzListOfNumbers

ARandomNumber()
ARandomNumberZ()
ANumberLessThan(nNumber)
ANumberLessThanZ(nNumber)
ANumberGreaterThan(nNumber)
ANumberGreaterThanZ(nNumber)
AnyNumberBeforeOrAfter(n)
AnyNumberBeforeOrAfterZ(n)
AnyNumberBefore(n)
AnyNumberBeforeZ(n)
AnyNumberBeforePosition(n)
AnyNumberBeforePositionZ(n)
AnyNumberAfter(n)
AnyNumberAfterZ(n)
AnyNumberAfterPosition(n)
AnyNumberAfterPositionZ(n)
AnyNumberBetween(n1, n2)
AnyNumberBetweenZ(n1, n2)
AnyNumberBetweenIB(n1, n2)
AnyNumberBetweenIBZ(n1, n2)
AnyNumberNotBetween(n1, n2)
AnyNumberNotBetweenZ(n1, n2)
AnyNumberNotBetweenIB(n1, n2)
AnyNumberNotBetweenIBZ(n1, n2)
AnyNumberBetweenPositions(n1, n2)
AnyNumberBetweenPositionsZ(n1, n2)
AnyNumberNotBetweenPositions(n1, n2)
AnyNumberNotBetweenPositionsZ(n1, n2)
AnyNumberOutsidePosition(n)
ANumberOtherThan(n)
NRandomNumbers(n)
NRandomNumbersZ(n)
NNumbersOtherThan(n, nNumber)
NNumbersOtherThanZ(n, nNumber)
NNumbersLessThan(n, nNumber)
NNumbersLessThanZ(n, nNumber)
NNumbersGreaterThan(n, nNumber)
NNumbersGreaterThanZ(n, nNumber)
NNumbersOtherThanMany(n, anNumbers)
NNumbersOtherThanManyZ(n, anNumbers)
NNumbersBetween(n, nMin, nMax)
NNumbersBetweenZ(n, nMin, nMax)

# StzList

ARandomItem()
ARandomItemZ()
NRandomItemsCS(pCaseSensitive)
NRandomItemsCSZ(pCaseSensitive)
SomeRandomItemsCS(pCaseSensitive)
SomeRandomItemsCSZ(pCaseSensitive)
AnItemOtherThanCS(pItem, pCaseSensitive)
AnItemOtherThanCSZ(pItem, pCaseSensitive)
AnItemOtherThanZ(pItem)
AnyRandomItemOtherThanManyCS(paItems, pCaseSensitive)
AnyRandomItemOtherThanMany(paItems)
AnyRandomItemOtherThanManyCSZ(paItems, pCaseSensitive)
AnyRandomItemOtherThanManyZ(paItems)
NRandomItemsOtherThanCS(pItem)
NRandomItemsOtherThanCSZ(pItem)
SomeRandomItemsOtherThanCS(pItem)
SomeRandomItemsOtherThanCSZ(pItem)
NRandomItemsOtherThanManyCS(pItem)
NRandomItemsOtherThanManyCSZ(pItem)
SomeRandomItemsOtherThanManyCS(pItem)
SomeRandomItemsOtherThanManyCSZ(pItem)
AnItemBetweenCS(pMin, pMax, pCaseSensitive) # InSection
AnItemBetweenCSZ(pMin, pMax, pCaseSensitive)
AnItemBetweenIBCS(pMin, pMax, pCaseSensitive)
AnItemBetweenIBCSZ(pMin, pMax, pCaseSensitive)
AnItemNotBetweenCS(pMin, pMax, pCaseSensitive) # OutsideInSection
AnItemNotBetweenCSZ(pMin, pMax, pCaseSensitive)
AnItemNotBetweenIBCS(pMin, pMax, pCaseSensitive)
AnItemNotBetweenIBCSZ(pMin, pMax, pCaseSensitive)
AnItemBetweenManyCS(pMin, pMax, pCaseSensitive) # InSections
AnItemBetweenManyCSZ(pMin, pMax, pCaseSensitive)
AnItemBetweenManyIBCS(pMin, pMax, pCaseSensitive)
AnItemBetweenManyIBCSZ(pMin, pMax, pCaseSensitive)
AnItemNotBetweenManyCS(pMin, pMax, pCaseSensitive) # OutsideSections
AnItemNotBetweenManyCSZ(pMin, pMax, pCaseSensitive)
AnItemNotBetweenManyIBCS(pMin, pMax, pCaseSensitive)
AnItemNotBetweenManyIBCSZ(pMin, pMax, pCaseSensitive)
NItemsBetweenCS(pMin, pMax, pCaseSensitive) # InSection
NItemsBetweenCSZ(pMin, pMax, pCaseSensitive)
NItemsBetweenIBCS(pMin, pMax, pCaseSensitive)
NItemsBetweenIBCSZ(pMin, pMax, pCaseSensitive)
SomeItemsBetweenCS(pMin, pMax, pCaseSensitive)
SomeItemsBetweenCSZ(pMin, pMax, pCaseSensitive)
SomeItemsBetweenIBCS(pMin, pMax, pCaseSensitive)
SomeItemsBetweenIBCSZ(pMin, pMax, pCaseSensitive)
NItemsNotBetweenCS(pMin, pMax, pCaseSensitive) # OutsideSection
NItemsNotBetweenCSZ(pMin, pMax, pCaseSensitive)
NItemsNotBetweenIBCS(pMin, pMax, pCaseSensitive)
NItemsNotBetweenIBCSZ(pMin, pMax, pCaseSensitive)
SomeItemsNotBetweenCS(pMin, pMax, pCaseSensitive)
SomeItemsNotBetweenCSZ(pMin, pMax, pCaseSensitive)
SomeItemsNotBetweenIBCS(pMin, pMax, pCaseSensitive)
SomeItemsNotBetweenIBCSZ(pMin, pMax, pCaseSensitive)
NItemsBetweenManyCS(pMin, pMax, pCaseSensitive) # InSections
NItemsBetweenManyCSZ(pMin, pMax, pCaseSensitive)
NItemsBetweenManyIBCS(pMin, pMax, pCaseSensitive)
NItemsBetweenManyIBCSZ(pMin, pMax, pCaseSensitive)
SomeItemsBetweenManyCS(pMin, pMax, pCaseSensitive) # InSections
SomeItemsBetweenManyCSZ(pMin, pMax, pCaseSensitive)
SomeItemsBetweenManyIBCS(pMin, pMax, pCaseSensitivity)
SomeItemsBetweenManyIBCSZ(pMin, pMax, pCaseSensitivity)
NItemsNotBetweenMayCS(pMin, pMax, pCaseSensitive) # NotInSections
NItemsNotBetweenMayCSZ(pMin, pMax, pCaseSensitive)
NItemsNotBetweenManyIBCS(pMin, pMax, pCaseSensitive)
NItemsNotBetweenManyIBCSZ(pMin, pMax, pCaseSensitive)
SomeItemsNotBetweenManyCS(pMin, pMax, pCaseSensitive) # NotInSections
SomeItemsNotBetweenManyCSZ(pMin, pMax, pCaseSensitive)
SomeItemsNotBetweenManyIBCS(pMin, pMax, pCaseSensitive)
SomeItemsNotBetweenManyIBCSZ(pMin, pMax, pCaseSensitive)
AnItemOutsidePosition(nPos)
AnItemOutsidePositionZ(nPos)
AnItemOutsidePositions(panPos)
AnItemOutsidePositionsZ(panPos)
NItemsOutsidePosition(anPos)
NItemsOutsidePositionZ(anPos)
SomeItemsOutsidePosition(anPos)
SomeItemsOutsidePositionZ(anPos)
NItemsOutsidePositions(panPos, pCaseSensitive)
NItemsOutsidePositionsZ(panPos, pCaseSensitive)
SomeItemsOutsidePositions(panPos, pCaseSensitive)
SomeItemsOutsidePositionsZ(panPos, pCaseSensitive)
Randomize()
RandomizeSection(n1, n2)
RandomizeSections(panSections)
RandomizeBetweenCS(p1, p2, pCaseSensitive)
RandomizeBetweenItemsCS(p1, p2, pCaseSensitive)
RandomizeNotBetweenCS(p1, p2, pCaseSensitive)
RandomizeNotBetweenItemsCS(p1, p2, pCaseSensitive)
RandomizeAntiSection(n1, n2)
RandomizeAntiSections(panSections)

