load "stzlib.ring"


#----- MISC. -----
/*
o1 = new stzListOfStrings([ "ring", "programming", "languag" ])
? o1.ConcatenatedUsing(" ") #--> ring programming languag

o1 = new stzListOfStrings([ ])
? @@( o1.ConcatenatedUsing(" ") ) #--> ""

#--------

o1 = new stzListOfStrings([ "aa", "  ", "b", "     ", "ccc" ])
o1.RemoveBlankSpacesStrings()
? o1.Content()

#--------

? SectionToRange([3, 7]) #--> [ 3, 4 ]
? RangeToSection([3, 4]) #--> [ 3, 7 ]

/*-----------------
*/

o1 = new stzString("AAA;;bbB;  ;Ccc;;Ddd;EEe")
? o1.SplitXT(";", [
	:CS = FALSE, :StartAt = 1, :EndAt = :LastChar, :MaxNumberOfParts = :All,

	:IgnoreFirstSep = False, :IgnoreLastSep = FALSE,

	//:PerformOnEachCharW = NULL
	:PerformOnEachCharW = [ '@char = Q(@char).Uppercased()', :If = 'Q(@char).IsLowercase()' ],

	:removeemptyparts = true, :removeblankspaceparts = true,

	#--

	:removefirstsplittedpart = true, :removelastsplittedpart = true//,
/*	:removethesesplittedparts = [1, 3],

	:RemoveTheseLeadingSubstringsInEachPart = [""],
	:RemoveTheseTrailingSubstringsInEachPart = [""],

	:RemoveLeadingCharsInEachPart = true,
	:RemoveTrailingCharsInEachPart = false,

	:RemoveThisLeadingCharInEachPart = "",
	:RemoveThisTrailingCharInEachPart = "",

	:RemoveNLeadingCharsInEachPart = 0 ,
	:RemoveNTrailingCharsInEachPart = 0,
			
	:PerformOnEachPartW = ["",""]
*/
])

/*
---- Before splitting

--#1	:CaseSensitive, :CS,
			
#2	:StartAt,
#3	:EndAt,

#4	:MaxNumberOfParts,
			
#5	:IgnoreFirstSep,
#6	:IgnoreLastSep,

#7	:PerformOnEachCharW,
			
---- After splitting
			
#8	:RemoveEmptyParts,
#9	:RemoveBlankSpaceParts,
			
#10	:RemoveFirstSplittedPart,
		# Splitted --> cFirstPart generated by :IgnoreFirstSep
		# is not concerned

#11	:RemoveLastSplittedPart,
		# Splitted --> cLastPart generated by :IgnoreLastSep is
		# not concerned

#12	:RemoveTheseSplittedParts,
		# Spliited --> cFirstPart and cLastPart generated by
		# :IgnoreFirstSep and :IgnoreLastSep are not concerned

#13	:RemoveTheseLeadingSubstringsInEachPart,
#14	:RemoveTheseTrailingSubstringsInEachPart,
#15	:RemoveLeadingCharsInEachPart,
#16	:RemoveTrailingCharsInEachPart,
		
#17	:RemoveThisLeadingCharInEachPart,
#18	:RemoveThisTrailingCharInEachPart,
			
#19	:RemoveNLeadingCharsInEachPart,
#20	:RemoveNTrailingCharsInEachPart,
			
#21	:PerformOnEachPartW
