# THE DRAKON SCENES, AS FUNCTIONS TWO FILES SHARE.
#
# The catalogue renders them; the gate GOVERNS them. They were written
# once, inline in the catalogue, and the governor's corpus carried its
# own smaller copies -- and a rule tested on the smaller copy passed a
# picture the larger one broke: the OR staircase, three deep in the
# catalogue and two deep in the corpus, inverted for as long as the rule
# existed. A family written in two places drifts; this is the one place.
# Each takes the options it renders with, so the catalogue and the gate
# ask for the same scene at their own size.
#
# Functions only: loading this file draws nothing.

func StzDrakonScene01(paOpt)
	_o_ = new stzDiagram("simplest")
	_o_.SetNotation(StzDrakonNotation())
	_o_.AddNodeXTT("t", "Sum two numbers", [ :type = "title" ])
	_o_.AddNodeXTT("a", "result = a + b",  [ :type = "action" ])
	_o_.AddNodeXTT("e", "End",             [ :type = "end" ])
	_o_.AddEdge("t","a")  _o_.AddEdge("a","e")
	_o_.ToCanvasXT(paOpt)
	return _o_

func StzDrakonScene02(paOpt)
	_o_ = new stzDiagram("theif")
	_o_.SetNotation(StzDrakonNotation())
	_o_.AddNodeXTT("t",  "Go out",           [ :type = "title" ])
	_o_.AddNodeXTT("q",  "Is it raining?",   [ :type = "question" ])
	_o_.AddNodeXTT("umb", "Take an umbrella",[ :type = "action" ])
	_o_.AddNodeXTT("go", "Leave the house",  [ :type = "action" ])
	_o_.AddNodeXTT("e",  "End",              [ :type = "end" ])
	_o_.AddEdge("t","q")
	_o_.AddEdgeXTT("q","umb","yes", [ :exit = :down ])
	_o_.AddEdgeXTT("q","go","no",   [ :exit = :right ])
	_o_.AddEdge("umb","go")  _o_.AddEdge("go","e")
	_o_.ToCanvasXT(paOpt)
	return _o_

func StzDrakonScene03(paOpt)
	_o_ = new stzDiagram("secondary")
	_o_.SetNotation(StzDrakonNotation())
	_o_.AddNodeXTT("t",  "Serve tea",        [ :type = "title" ])
	_o_.AddNodeXTT("q1", "Cup intact?",      [ :type = "question" ])
	_o_.AddNodeXTT("q2", "Tea still hot?",   [ :type = "question" ])
	_o_.AddNodeXTT("q3", "Guest seated?",    [ :type = "question" ])
	_o_.AddNodeXTT("ok", "Pour and serve",   [ :type = "action" ])
	_o_.AddNodeXTT("n3", "Wait a moment",    [ :type = "action" ])
	_o_.AddNodeXTT("n2", "Reheat the pot",   [ :type = "action" ])
	_o_.AddNodeXTT("n1", "Sweep the pieces", [ :type = "action" ])
	_o_.AddNodeXTT("e",  "End",              [ :type = "end" ])
	_o_.AddEdge("t","q1")
	_o_.AddEdgeXTT("q1","q2","yes", [ :exit = :down ])
	_o_.AddEdgeXTT("q1","n1","no",  [ :exit = :right ])
	_o_.AddEdgeXTT("q2","q3","yes", [ :exit = :down ])
	_o_.AddEdgeXTT("q2","n2","no",  [ :exit = :right ])
	_o_.AddEdgeXTT("q3","ok","yes", [ :exit = :down ])
	_o_.AddEdgeXTT("q3","n3","no",  [ :exit = :right ])
	_o_.AddEdge("ok","e")  _o_.AddEdge("n1","e")
	_o_.AddEdge("n2","e")  _o_.AddEdge("n3","e")
	_o_.ToCanvasXT(paOpt)
	return _o_

func StzDrakonScene04(paOpt)
	_o_ = new stzDiagram("insertion")
	_o_.SetNotation(StzDrakonNotation())
	_o_.AddNodeXTT("t",  "Print the report", [ :type = "title" ])
	_o_.AddNodeXTT("g",  "Gather the rows",  [ :type = "action" ])
	_o_.AddNodeXTT("ins","Format the page",  [ :type = "insertion" ])
	_o_.AddNodeXTT("s",  "Send to printer",  [ :type = "action" ])
	_o_.AddNodeXTT("e",  "End",              [ :type = "end" ])
	_o_.AddEdge("t","g")  _o_.AddEdge("g","ins")
	_o_.AddEdge("ins","s")  _o_.AddEdge("s","e")
	_o_.ToCanvasXT(paOpt)
	return _o_

func StzDrakonScene05(paOpt)
	_o_ = new stzDiagram("forloop")
	_o_.SetNotation(StzDrakonNotation())
	_o_.AddNodeXTT("t", "Total a basket",  [ :type = "title" ])
	_o_.AddNodeXTT("f", "for each line",   [ :type = "foreach" ])
	_o_.AddNodeXTT("p", "Read its price",  [ :type = "action" ])
	_o_.AddNodeXTT("a", "Add to the total",[ :type = "action" ])
	_o_.AddNodeXTT("z", "end for",         [ :type = "endforeach" ])
	_o_.AddNodeXTT("s", "Show the total",  [ :type = "action" ])
	_o_.AddNodeXTT("e", "End",             [ :type = "end" ])
	_o_.AddEdge("t","f")  _o_.AddEdge("f","p")  _o_.AddEdge("p","a")
	_o_.AddEdge("a","z")
	_o_.AddEdge("z","f")
	_o_.AddEdgeXTT("z","s","", [ :exit = :down ])
	_o_.AddEdge("s","e")
	_o_.ToCanvasXT(paOpt)
	return _o_

func StzDrakonScene06(paOpt)
	_o_ = new stzDiagram("forexit")
	_o_.SetNotation(StzDrakonNotation())
	_o_.AddNodeXTT("t", "Scan the file",   [ :type = "title" ])
	_o_.AddNodeXTT("f", "for each row",    [ :type = "foreach" ])
	_o_.AddNodeXTT("r", "Read the row",    [ :type = "action" ])
	_o_.AddNodeXTT("q", "Row readable?",   [ :type = "question" ])
	_o_.AddNodeXTT("k", "Keep it",         [ :type = "action" ])
	_o_.AddNodeXTT("z", "end for",         [ :type = "endforeach" ])
	_o_.AddNodeXTT("bad","Report damage",  [ :type = "action" ])
	_o_.AddNodeXTT("e", "End",             [ :type = "end" ])
	_o_.AddEdge("t","f")  _o_.AddEdge("f","r")  _o_.AddEdge("r","q")
	_o_.AddEdgeXTT("q","k","yes",   [ :exit = :down ])
	_o_.AddEdgeXTT("q","bad","no",  [ :exit = :right ])
	_o_.AddEdge("k","z")
	_o_.AddEdge("z","f")
	_o_.AddEdgeXTT("z","e","", [ :exit = :down ])
	_o_.AddEdge("bad","e")
	_o_.ToCanvasXT(paOpt)
	return _o_

func StzDrakonScene07(paOpt)
	_o_ = new stzDiagram("whileloop")
	_o_.SetNotation(StzDrakonNotation())
	_o_.AddNodeXTT("t", "Drain the queue", [ :type = "title" ])
	_o_.AddNodeXTT("q", "Anything left?",  [ :type = "question" ])
	_o_.AddNodeXTT("a", "Handle one item", [ :type = "action" ])
	_o_.AddNodeXTT("e", "End",             [ :type = "end" ])
	_o_.AddEdge("t","q")
	_o_.AddEdgeXTT("q","a","yes", [ :exit = :down ])
	_o_.AddEdgeXTT("q","e","no",  [ :exit = :right ])
	_o_.AddEdge("a","q")
	_o_.ToCanvasXT(paOpt)
	return _o_

func StzDrakonScene08(paOpt)
	_o_ = new stzDiagram("dountil")
	_o_.SetNotation(StzDrakonNotation())
	_o_.AddNodeXTT("t", "Dial the number", [ :type = "title" ])
	_o_.AddNodeXTT("a", "Place the call",  [ :type = "action" ])
	_o_.AddNodeXTT("q", "Answered?",       [ :type = "question" ])
	_o_.AddNodeXTT("e", "End",             [ :type = "end" ])
	_o_.AddEdge("t","a")  _o_.AddEdge("a","q")
	_o_.AddEdgeXTT("q","e","yes", [ :exit = :down ])
	_o_.AddEdgeXTT("q","a","no",  [ :exit = :right ])
	_o_.ToCanvasXT(paOpt)
	return _o_

func StzDrakonScene09(paOpt)
	_o_ = new stzDiagram("hybrid")
	_o_.SetNotation(StzDrakonNotation())
	_o_.AddNodeXTT("t",  "Fill the tank",   [ :type = "title" ])
	_o_.AddNodeXTT("a1", "Pour a litre",    [ :type = "action" ])
	_o_.AddNodeXTT("q",  "Tank full?",      [ :type = "question" ])
	_o_.AddNodeXTT("a2", "Wait for settle", [ :type = "action" ])
	_o_.AddNodeXTT("e",  "End",             [ :type = "end" ])
	_o_.AddEdge("t","a1")  _o_.AddEdge("a1","q")
	_o_.AddEdgeXTT("q","e","yes", [ :exit = :down ])
	_o_.AddEdgeXTT("q","a2","no", [ :exit = :right ])
	_o_.AddEdge("a2","a1")
	_o_.ToCanvasXT(paOpt)
	return _o_

func StzDrakonScene10(paOpt)
	_o_ = new stzDiagram("switch")
	_o_.SetNotation(StzDrakonNotation())
	_o_.AddNodeXTT("t",  "Route the parcel",[ :type = "title" ])
	_o_.AddNodeXTT("s",  "Destination?",    [ :type = "select" ])
	_o_.AddNodeXTT("k1", "local",           [ :type = "case" ])
	_o_.AddNodeXTT("k2", "national",        [ :type = "case" ])
	_o_.AddNodeXTT("k3", "abroad",          [ :type = "case" ])
	_o_.AddNodeXTT("d1", "Bike courier",    [ :type = "action" ])
	_o_.AddNodeXTT("d2", "Post it",         [ :type = "action" ])
	_o_.AddNodeXTT("d3", "Air freight",     [ :type = "action" ])
	_o_.AddNodeXTT("e",  "End",             [ :type = "end" ])
	_o_.AddEdge("t","s")
	_o_.AddEdge("s","k1")  _o_.AddEdge("s","k2")  _o_.AddEdge("s","k3")
	_o_.AddEdge("k1","d1") _o_.AddEdge("k2","d2") _o_.AddEdge("k3","d3")
	_o_.AddEdge("d1","e")  _o_.AddEdge("d2","e")  _o_.AddEdge("d3","e")
	_o_.ToCanvasXT(paOpt)
	return _o_

func StzDrakonScene11(paOpt)
	_o_ = new stzDiagram("switchloop")
	_o_.SetNotation(StzDrakonNotation())
	_o_.AddNodeXTT("t",  "Read a command",  [ :type = "title" ])
	_o_.AddNodeXTT("rd", "Take one word",   [ :type = "input" ])
	_o_.AddNodeXTT("s",  "Which command?",  [ :type = "select" ])
	_o_.AddNodeXTT("k1", "run",             [ :type = "case" ])
	_o_.AddNodeXTT("k2", "stop",            [ :type = "case" ])
	_o_.AddNodeXTT("k3", "anything else",   [ :type = "case" ])
	_o_.AddNodeXTT("d1", "Start the job",   [ :type = "action" ])
	_o_.AddNodeXTT("d2", "Halt the job",    [ :type = "action" ])
	_o_.AddNodeXTT("d3", "Say it is unknown",[ :type = "action" ])
	_o_.AddNodeXTT("e",  "End",             [ :type = "end" ])
	_o_.AddEdge("t","rd")  _o_.AddEdge("rd","s")
	_o_.AddEdge("s","k1")  _o_.AddEdge("s","k2")  _o_.AddEdge("s","k3")
	_o_.AddEdge("k1","d1") _o_.AddEdge("k2","d2") _o_.AddEdge("k3","d3")
	_o_.AddEdge("d1","e")  _o_.AddEdge("d2","e")
	# the loop: the last case goes back above the Select and asks again
	_o_.AddEdge("d3","rd")
	_o_.ToCanvasXT(paOpt)
	return _o_

func StzDrakonScene12(paOpt)
	_o_ = new stzDiagram("logicand")
	_o_.SetNotation(StzDrakonNotation())
	_o_.AddNodeXTT("t",  "Buy the gadget?",  [ :type = "title" ])
	_o_.AddNodeXTT("q1", "Looks good?",      [ :type = "question" ])
	_o_.AddNodeXTT("q2", "Affordable?",      [ :type = "question" ])
	_o_.AddNodeXTT("yes","Buy it",           [ :type = "action" ])
	_o_.AddNodeXTT("no", "Walk away",        [ :type = "action" ])
	_o_.AddNodeXTT("e",  "End",              [ :type = "end" ])
	_o_.AddEdge("t","q1")
	_o_.AddEdgeXTT("q1","q2","yes", [ :exit = :down ])
	_o_.AddEdgeXTT("q1","no","no",  [ :exit = :right ])
	_o_.AddEdgeXTT("q2","yes","yes",[ :exit = :down ])
	_o_.AddEdgeXTT("q2","no","no",  [ :exit = :right ])
	_o_.AddEdge("yes","e")  _o_.AddEdge("no","e")
	_o_.ToCanvasXT(paOpt)
	return _o_

func StzDrakonScene13(paOpt)
	_o_ = new stzDiagram("logicor")
	_o_.SetNotation(StzDrakonNotation())
	_o_.AddNodeXTT("t",  "Let them in?",    [ :type = "title" ])
	_o_.AddNodeXTT("q1", "On the list?",    [ :type = "question" ])
	_o_.AddNodeXTT("q2", "Has a ticket?",   [ :type = "question" ])
	_o_.AddNodeXTT("q3", "Knows the host?", [ :type = "question" ])
	_o_.AddNodeXTT("in", "Open the door",   [ :type = "action" ])
	_o_.AddNodeXTT("out","Turn them away",  [ :type = "action" ])
	_o_.AddNodeXTT("e",  "End",             [ :type = "end" ])
	_o_.AddEdge("t","q1")
	_o_.AddEdgeXTT("q1","in","yes",  [ :exit = :down ])
	_o_.AddEdgeXTT("q1","q2","no",   [ :exit = :right ])
	_o_.AddEdgeXTT("q2","in","yes",  [ :exit = :down ])
	_o_.AddEdgeXTT("q2","q3","no",   [ :exit = :right ])
	_o_.AddEdgeXTT("q3","in","yes",  [ :exit = :down ])
	_o_.AddEdgeXTT("q3","out","no",  [ :exit = :right ])
	_o_.AddEdge("in","e")  _o_.AddEdge("out","e")
	_o_.ToCanvasXT(paOpt)
	return _o_

func StzDrakonScene14(paOpt)
	_o_ = new stzDiagram("cooklunch")
	_o_.SetNotation(StzDrakonNotation())
	_o_.AddNodeXTT("b1", "Salad",           [ :type = "branch", :branchId = 1 ])
	_o_.AddNodeXTT("w1", "wash vegetables", [ :type = "action" ])
	_o_.AddNodeXTT("w2", "slice vegetables",[ :type = "action" ])
	_o_.AddNodeXTT("w3", "blend vegetables",[ :type = "action" ])
	_o_.AddNodeXTT("a1", "Potatoes",        [ :type = "address" ])
	_o_.AddNodeXTT("b2", "Potatoes",        [ :type = "branch", :branchId = 2 ])
	_o_.AddNodeXTT("p1", "peel potatoes",   [ :type = "action" ])
	_o_.AddNodeXTT("p2", "boil potatoes",   [ :type = "action" ])
	_o_.AddNodeXTT("p3", "add butter",      [ :type = "action" ])
	_o_.AddNodeXTT("a2", "Meat",            [ :type = "address" ])
	_o_.AddNodeXTT("b3", "Meat",            [ :type = "branch", :branchId = 3 ])
	_o_.AddNodeXTT("m1", "cut in pieces",   [ :type = "action" ])
	_o_.AddNodeXTT("m2", "stuff with garlic",[ :type = "action" ])
	_o_.AddNodeXTT("m3", "bake in oven",    [ :type = "action" ])
	_o_.AddNodeXTT("fin","End",             [ :type = "end" ])
	_o_.AddEdge("b1","w1")  _o_.AddEdge("w1","w2")  _o_.AddEdge("w2","w3")
	_o_.AddEdge("w3","a1")  _o_.AddEdge("a1","b2")
	_o_.AddEdge("b2","p1")  _o_.AddEdge("p1","p2")  _o_.AddEdge("p2","p3")
	_o_.AddEdge("p3","a2")  _o_.AddEdge("a2","b3")
	_o_.AddEdge("b3","m1")  _o_.AddEdge("m1","m2")  _o_.AddEdge("m2","m3")
	_o_.AddEdge("m3","fin")
	_o_.ToCanvasXT(paOpt)
	return _o_

func StzDrakonScene15(paOpt)
	_o_ = new stzDiagram("branchloop")
	_o_.SetNotation(StzDrakonNotation())
	_o_.AddNodeXTT("b1", "Prepare",         [ :type = "branch", :branchId = 1 ])
	_o_.AddNodeXTT("s1", "Open the line",   [ :type = "action" ])
	_o_.AddNodeXTT("x1", "Attempt",         [ :type = "address" ])
	_o_.AddNodeXTT("b2", "Attempt",         [ :type = "branch", :branchId = 2 ])
	_o_.AddNodeXTT("s2", "Send the packet", [ :type = "action" ])
	_o_.AddNodeXTT("q",  "Acknowledged?",   [ :type = "question" ])
	_o_.AddNodeXTT("x2", "Finish",          [ :type = "address" ])
	_o_.AddNodeXTT("rt", "Attempt",         [ :type = "address" ])
	_o_.AddNodeXTT("b3", "Finish",          [ :type = "branch", :branchId = 3 ])
	_o_.AddNodeXTT("s3", "Close the line",  [ :type = "action" ])
	_o_.AddNodeXTT("fin","End",             [ :type = "end" ])
	_o_.AddEdge("b1","s1")  _o_.AddEdge("s1","x1")  _o_.AddEdge("x1","b2")
	_o_.AddEdge("b2","s2")  _o_.AddEdge("s2","q")
	_o_.AddEdgeXTT("q","x2","yes", [ :exit = :down ])
	_o_.AddEdgeXTT("q","rt","no",  [ :exit = :right ])
	_o_.AddEdge("x2","b3")
	# the branch loop: this address names a branch to the LEFT
	_o_.AddEdge("rt","b2")
	_o_.AddEdge("b3","s3")  _o_.AddEdge("s3","fin")
	_o_.ToCanvasXT(paOpt)
	return _o_

func StzDrakonScene16(paOpt)
	_o_ = new stzDiagram("advancestep")
	_o_.SetNotation(StzDrakonNotation())
	_o_.AddNodeXTT("t",  "advanceStep",       [ :type = "title" ])
	_o_.AddNodeXTT("s",  "module.state",      [ :type = "select" ])
	_o_.AddNodeXTT("k1", "playing",           [ :type = "case" ])
	_o_.AddNodeXTT("k2", "dropping",          [ :type = "case" ])
	_o_.AddNodeXTT("k3", "finished",          [ :type = "case" ])
	_o_.AddNodeXTT("p1", "module.projectile", [ :type = "question" ])
	_o_.AddNodeXTT("p2", "canMoveDown()",     [ :type = "question" ])
	_o_.AddNodeXTT("p3", "moveDown()",        [ :type = "action" ])
	_o_.AddNodeXTT("p4", "return getStepPeriod()", [ :type = "action" ])
	_o_.AddNodeXTT("p5", "freezeProjectile()",[ :type = "action" ])
	_o_.AddNodeXTT("p6", "return noProjectile()",  [ :type = "action" ])
	_o_.AddNodeXTT("d1", "canMoveDown()",     [ :type = "question" ])
	_o_.AddNodeXTT("d2", "moveDown()",        [ :type = "action" ])
	_o_.AddNodeXTT("d3", "return DropPeriod", [ :type = "action" ])
	_o_.AddNodeXTT("d4", "freezeProjectile()",[ :type = "action" ])
	_o_.AddNodeXTT("d5", "return getStepPeriod()", [ :type = "action" ])
	_o_.AddNodeXTT("f1", "return undefined",  [ :type = "action" ])
	_o_.AddNodeXTT("e",  "End",               [ :type = "end" ])
	_o_.AddEdge("t","s")
	_o_.AddEdge("s","k1")  _o_.AddEdge("s","k2")  _o_.AddEdge("s","k3")
	_o_.AddEdge("k1","p1")
	_o_.AddEdgeXTT("p1","p2","yes", [ :exit = :down ])
	_o_.AddEdgeXTT("p1","p6","no",  [ :exit = :right ])
	_o_.AddEdgeXTT("p2","p3","yes", [ :exit = :down ])
	_o_.AddEdgeXTT("p2","p5","no",  [ :exit = :right ])
	_o_.AddEdge("p3","p4")  _o_.AddEdge("p5","p6")
	_o_.AddEdge("p4","e")   _o_.AddEdge("p6","e")
	_o_.AddEdge("k2","d1")
	_o_.AddEdgeXTT("d1","d2","yes", [ :exit = :down ])
	_o_.AddEdgeXTT("d1","d4","no",  [ :exit = :right ])
	_o_.AddEdge("d2","d3")  _o_.AddEdge("d4","d5")
	_o_.AddEdge("d3","e")   _o_.AddEdge("d5","e")
	_o_.AddEdge("k3","f1")  _o_.AddEdge("f1","e")
	_o_.ToCanvasXT(paOpt)
	return _o_

func StzDrakonScene17(paOpt)
	_o_ = new stzDiagram("numbertostring")
	_o_.SetNotation(StzDrakonNotation())
	_o_.AddNodeXTT("t",  "NumberToString", [ :type = "title" ])
	_o_.AddNodeXTT("s",  "number",         [ :type = "select" ])
	_o_.AddNodeXTT("k0", "0",              [ :type = "case" ])
	_o_.AddNodeXTT("k1", "1",              [ :type = "case" ])
	_o_.AddNodeXTT("k2", "2",              [ :type = "case" ])
	_o_.AddNodeXTT("k3", "anything else",  [ :type = "case" ])
	_o_.AddNodeXTT("p0", "print(zero)",    [ :type = "action" ])
	_o_.AddNodeXTT("p1", "print(one)",     [ :type = "action" ])
	_o_.AddNodeXTT("p2", "print(two)",     [ :type = "action" ])
	_o_.AddNodeXTT("p3", "print(a lot)",   [ :type = "action" ])
	_o_.AddNodeXTT("e",  "End",            [ :type = "end" ])
	_o_.AddEdge("t","s")
	_o_.AddEdge("s","k0")  _o_.AddEdge("s","k1")
	_o_.AddEdge("s","k2")  _o_.AddEdge("s","k3")
	_o_.AddEdge("k0","p0") _o_.AddEdge("k1","p1")
	_o_.AddEdge("k2","p2") _o_.AddEdge("k3","p3")
	_o_.AddEdge("p0","e")  _o_.AddEdge("p1","e")
	_o_.AddEdge("p2","e")  _o_.AddEdge("p3","e")
	_o_.ToCanvasXT(paOpt)
	return _o_

func StzDrakonScene18(paOpt)
	_o_ = new stzDiagram("icons")
	_o_.SetNotation(StzDrakonNotation())
	_o_.AddNodeXTT("t",  "Title",     [ :type = "title" ])
	_o_.AddNodeXTT("i",  "Input",     [ :type = "input" ])
	_o_.AddNodeXTT("o",  "Output",    [ :type = "output" ])
	_o_.AddNodeXTT("a",  "Action",    [ :type = "action" ])
	_o_.AddNodeXTT("q",  "Question",  [ :type = "question" ])
	_o_.AddNodeXTT("sel","Select",    [ :type = "select" ])
	_o_.AddNodeXTT("cs", "Case",      [ :type = "case" ])
	_o_.AddNodeXTT("ins","Insertion", [ :type = "insertion" ])
	# A SHELF CARRIES TWO TEXTS OR IT IS A BOX. Declared with only a name
	# it drew as one compartment, which is the icon with its own rule
	# missing -- the thing that makes it a shelf.
	_o_.AddNodeXTT("sh", "Shelf",     [ :type = "shelf", :value = "what it is" ])
	_o_.AddNodeXTT("bf", "Begin For", [ :type = "foreach" ])
	_o_.AddNodeXTT("ef", "End For",   [ :type = "endforeach" ])
	_o_.AddNodeXTT("tm", "Timer",     [ :type = "timer" ])
	_o_.AddNodeXTT("pa", "Pause",     [ :type = "pause" ])
	_o_.AddNodeXTT("br", "Branch",    [ :type = "branch" ])
	_o_.AddNodeXTT("ad", "Address",   [ :type = "address" ])
	_o_.AddNodeXTT("e",  "End",       [ :type = "end" ])
	_o_.AddEdge("t","i")    _o_.AddEdge("i","o")    _o_.AddEdge("o","a")
	_o_.AddEdge("a","q")
	_o_.AddEdgeXTT("q","sel","yes", [ :exit = :down ])
	_o_.AddEdge("sel","cs") _o_.AddEdge("cs","ins")  _o_.AddEdge("ins","sh")
	_o_.AddEdge("sh","bf")  _o_.AddEdge("bf","ef")   _o_.AddEdge("ef","tm")
	_o_.AddEdge("tm","pa")  _o_.AddEdge("pa","br")   _o_.AddEdge("br","ad")
	_o_.AddEdge("ad","e")
	_o_.ToCanvasXT(paOpt)
	return _o_

func StzDrakonScene19(paOpt)
	_o_ = new stzDiagram("shelfwork")
	_o_.SetNotation(StzDrakonNotation())
	_o_.AddNodeXTT("t",  "Price a basket",   [ :type = "title" ])
	_o_.AddNodeXTT("rd", "Read the lines",   [ :type = "input" ])
	_o_.AddNodeXTT("ins","Apply the tariff", [ :type = "insertion" ])
	_o_.AddNodeXTT("s1", "net",              [ :type = "shelf",
	                                           :value = "sum of the lines" ])
	_o_.AddNodeXTT("s2", "total",            [ :type = "shelf",
	                                           :value = "net + tax" ])
	_o_.AddNodeXTT("ou", "Show the total",   [ :type = "output" ])
	_o_.AddNodeXTT("e",  "End",              [ :type = "end" ])
	_o_.AddEdge("t","rd")   _o_.AddEdge("rd","ins")  _o_.AddEdge("ins","s1")
	_o_.AddEdge("s1","s2")  _o_.AddEdge("s2","ou")   _o_.AddEdge("ou","e")
	_o_.ToCanvasXT(paOpt)
	return _o_

func StzDrakonScene20(paOpt)
	_o_ = new stzDiagram("realtime")
	_o_.SetNotation(StzDrakonNotation())
	_o_.AddNodeXTT("t",  "Poll the sensor",  [ :type = "title" ])
	_o_.AddNodeXTT("rd", "Read the value",   [ :type = "action" ])
	_o_.AddNodeXTT("tm", "500 ms",           [ :type = "timer" ])
	_o_.AddNodeXTT("pub","Publish the run",  [ :type = "par" ])
	_o_.AddNodeXTT("st", "Settle",           [ :type = "pause" ])
	_o_.AddNodeXTT("wr", "Write the log",    [ :type = "action" ])
	_o_.AddNodeXTT("e",  "Done",             [ :type = "end" ])
	_o_.AddEdge("t","rd")   _o_.AddEdge("rd","pub")
	_o_.AddEdge("pub","wr") _o_.AddEdge("wr","e")
	# the two attachments: each governs the icon it points at, and neither
	# is a step in the sequence
	_o_.AddEdge("tm","rd")
	_o_.AddEdge("st","wr")
	_o_.ToCanvasXT(paOpt)
	return _o_
