#!/usr/bin/env python3
"""Generate NumPy/LAPACK reference values for numeric_reference_oracle_narrated.ring.

WHY A GENERATOR AND FROZEN VALUES, rather than calling Python from the test:
the guard must run wherever Ring runs, with no Python dependency at test time.
So the reference values are produced HERE by NumPy (i.e. LAPACK) and checked in
as constants. This script stays committed so the numbers are auditable and
regenerable -- run it and diff if a reference is ever doubted.

    python3 _gen_numpy_reference.py

The corpus is deliberately ILL-CONDITIONED. A numeric library is judged on
Hilbert and Vandermonde matrices, not on tidy 3x3 examples.
"""

import numpy as np
from fractions import Fraction

np.set_printoptions(precision=17)

EPS = float(np.finfo(float).eps)


def exact_solve_ones(rows):
    """Solve A x = [1,1,...] in EXACT RATIONAL ARITHMETIC.

    A stronger oracle than LAPACK: no rounding at all.

    TWO DIFFERENT TRUTHS, AND THE DISTINCTION MATTERS. Called with Fraction(1, i+j+1)
    this solves the TRUE Hilbert matrix and the answer is a vector of INTEGERS.
    Called with the f64 entries, it solves the matrix that was actually HANDED to
    the library -- a slightly different matrix, whose exact answer differs from the
    integers by ~1e-10 no matter how perfect the solver is. Judging an algorithm
    against the integers would charge it for the input's representation error.
    """
    n = len(rows)
    m = [[Fraction(v) for v in rows[i]] + [Fraction(1)] for i in range(n)]
    for c in range(n):
        p = next(r for r in range(c, n) if m[r][c] != 0)
        m[c], m[p] = m[p], m[c]
        pv = m[c][c]
        m[c] = [v / pv for v in m[c]]
        for r in range(n):
            if r != c and m[r][c] != 0:
                f = m[r][c]
                m[r] = [a - f * b for a, b in zip(m[r], m[c])]
    return [m[i][n] for i in range(n)]


def hilbert(n):
    return np.array([[1.0 / (i + j + 1) for j in range(n)] for i in range(n)])


def tridiag(n):
    a = np.zeros((n, n))
    for i in range(n):
        a[i, i] = 2.0
        if i:
            a[i, i - 1] = -1.0
            a[i - 1, i] = -1.0
    return a


def vandermonde(nodes):
    n = len(nodes)
    return np.array([[nodes[i] ** j for j in range(n)] for i in range(n)])


def ring_num(x):
    """Ring literal for an f64.

    FIXED-POINT ONLY: Ring's parser rejects scientific notation, so a reference
    like 9.67e-05 must be written out as 0.0000967... . 30 decimals is well past
    f64's ~17 significant digits for every magnitude in this corpus.
    """
    x = float(x)
    if x == 0.0:
        return "0"
    s = f"{x:.30f}".rstrip("0")
    if s.endswith("."):
        s += "0"
    return s


def ring_list(xs):
    return "[ " + ", ".join(ring_num(x) for x in xs) + " ]"


def ring_matrix(m):
    rows = ["[ " + ", ".join(ring_num(v) for v in row) + " ]" for row in m]
    return "[ " + ", ".join(rows) + " ]"


# Matrices whose entries have an EXACT rational form, so the "true" answer can be
# distinguished from the answer to their f64 rounding.
EXACT_RATIONAL = {
    "hilbert4": lambda n: [[Fraction(1, i + j + 1) for j in range(n)] for i in range(n)],
    "hilbert5": lambda n: [[Fraction(1, i + j + 1) for j in range(n)] for i in range(n)],
    "hilbert6": lambda n: [[Fraction(1, i + j + 1) for j in range(n)] for i in range(n)],
}

CORPUS = {}

CORPUS["hilbert4"] = hilbert(4)
CORPUS["hilbert5"] = hilbert(5)
CORPUS["hilbert6"] = hilbert(6)
CORPUS["tridiag5"] = tridiag(5)
CORPUS["vander4"] = vandermonde([1.0, 2.0, 3.0, 4.0])
CORPUS["spd3"] = np.array([[4.0, 1.0, 2.0], [1.0, 5.0, 3.0], [2.0, 3.0, 6.0]])
CORPUS["nearsing2"] = np.array([[1.0, 1.0], [1.0, 1.0000001]])
# non-symmetric, genuinely complex spectrum
CORPUS["rot3"] = np.array([[0.0, -1.0, 0.0], [1.0, 0.0, 0.0], [0.0, 0.0, 2.0]])

print("# GENERATED by _gen_numpy_reference.py -- do not hand-edit.")
print("# Reference values from NumPy (LAPACK). Regenerate with:")
print("#     python3 _gen_numpy_reference.py")
print()

for name, a in CORPUS.items():
    n = a.shape[0]
    sym = np.allclose(a, a.T)

    # eigenvalues: real ascending when the spectrum is real, else complex pairs
    ev = np.linalg.eigvals(a)
    real_spectrum = np.allclose(ev.imag, 0.0)

    sv = np.linalg.svd(a, compute_uv=False)
    cond = np.linalg.cond(a)          # 2-norm condition number
    det = np.linalg.det(a)
    rank = np.linalg.matrix_rank(a)

    print(f"# ---- {name} ({n}x{n}, symmetric={sym}, cond={cond:.6e}) ----")
    print(f"func RefMat_{name}()")
    print(f"\treturn {ring_matrix(a)}")
    print()

    if real_spectrum:
        print(f"func RefEig_{name}()          # ascending, real")
        print(f"\treturn {ring_list(sorted(ev.real))}")
    else:
        print(f"func RefEigRe_{name}()        # real parts, ascending by (re, im)")
        order = sorted(range(n), key=lambda k: (ev[k].real, ev[k].imag))
        print(f"\treturn {ring_list([ev[k].real for k in order])}")
        print()
        print(f"func RefEigIm_{name}()        # matching imaginary parts")
        print(f"\treturn {ring_list([ev[k].imag for k in order])}")
    print()

    print(f"func RefSv_{name}()           # singular values, descending")
    print(f"\treturn {ring_list(sv)}")
    print()
    print(f"func RefCond_{name}()")
    print(f"\treturn {ring_num(cond)}")
    print()
    print(f"func RefDet_{name}()")
    print(f"\treturn {ring_num(det)}")
    print()
    print(f"func RefRank_{name}()")
    print(f"\treturn {rank}")
    print()

    # a solve, on a right-hand side of all ones -- the classic ill-conditioning demo
    if abs(det) > 1e-300:
        b = np.ones(n)
        x = np.linalg.solve(a, b)
        print(f"func RefSolveOnes_{name}()    # x where A x = [1,1,...]")
        print(f"\treturn {ring_list(x)}")
        print()
        inv = np.linalg.inv(a)
        print(f"func RefInv_{name}()")
        print(f"\treturn {ring_matrix(inv)}")
        print()

        # EXACT rational truth for the same solve, and the accuracy the
        # conditioning permits: relative error <= kappa(A) * eps. That product
        # is the guard's TOLERANCE -- derived, not a literal.
        #
        # ex   = exact answer to the matrix the library is ACTUALLY GIVEN (f64
        #        entries). The fair yardstick for the solver.
        # true = exact answer to the mathematically true matrix. For Hilbert
        #        these are integers; the gap between the two is the input's
        #        representation error, which no algorithm can undo.
        ex = exact_solve_ones(a.tolist())
        print(f"func RefExactSolveOnes_{name}()   # EXACT answer to the f64 matrix")
        print(f"\treturn {ring_list(float(v) for v in ex)}")
        print()
        if name in EXACT_RATIONAL:
            true = exact_solve_ones(EXACT_RATIONAL[name](n))
            print(f"func RefTrueSolveOnes_{name}()    # exact answer to the TRUE matrix")
            print(f"\treturn {ring_list(float(v) for v in true)}")
            print()
            rep = max(
                abs(float(e) - float(t)) / abs(float(t))
                for e, t in zip(ex, true) if float(t) != 0.0
            )
            print(f"func RefReprErr_{name}()          # input representation error alone")
            print(f"\treturn {ring_num(rep)}")
            print()
        print(f"func RefKappaEpsBound_{name}()    # kappa * eps = {cond * EPS:.6e}")
        print(f"\treturn {ring_num(cond * EPS)}")
        print()
        # how far LAPACK itself lands from exact truth -- the parity yardstick
        lap_rel = max(
            abs(float(xi) - float(ti)) / abs(float(ti))
            for xi, ti in zip(x, ex) if float(ti) != 0.0
        )
        print(f"func RefLapackRelErr_{name}()     # LAPACK's own relative error")
        print(f"\treturn {ring_num(lap_rel)}")
        print()
