load "../../stzBase.ring"
o = StzNumBufferQ([2, 4, 6, 8])
? "size=" + o.Size() + "  sum=" + o.Sum() + "  mean=" + o.Mean()
o.Scale(10).AddScalar(1)
? "after Scale(10).AddScalar(1) = " + @@(o.ToList())
? "min=" + o.Min() + " max=" + o.Max() + " varS=" + o.VarianceSample()
p = StzNumBufferQ([1, 1, 1, 1])
o.AddBuffer(p)
? "after AddBuffer = " + @@(o.ToList())
? "dot with itself = " + o.Dot(o)
q = StzNumBufferRangeQ(5, 1, 1)
? "RangeQ(5,1,1) = " + @@(q.ToList())
o.Free()  p.Free()  q.Free()
? "freed: " + o.IsFreed()
