load "../../stzBase.ring"
load "../_narrated.ring"

# Phase 4 of the numeric foundation, first slice: COMPILE THE ENGINE.
#
# Phase 4 is meant to be about kernels -- SIMD, threads, decompositions. Before
# writing one, a measurement worth taking: how fast is the engine we already have?
#
# `build.zig` asked for `b.standardOptimizeOption(.{})`, which defaults to Debug,
# and every documented build command in this repo is a bare `zig build`. The DLLs
# are not tracked in git, so every developer and every deploy compiled them
# UNOPTIMISED. Measured on 2M engine-resident f64s, twenty passes each:
#
#                    Debug     ReleaseSafe
#     Sum            0.14s        0.04s      3.5x
#     Mean           0.14s        0.04s      3.5x
#     Variance       0.22s        0.07s      3.1x
#     Dot            0.08s        0.03s      2.7x
#     Scale          0.05s        0.01s      5x
#
# On string, list and matrix work the same change buys about 15%, because there
# the marshalling dominates and the engine loop is a small share of the time.
# THAT CONTRAST IS THE POINT. Phase 3 moved computation into the engine, so from
# here on the engine loop IS the cost and how it is compiled starts to matter.
# Fixing this before writing a single SIMD kernel is the difference between
# optimising code and optimising code that was never being compiled.
#
# ReleaseSafe rather than ReleaseFast because it measured the SAME on every kernel
# while keeping bounds, overflow and alignment checks -- and because Debug had
# those checks too, so this changes NO runtime semantics, only the optimiser.

Scenario("the engine is compiled with optimisation on")
	# Debug cannot reach this. Twenty sums over two million resident doubles took
	# 0.14s unoptimised and 0.04s optimised, so the gate sits between them with
	# room for a slow machine on either side.
	nN = 2000000
	oBuf = StzNumBufferOfSizeQ(nN)
	oBuf.RangeFrom(1, 1)

	nT0 = clock()
	for k = 1 to 20
		nS = oBuf.Sum()
	next
	nT1 = clock()
	nElapsed = (nT1 - nT0) / clockspersecond()

	Then("twenty sums over 2M resident doubles come in under a tenth of a second",
	     nElapsed < 0.10, TRUE)
	Then("...and the answer is still right",
	     nS, nN * (nN + 1) / 2)

	oBuf.Free()
	# if this ever fails, check the build FIRST: `zig build` must default to
	# ReleaseSafe. A wrong answer is a kernel bug; a slow right answer is a build
	# regression.
EndScenario()

Scenario("...and the safety checks that came with Debug are still there")
	# ReleaseSafe keeps every runtime check Debug had. The point of choosing it
	# over ReleaseFast is that this engine is called across a C ABI by a
	# dynamically typed interpreter that can hand it any index at all, and a clean
	# refusal beats silent memory corruption.
	oBuf = StzNumBufferQ([ 10, 20, 30 ])
	Then("an index past the end is refused, not read", oBuf.Item(99), 0)
	Then("...and index zero too, since this API is 1-based", oBuf.Item(0), 0)
	Then("the buffer is unharmed", @@(oBuf.ToList()), "[ 10, 20, 30 ]")
	oBuf.Free()
EndScenario()

Scenario("the vendored C that the new mode broke, and now does not")
	# Turning optimisation on turned Zig's implicit C sanitiser on with it, and
	# tree-sitter started trapping: any parse at all -- `class A {}` was enough --
	# died with SIGILL and no message. A bare ud2 is what trap mode emits; a Zig
	# safety panic would have printed. Debug and ReleaseFast were both fine, which
	# is what identified it as a sanitiser trap rather than a miscompile.
	#
	# Those parser.c files are machine-generated by tree-sitter's codegen and do
	# deliberate unaligned access on packed parse tables. UBSan is off for that one
	# library now -- pcre2, utf8proc and sqlite still opt IN to trap mode, and our
	# own Zig keeps every check.
	if StzTreeSitterAvailable()
		oG = StzPyCodeGraphFromSourceTS("class A:" + nl + "    pass" + nl)
		Then("a parse that used to abort the process now answers",
		     oG.NumberOfClasses(), 1)
	else
		Then("tree-sitter not built here, nothing to check", TRUE, TRUE)
	ok
EndScenario()

Summary()
