# made d4.ring ; run: cd libraries/stzlib/base/test/reflect && ring <this file>  (picture: diag_colours_dot.png)
load "../../../stzlib.ring"
# chdir("<an output folder>") here, after the load, so the picture lands there (the engine DLL path breaks if Ring starts elsewhere: run from base/test/reflect)
o3 = new stzDiagram("colours")
o3.SetTheme("dark")
o3.SetLayout(:LeftRight)
o3.SetTitle("SEMANTIC COLOURS")
o3.AddNodeXTT("s", "Start", [ :type = "start", :color = "success" ])
o3.AddNodeXTT("p1", "Process", [ :type = "process", :color = "primary" ])
o3.AddNodeXTT("w", "Warning?", [ :type = "decision", :color = "warning" ])
o3.AddNodeXTT("d", "Danger", [ :type = "process", :color = "danger" ])
o3.AddNodeXTT("i", "Store", [ :type = "storage", :color = "info" ])
o3.AddNodeXTT("n", "Neutral", [ :type = "process", :color = "neutral" ])
o3.AddNodeXTT("e", "End", [ :type = "endpoint", :color = "success" ])
o3.Connect("s", "p1")
o3.Connect("p1", "w")
o3.ConnectXT("w", "d", "Yes")
o3.ConnectXT("w", "i", "No")
o3.Connect("d", "n")
o3.Connect("i", "n")
o3.Connect("n", "e")
write("diag_colours_dot.dot", o3.Dot())
write("diag_colours.mmd", o3.Mermaid())

o4 = new stzDiagram("PricingTiers")
o4.AddNodeXTT(:@free, "Free Tier", [ :Price = 0 ])
o4.AddNodeXTT(:@basic, "Basic Tier", [ :Price = 10 ])
o4.AddNodeXTT(:@pro, "Pro Tier", [ :Price = 50 ])
o4.AddNodeXTT(:@entreprise, "Enterprise Tier", [ :price = 200 ])
o4.ConnectSequence([ :@free, :@basic, :@pro, :@entreprise ])
o4.RegisterVisualRule("CHEAP_GREEN", [ :ConditionType = "property_range", :ConditionParams = [ :Price, 0, 30 ], :Effects = [ :Color = "green-", :PenWidth = 1 ] ])
o4.RegisterVisualRule("MID_BLUE", [ :ConditionType = "property_range", :ConditionParams = [ :Price, 31, 99 ], :Effects = [ :Color = "blue+", :PenWidth = 1 ] ])
o4.RegisterVisualRule("EXPENSIVE_GOLD", [ :ConditionType = "property_range", :ConditionParams = [ :Price, 100, 999999 ], :Effects = [ :Color = "gold", :PenWidth = 3 ] ])
o4.ApplyVisualRules()
o4.AddClusterXT("low", "Entry plans", [ :@free, :@basic ])
o4.AddClusterXT("high", "Paid plans", [ :@pro, :@entreprise ])
write("diag_rules_clusters_dot.dot", o4.Dot())
