cDoc = "# Mini" + char(10) + "```ring" + char(10) + "? 1 + 1" + char(10) + "#--> 2" + char(10) + "```" + char(10)
cBroken = "# Mini" + char(10) + "```ring" + char(10) + "? 1 + 1" + char(10) + "#--> 3" + char(10) + "```" + char(10)
write("t_ex15_h.en.md", cDoc)
write("t_ex15_i.en.md", cBroken)
oA = StzChapterQ("t_ex15_h.en.md", "en")
oA.Run("")
oB = StzChapterQ("t_ex15_i.en.md", "en")
oB.Run("")
? oA.AllPromisesKept()
? oB.AllPromisesKept()
remove("t_ex15_h.en.md")
remove("t_ex15_i.en.md")
