// Softanza Engine -- Named Param Registry
//
// Replaces 1,566 IsXxxNamedParam() methods in stzList with a single
// hash-set lookup. Ring calls stz_meta_is_named_param(keyword) and
// gets back 0/1 -- no eval(), no dynamic method construction.
//
// The keyword set is populated at init from a comptime table built
// from the actual stzlib codebase (extracted May 2026).

const std = @import("std");
const meta = @import("meta.zig");

// Complete keyword vocabulary extracted from stzList IsXxxNamedParam() methods.
// Each entry is one keyword that can appear as [:Keyword, value] in Ring.
// Sorted alphabetically for maintainability.
pub const all_keywords = [_][]const u8{
    "After",
    "AfterChar",
    "AfterChars",
    "AfterCharsW",
    "AfterCharsWhere",
    "AfterCharsWhereXT",
    "AfterCharsWXT",
    "AfterEach",
    "AfterFirst",
    "AfterIB",
    "AfterItem",
    "AfterItemIB",
    "AfterItems",
    "AfterItemsIB",
    "AfterLast",
    "AfterMany",
    "AfterManyPositions",
    "AfterManyPositionsIB",
    "AfterNth",
    "AfterPosition",
    "AfterPositionIB",
    "AfterPositions",
    "AfterPositionsIB",
    "AfterSection",
    "AfterSectionIB",
    "AfterSections",
    "AfterSectionsIB",
    "AfterSubString",
    "AfterSubStringIB",
    "AfterSubStringPosition",
    "AfterSubStrings",
    "AfterSubStringsIB",
    "AfterSubStringsPositions",
    "AfterThese",
    "AfterTheseItems",
    "AfterTheseItemsIB",
    "AfterThesePositions",
    "AfterThesePositionsIB",
    "AfterTheseSections",
    "AfterTheseSubStrings",
    "AfterTheseSubStringsIB",
    "AfterTheseSubStringsPositions",
    "AfterThisItem",
    "AfterThisItemIB",
    "AfterThisPosition",
    "AfterThisPositionIB",
    "AfterThisSection",
    "AfterThisSubString",
    "AfterThisSubStringIB",
    "AfterThisSubStringPosition",
    "AfterWhere",
    "AfterWhereXT",
    "AlongWith",
    "AlongWithTheir",
    "Among",
    "And",
    "AndChar",
    "AndCol",
    "AndColAt",
    "AndColAtPosition",
    "AndColNamed",
    "AndColumn",
    "AndColumnAt",
    "AndColumnAtPosition",
    "AndColumnNamed",
    "AndHarvest",
    "AndHarvestSection",
    "AndHarvestSections",
    "AndItem",
    "AndItemAt",
    "AndItemAtPosition",
    "AndPosition",
    "AndPositions",
    "AndReturnAs",
    "AndReturnedAs",
    "AndReturnItAs",
    "AndReturnThemAs",
    "AndRow",
    "AndRowAt",
    "AndRowAtPosition",
    "AndSection",
    "AndSections",
    "AndString",
    "AndStringAt",
    "AndStringAtPosition",
    "AndSubString",
    "AndSubStrings",
    "AndThat",
    "AndTheir",
    "AndThen",
    "AndThenHarvest",
    "AndThenHarvestSection",
    "AndThenHarvestSections",
    "AndThenYield",
    "AndThenYieldSection",
    "AndThenYieldSections",
    "AndThis",
    "AndYield",
    "AndYieldSection",
    "AndYieldSections",
    "Around",
    "AroundChar",
    "AroundChars",
    "AroundEach",
    "AroundFirst",
    "AroundIB",
    "AroundItemIB",
    "AroundItemsIB",
    "AroundLast",
    "AroundMany",
    "AroundNth",
    "AroundPosition",
    "AroundPositionIB",
    "AroundPositions",
    "AroundPositionsIB",
    "AroundSection",
    "AroundSectionIB",
    "AroundSections",
    "AroundSectionsIB",
    "AroundSubString",
    "AroundSubStringIB",
    "AroundSubStrings",
    "AroundSubStringsIB",
    "AroundThese",
    "AroundTheseItemsIB",
    "AroundThesePositionsIB",
    "AroundTheseSubStringsIB",
    "AroundThisItemIB",
    "AroundThisPositionIB",
    "AroundThisSubStringIB",
    "As",
    "At",
    "AtChar",
    "AtChars",
    "AtCharsW",
    "AtCharsWhere",
    "AtCharsWhereXT",
    "AtCharsWXT",
    "AtIB",
    "AtItem",
    "AtItemIB",
    "AtItems",
    "AtItemsIB",
    "AtList",
    "AtListOfChars",
    "AtListOfHashLists",
    "AtListOfLists",
    "AtListOfNumbers",
    "AtListOfPairs",
    "AtListOfRanges",
    "AtListOfSections",
    "AtListOfSectionsIB",
    "AtListOfStrings",
    "AtListOfSubLists",
    "AtLists",
    "AtManyChars",
    "AtManyItems",
    "AtManyLists",
    "AtManyNumbers",
    "AtManyObjects",
    "AtManyPairs",
    "AtManyPositions",
    "AtManyPositionsIB",
    "AtManyRanges",
    "AtManySections",
    "AtManySectionsIB",
    "AtManyStrings",
    "AtManySubLists",
    "AtManySubStrings",
    "AtManySubStringsIB",
    "AtNumber",
    "AtNumbers",
    "AtObject",
    "AtObjects",
    "AtPair",
    "AtPairs",
    "AtPosition",
    "AtPositionIB",
    "AtPositions",
    "AtPositionsIB",
    "AtRange",
    "AtRanges",
    "AtSection",
    "AtSectionIB",
    "AtSections",
    "AtSectionsIB",
    "AtString",
    "AtStrings",
    "AtSubList",
    "AtSubLists",
    "AtSubString",
    "AtSubStringIB",
    "AtSubStrings",
    "AtSubStringsIB",
    "AtTheseChars",
    "AtTheseItems",
    "AtTheseLists",
    "AtTheseNumbers",
    "AtTheseObjects",
    "AtThesePairs",
    "AtThesePositions",
    "AtThesePositionsIB",
    "AtTheseRanges",
    "AtTheseSections",
    "AtTheseSectionsIB",
    "AtTheseStrings",
    "AtTheseSubLists",
    "AtTheseSubStrings",
    "AtTheseSubStringsIB",
    "AtThisChar",
    "AtThisItem",
    "AtThisList",
    "AtThisNumber",
    "AtThisObject",
    "AtThisPair",
    "AtThisPosition",
    "AtThisPositionIB",
    "AtThisRange",
    "AtThisSection",
    "AtThisSectionIB",
    "AtThisString",
    "AtThisSubList",
    "AtThisSubString",
    "AtThisSubStringIB",
    "AtWhere",
    "AtWhereXT",
    "Backward",
    "Before",
    "BeforeChar",
    "BeforeChars",
    "BeforeCharsW",
    "BeforeCharsWhere",
    "BeforeCharsWhereXT",
    "BeforeCharsWXT",
    "BeforeEach",
    "BeforeFirst",
    "BeforeIB",
    "BeforeItem",
    "BeforeItemIB",
    "BeforeItems",
    "BeforeItemsIB",
    "BeforeLast",
    "BeforeMany",
    "BeforeManyPositions",
    "BeforeManyPositionsIB",
    "BeforeNth",
    "BeforePosition",
    "BeforePositionIB",
    "BeforePositions",
    "BeforePositionsIB",
    "BeforeSection",
    "BeforeSectionIB",
    "BeforeSections",
    "BeforeSectionsIB",
    "BeforeSubString",
    "BeforeSubStringIB",
    "BeforeSubStringPosition",
    "BeforeSubStrings",
    "BeforeSubStringsIB",
    "BeforeSubStringsPositions",
    "BeforeThese",
    "BeforeTheseItems",
    "BeforeTheseItemsIB",
    "BeforeThesePositions",
    "BeforeThesePositionsIB",
    "BeforeTheseSections",
    "BeforeTheseSubStrings",
    "BeforeTheseSubStringsIB",
    "BeforeTheseSubStringsPositions",
    "BeforeThisItem",
    "BeforeThisItemIB",
    "BeforeThisPosition",
    "BeforeThisPositionIB",
    "BeforeThisSection",
    "BeforeThisSubString",
    "BeforeThisSubStringIB",
    "BeforeThisSubStringPosition",
    "BeforeWhere",
    "BeforeWhereXT",
    "Between",
    "BetweenCS",
    "BetweenIB",
    "BetweenPosition",
    "BetweenPositionIB",
    "BetweenPositions",
    "BetweenPositionsIB",
    "BetweenSection",
    "BetweenSubString",
    "BetweenSubStrings",
    "BetweenSubStringsIB",
    "BetweenXT",
    "BoundedBy",
    "BoundedByIB",
    "Bounds",
    "BoundsIB",
    "By",
    "ByMany",
    "ByManyXT",
    "ByXT",
    "CS",
    "CaseSensitive",
    "Cell",
    "CellPart",
    "Cells",
    "CellValue",
    "Char",
    "CharAt",
    "CharAtPosition",
    "Chars",
    "Col",
    "ColNumber",
    "Cols",
    "ColsNumbers",
    "Column",
    "ColumnNumber",
    "Columns",
    "ColumnsNumbers",
    "Coming",
    "Concatenated",
    "ConcatenatedUsing",
    "ConcatenatedWith",
    "Direction",
    "Do",
    "DownTo",
    "Each",
    "EachNChars",
    "EachNItems",
    "Else",
    "End",
    "EndAt",
    "EndAtOccurrence",
    "EndAtPosition",
    "EndingAt",
    "EndingAtOccurrence",
    "EndingAtPosition",
    "EndOfLine",
    "EndOfList",
    "EndOfSentence",
    "EndOfString",
    "EndOfWord",
    "EndsAt",
    "EndsAtOccurrence",
    "EndsAtPosition",
    "Equals",
    "EqualTo",
    "Eval",
    "EvalDirection",
    "EvalFrom",
    "Evaluate",
    "EvaluateFrom",
    "EvaluationDirection",
    "Exactly",
    "Except",
    "Expression",
    "First",
    "FirstChars",
    "FirstNChars",
    "FirstPosition",
    "For",
    "ForEach",
    "Forward",
    "From",
    "FromEnd",
    "FromEndOfList",
    "FromEndOfString",
    "FromPosition",
    "FromPositionOfChar",
    "FromPositionOfItem",
    "FromPositionOfString",
    "FromPositions",
    "FromStart",
    "FromStartOfList",
    "FromStartOfString",
    "Going",
    "GrandTotal",
    "GreaterThan",
    "Grid",
    "Group",
    "Harvest",
    "HarvestSection",
    "HarvestSections",
    "HashList",
    "ID",
    "If",
    "In",
    "InA",
    "InAListOf",
    "InAListOfN",
    "InAListOfNItems",
    "InAListOfSize",
    "InAListOfSizeN",
    "InCell",
    "InCells",
    "InChar",
    "InCol",
    "InColNumber",
    "InCols",
    "InColsNumbers",
    "InColumn",
    "InColumnNumber",
    "InColumns",
    "InColumnsNumbers",
    "InHashList",
    "InList",
    "InListOf",
    "InListOfN",
    "InListOfNItems",
    "InListOfSize",
    "InListOfSizeN",
    "InNumber",
    "InObject",
    "InPair",
    "InPlan",
    "InPosition",
    "InPositions",
    "InRange",
    "InRow",
    "InRowNumber",
    "InRows",
    "InRowsNumbers",
    "InSection",
    "InSections",
    "InSet",
    "InSide",
    "InsideA",
    "InsideChar",
    "InsideHashList",
    "InsideList",
    "InsideNumber",
    "InsideObject",
    "InsidePair",
    "InsideSet",
    "InsideString",
    "InsideSubString",
    "InString",
    "InStringOf",
    "InStringOfSizeN",
    "InSubString",
    "InSubStrings",
    "InterTotal",
    "IsBoundedBy",
    "IsBoundOf",
    "IsFirstBoundOf",
    "IsGreaterThan",
    "IsLastBoundOf",
    "IsLeftBoundOf",
    "IsLessThan",
    "IsOfItem",
    "IsRightBoundOf",
    "It",
    "Item",
    "ItemAt",
    "ItemAtPosition",
    "ItemFrom",
    "ItemFromPosition",
    "Items",
    "Jump",
    "Label",
    "Last",
    "LastChars",
    "LastNChars",
    "LastPosition",
    "LastSep",
    "LessThan",
    "Like",
    "List",
    "ListOfLists",
    "ListSize",
    "MadeOf",
    "N",
    "Name",
    "Named",
    "NamedAs",
    "NCharsAfter",
    "NCharsBefore",
    "Next",
    "NextNth",
    "NFirstChars",
    "NFirstItems",
    "NLastChars",
    "NLastItems",
    "Nor",
    "Not",
    "NStep",
    "NSteps",
    "Nth",
    "NthNext",
    "NthOccurrence",
    "NthPrevious",
    "NthToFirst",
    "NthToLast",
    "Number",
    "NumberOfChars",
    "NumberOfItems",
    "Numbers",
    "Object",
    "Occurrence",
    "Of",
    "OfCell",
    "OfCellPart",
    "OfCells",
    "OfCellValue",
    "OfChar",
    "OfCol",
    "OfColNumber",
    "OfCols",
    "OfColsNumbers",
    "OfColumn",
    "OfColumnNumber",
    "OfColumns",
    "OfColumnsNumbers",
    "OfHashList",
    "OfList",
    "OfNumber",
    "OfObject",
    "OfPair",
    "OfPart",
    "OfPlan",
    "OfRow",
    "OfRowNumber",
    "OfRows",
    "OfRowsNumbers",
    "OfSection",
    "OfSections",
    "OfSet",
    "OfSize",
    "OfString",
    "OfSubPart",
    "OfSubString",
    "OfSubStrings",
    "OfSubValue",
    "OfSubValues",
    "OfThese",
    "OfTheseChars",
    "OfTheseLetters",
    "OfTheseLists",
    "OfTheseNumbers",
    "OfTheseObjects",
    "OfTheseSubStrings",
    "OfValue",
    "On",
    "OnChar",
    "OnComplete",
    "OnError",
    "OnHashList",
    "OnList",
    "OnNumber",
    "OnObject",
    "OnPair",
    "OnPosition",
    "OnPositions",
    "OnSection",
    "OnSectionIB",
    "OnSections",
    "OnSectionsIB",
    "OnSet",
    "OnString",
    "OnSubString",
    "OnSuccess",
    "OnUpdate",
    "Or",
    "OrA",
    "OrAn",
    "OrThat",
    "OrThis",
    "Otherwise",
    "Pair",
    "ParamName",
    "Part",
    "Pattern",
    "Person",
    "Position",
    "PositionIB",
    "Positions",
    "PositionsIB",
    "Previous",
    "PreviousNth",
    "Respectively",
    "Return",
    "ReturnAs",
    "ReturnedAs",
    "ReturnItAs",
    "ReturnThemAs",
    "Row",
    "Rows",
    "Section",
    "SectionIB",
    "Sections",
    "SectionsIB",
    "Seed",
    "Separator",
    "Size",
    "Start",
    "StartAt",
    "StartAtOccurrence",
    "StartAtPosition",
    "StartFrom",
    "StartingAt",
    "StartingAtOccurrence",
    "StartingAtPosition",
    "StartingFrom",
    "StartOfList",
    "StartOfString",
    "StartsAtOccurrence",
    "StartsAtPosition",
    "StartsFrom",
    "Step",
    "Stepping",
    "Steps",
    "Stop",
    "StopAt",
    "StopAtOccurrence",
    "StoppingAt",
    "StoppingAtOccurrence",
    "StoppingAtPosition",
    "StopsAt",
    "StopsAtOccurrence",
    "String",
    "StringAt",
    "StringAtPosition",
    "Strings",
    "StringSize",
    "SubPart",
    "SubString",
    "SubStrings",
    "SubTotal",
    "SubValue",
    "SubValues",
    "Table",
    "Than",
    "That",
    "Then",
    "ThenHarvest",
    "ThenHarvestSection",
    "ThenHarvestSections",
    "ThenYield",
    "ThenYieldSection",
    "ThenYieldSections",
    "TheseChars",
    "TheseItems",
    "TheseLists",
    "TheseNumbers",
    "TheseObjects",
    "ThesePositions",
    "ThesePositionsIB",
    "TheseSections",
    "TheseSectionsIB",
    "TheseStrings",
    "TheseSubStrings",
    "This",
    "ThisChar",
    "ThisItem",
    "ThisList",
    "ThisNumber",
    "ThisObject",
    "ThisPosition",
    "ThisPositionIB",
    "ThisSection",
    "ThisSectionIB",
    "ThisString",
    "ThisSubString",
    "To",
    "ToChar",
    "ToCharAt",
    "ToCharAtPosition",
    "ToEach",
    "ToEnd",
    "ToEndOfLine",
    "ToEndOfList",
    "ToEndOfSentence",
    "ToEndOfString",
    "ToEndOfWord",
    "ToFirst",
    "ToItem",
    "ToItemAt",
    "ToItemAtPosition",
    "ToItems",
    "ToLast",
    "ToList",
    "ToMany",
    "ToNChars",
    "ToNItems",
    "ToNth",
    "ToNumber",
    "ToObject",
    "ToPair",
    "ToPosition",
    "ToPositionOf",
    "ToPositionOfChar",
    "ToPositionOfItem",
    "ToPositionOfString",
    "ToPositions",
    "ToSection",
    "ToSections",
    "ToSet",
    "ToStart",
    "ToStartOfList",
    "ToStartOfString",
    "ToString",
    "ToStringAt",
    "ToStringAtPosition",
    "ToStrings",
    "ToSubString",
    "ToSubStrings",
    "ToThis",
    "Type",
    "Under",
    "Until",
    "UntilChar",
    "UntilItem",
    "UntilList",
    "UntilNumber",
    "UntilObject",
    "UntilPosition",
    "UntilString",
    "UntilSubString",
    "UntilXT",
    "UpTo",
    "UpToChar",
    "UpToItem",
    "UpToList",
    "UpToN",
    "UpToNBounds",
    "UpToNChars",
    "UpToNItems",
    "UpToNumber",
    "UpToObject",
    "UpToPosition",
    "UpToString",
    "UpToSubString",
    "Using",
    "UsingItem",
    "UsingItems",
    "UsingMany",
    "UsingManyXT",
    "UsingString",
    "UsingStrings",
    "UsingSubString",
    "UsingSubStrings",
    "UsingTheseItems",
    "UsingTheseStrings",
    "UsingTheseSubStrings",
    "UsingThisItem",
    "UsingThisString",
    "UsingThisSubString",
    "Value",
    "Values",
    "When",
    "Where",
    "WhereXT",
    "While",
    "Width",
    "With",
    "WithChar",
    "WithHashList",
    "WithList",
    "WithMany",
    "WithManyXT",
    "WithNumber",
    "WithObject",
    "WithPair",
    "WithSet",
    "WithString",
    "WithSubString",
    "WithTheir",
    "Yield",
    "YieldSection",
    "YieldSections",
};

pub fn registerAll(eng: *meta.MetaEngine) !void {
    for (&all_keywords) |kw| {
        try eng.named_params.register(kw);
    }
}

// ─── Tests ───

test "all keywords register without collision" {
    var eng = meta.MetaEngine.init(std.testing.allocator);
    defer eng.deinit();

    try registerAll(&eng);

    try std.testing.expect(eng.isNamedParam("Of"));
    try std.testing.expect(eng.isNamedParam("At"));
    try std.testing.expect(eng.isNamedParam("CaseSensitive"));
    try std.testing.expect(eng.isNamedParam("CS"));
    try std.testing.expect(eng.isNamedParam("BetweenPositions"));
    try std.testing.expect(eng.isNamedParam("YieldSections"));
    try std.testing.expect(!eng.isNamedParam("NotAKeyword"));
    try std.testing.expect(!eng.isNamedParam(""));
}

test "keyword count matches table" {
    var eng = meta.MetaEngine.init(std.testing.allocator);
    defer eng.deinit();

    try registerAll(&eng);

    try std.testing.expectEqual(@as(u32, all_keywords.len), eng.named_params.entries.count());
}

test "keyword table is roughly ordered" {
    // Verify consecutive entries are not reversed (may have case-insensitive ties)
    var sorted_count: usize = 0;
    for (0..all_keywords.len - 1) |i| {
        const order = std.mem.order(u8, all_keywords[i], all_keywords[i + 1]);
        if (order == .lt or order == .eq) sorted_count += 1;
    }
    // At least 90% should be in order
    try std.testing.expect(sorted_count * 10 >= (all_keywords.len - 1) * 9);
}

test "keyword table has no empty entries" {
    for (&all_keywords) |kw| {
        try std.testing.expect(kw.len > 0);
    }
}

test "keyword table has no duplicates" {
    for (0..all_keywords.len) |i| {
        for (i + 1..all_keywords.len) |j| {
            try std.testing.expect(!std.mem.eql(u8, all_keywords[i], all_keywords[j]));
        }
    }
}

test "common named params are present" {
    var eng = meta.MetaEngine.init(std.testing.allocator);
    defer eng.deinit();
    try registerAll(&eng);

    // Most used params from stzLib
    try std.testing.expect(eng.isNamedParam("With"));
    try std.testing.expect(eng.isNamedParam("Using"));
    try std.testing.expect(eng.isNamedParam("In"));
    try std.testing.expect(eng.isNamedParam("From"));
    try std.testing.expect(eng.isNamedParam("To"));
    try std.testing.expect(eng.isNamedParam("By"));
    try std.testing.expect(eng.isNamedParam("Between"));
    try std.testing.expect(eng.isNamedParam("Where"));
    try std.testing.expect(eng.isNamedParam("Step"));
    try std.testing.expect(eng.isNamedParam("Direction"));
}

test "case sensitivity: params are case-exact" {
    var eng = meta.MetaEngine.init(std.testing.allocator);
    defer eng.deinit();
    try registerAll(&eng);

    // Exact case should match
    try std.testing.expect(eng.isNamedParam("CaseSensitive"));
    // Wrong case should not match
    try std.testing.expect(!eng.isNamedParam("casesensitive"));
    try std.testing.expect(!eng.isNamedParam("CASESENSITIVE"));
}

test "keyword count is substantial" {
    // The table should have hundreds of entries
    try std.testing.expect(all_keywords.len > 500);
}
