# made m1.ring ; run: cd libraries/stzlib/base/test/reflect && ring <this file>  (picture: math_matrix_product.png)
load "../../../stzlib.ring"
# chdir("<an output folder>") here, after the load, so the picture lands there (the engine DLL path breaks if Ring starts elsewhere: run from base/test/reflect)

o = StzMathFigureQ(:Function, [ :f = "x^3 - 3*x", :on = [ -2.2, 2.2 ], :mark = [ :zeros, :extrema ], :tangent = 1.5, :label = "y = x^3 - 3x" ])
? "" + len(o.ToPNG("math_function.png")) + " " + o.Why()
o = StzMathFigureQ(:NumberLine, [ :on = [ -3, 9 ], :points = [ 4, -2, 6.5, [ 0.5, "half" ] ], :jumps = [ [ 1, 6 ] ], :label = "the numbers from -3 to 9, and 1 + 5" ])
? "" + len(o.ToPNG("math_numberline.png")) + " " + o.Why()
o = StzMathFigureQ(:Fraction, [ :compare = [ [ 3, 4 ], [ 2, 3 ], [ 2, 4 ], [ 1, 2 ] ], :label = "which is more" ])
? "" + len(o.ToPNG("math_fraction.png")) + " " + o.Why()
o = StzMathFigureQ(:Matrix, [ :product = [ [ [ 1, 2 ], [ 3, 4 ] ], [ [ 5, 6 ], [ 7, 8 ] ] ], :show = [ 1, 2 ], :label = "a cell of a product" ])
? "" + len(o.ToPNG("math_matrix_product.png")) + " " + o.Why()
o = StzMathFigureQ(:BoxPlot, [ :groups = [ [ "morning", [ 12, 15, 14, 18, 16, 15, 13, 40 ] ], [ "noon", [ 20, 22, 25, 21, 23, 24, 22, 26 ] ] ], :label = "two groups of eight" ])
? "" + len(o.ToPNG("math_boxplot.png")) + " " + o.Why()
o = StzMathFigureQ(:Surface, [ :f = "x^2 - y^2", :x = [ -1, 1 ], :y = [ -1, 1 ], :samples = 16, :label = "z = x^2 - y^2" ])
? "" + len(o.ToPNG("math_surface.png")) + " " + o.Why()
o = StzMathFigureQ(:ComplexPlane, [ :roots = [ 1, 0, 0, -1 ], :unit = TRUE, :label = "the roots of z^3 = 1" ])
? "" + len(o.ToPNG("math_complexplane.png")) + " " + o.Why()
o = StzMathFigureQ(:StemPlot, [ :of = [ 112, 125, 131, 134, 138, 142, 145, 147, 150, 151, 153, 158, 162, 166, 171, 184, 197 ] ])
? "" + len(o.ToPNG("math_stemplot.png")) + " " + o.Why()
write("math_stemplot_text.txt", o.Text())
? o.Text()
