load "../../stzBase.ring"
load "../_narrated.ring"
load "_tblfix.ring"

# stzTable defect family: finding and counting cells. The text-in-text tests passed StzFindFirst the
# haystack first (the library contract is NEEDLE-FIRST), so every [ :SubValue, text ] form found nothing;
# FindCell and its relatives raised for a number because the list-of-lists helper they leaned on had the
# same inversion; the cell-level and cells-level forms named a parameter differently from the body (R24),
# called finders defined nowhere, or called a method without This. Every method also exists for a row, a
# list of rows, a column, a list of columns and a section, and those forms called themselves forever (R4).
#
#   3 x 3 :  1 2 3 / 4 5 6 / 7 8 9         (numbers)
#   4 x 2 :  x y / z w / x q / r y         (text)
#   ow    :  name = Andy Ali Alia   job = Maestro Abraham Ali      (texts that contain texts)

Scenario("A text inside a cell: the needle goes first")
	Given("the people table, whose names and jobs share the text Ali")
	Tn("FindInCol with :SubValue finds the cells that contain the text", Does("ow.FindInCol(:name, [ :SubValue, 'Ali' ])"), "[ 2, 3 ]")
	Tn("in the other column", Does("ow.FindInCol(:job, [ :SubValue, 'Ali' ])"), "[ 3 ]")
	Tn("the default is case-sensitive", Does("ow.FindInCol(:name, [ :SubValue, 'ALI' ])"), "[ ]")
	Tn("FindInColCS with the flag off ignores case", Does("ow.FindInColCS(:name, [ :SubValue, 'ALI' ], 0)"), "[ 2, 3 ]")
	Tn("the whole-value form still means equality", Does("ow.FindInCol(:name, 'Ali')"), "[ 2 ]")
	Tn("NumberOfOccurrenceInCol counts cells that contain the text", Does("ow.NumberOfOccurrenceInCol(:name, [ :OfSubValue, 'Ali' ])"), "2")
	Tn("not the cells equal to it", Does("ow.NumberOfOccurrenceInCol(:name, 'Ali')"), "1")
	Tn("NumberOfOccurrenceInRow counts across the row", Does("ow.NumberOfOccurrenceInRow(3, [ :OfSubValue, 'Ali' ])"), "2")
	Tn("a row with one cell that contains it", Does("ow.NumberOfOccurrenceInRow(2, [ :OfSubValue, 'Ali' ])"), "1")
	Tn("NumberOfOccurrenceInCell answers 1 for a cell that contains the text", Does("ow.NumberOfOccurrenceInCell(1, 3, [ :OfSubValue, 'li' ])"), "1")
	Tn("and 0 for a cell that does not", Does("ow.NumberOfOccurrenceInCell(1, 1, [ :OfSubValue, 'li' ])"), "0")
EndScenario()

Scenario("Cells that are numbers")
	Given("the 3 x 3 table, where FindCell raised for a number")
	Tn("FindCell finds a number", Does("o.FindCell(5)"), "[ [ 2, 2 ] ]")
	Tn("FindAll too", Does("o.FindAll(5)"), "[ [ 2, 2 ] ]")
	Tn("FindCells finds several, column by column", Does("o.FindCells([ 2, 9 ])"), "[ [ 2, 1 ], [ 3, 3 ] ]")
	Tn("FindNthCell", Does("o.FindNthCell(1, 5)"), "[ 2, 2 ]")
	Tn("an occurrence that does not exist gives [ ]", Does("o.FindNthCell(2, 5)"), "[ ]")
	Tn("FindFirst", Does("o.FindFirst(8)"), "[ 2, 3 ]")
	Tn("FindFirstCell", Does("o.FindFirstCell(1)"), "[ 1, 1 ]")
	Tn("FindLast", Does("o.FindLast(5)"), "[ 2, 2 ]")
	Tn("FindLastCell", Does("o.FindLastCell(9)"), "[ 3, 3 ]")
	Tn("NumberOfOccurrence", Does("o.NumberOfOccurrence(5)"), "1")
	Tn("NumberOfOccurrenceOfCell", Does("o.NumberOfOccurrenceOfCell(7)"), "1")
	Tn("Contains", Does("o.Contains(5)"), "1")
	Tn("a number that is not there", Does("o.Contains(10)"), "0")
	Tn("text cells keep working on the 4 x 2 table", Does("o4.FindCell('x')"), "[ [ 1, 1 ], [ 1, 3 ] ]")
	Tn("and the second occurrence", Does("o4.FindNthCell(2, 'x')"), "[ 1, 3 ]")
EndScenario()

Scenario("Several texts, and the occurrence of a text")
	Given("the people table")
	Tn("FindSubValues finds the cells that contain any of the texts",
		Does("ow.FindSubValues([ 'Ali', 'And' ])"), "[ [ [ 1, 2 ], [ 1 ] ], [ [ 1, 3 ], [ 1 ] ], [ [ 2, 3 ], [ 1 ] ], [ [ 1, 1 ], [ 1 ] ] ]")
	Tn("a cell that holds two of the texts is listed once, with all the places",
		Does("ow.FindSubValues([ 'A', 'li' ])"), "[ [ [ 1, 1 ], [ 1 ] ], [ [ 1, 2 ], [ 1, 2 ] ], [ [ 2, 2 ], [ 1 ] ], [ [ 1, 3 ], [ 1, 2 ] ], [ [ 2, 3 ], [ 1, 2 ] ] ]")
	Tn("FindNth takes [ :SubValue, text ]", Does("ow.FindNth(2, [ :SubValue, 'Ali' ])"), "[ [ 1, 3 ], 1 ]")
	Tn("and [ :Cell, value ]", Does("ow.FindNth(2, [ :Cell, 'Ali' ])"), "[ 2, 3 ]")
	Tn("FindNthOccurrenceOfSubValue", Does("ow.FindNthOccurrenceOfSubValue(2, 'Ali')"), "[ [ 1, 3 ], 1 ]")
	Tn("FindFirstOccurrenceOfSubValue", Does("ow.FindFirstOccurrenceOfSubValue('Ali')"), "[ [ 1, 2 ], 1 ]")
	Tn("FindLastOccurrenceOfSubValue", Does("ow.FindLastOccurrenceOfSubValue('Ali')"), "[ [ 2, 3 ], 1 ]")
EndScenario()

Scenario("A list of cells")
	Given("the cells [ 1, 2 ], [ 2, 3 ] and [ 1, 3 ] of the people table")
	Tn("OccurrencesInCells takes the cells", Does("ow.OccurrencesInCells([ [ 1, 2 ], [ 2, 3 ] ], 'Ali')"), "[ [ [ 1, 2 ], [ 1 ] ], [ [ 2, 3 ], [ 1 ] ] ]")
	Tn("FindValueInCells takes the cells and the value", Does("ow.FindValueInCells([ [ 1, 2 ], [ 2, 3 ] ], 'Ali')"), "[ [ 1, 2 ], [ 2, 3 ] ]")
	Tn("PositionsOfValueInCells", Does("ow.PositionsOfValueInCells([ [ 1, 2 ], [ 1, 3 ] ], 'Ali')"), "[ [ 1, 2 ] ]")
	Tn("FindNthOccurrenceOfValueInCells", Does("ow.FindNthOccurrenceOfValueInCells(2, [ [ 1, 2 ], [ 2, 3 ] ], 'Ali')"), "[ 2, 3 ]")
	Tn("FindNthValueInCells looks only in the given cells", Does("ow.FindNthValueInCells(1, [ [ 2, 3 ] ], 'Ali')"), "[ 2, 3 ]")
	Tn("FindFirstValueInCells", Does("ow.FindFirstValueInCells([ [ 2, 3 ], [ 1, 2 ] ], 'Ali')"), "[ 2, 3 ]")
	Tn("FindFirstOccurrenceOfValueInCells", Does("ow.FindFirstOccurrenceOfValueInCells([ [ 2, 3 ], [ 1, 2 ] ], 'Ali')"), "[ 2, 3 ]")
	Tn("FindLastValueInCells", Does("ow.FindLastValueInCells([ [ 1, 2 ], [ 2, 3 ], [ 1, 3 ] ], 'Ali')"), "[ 2, 3 ]")
	Tn("FindLastOccurrenceOfValueInCells", Does("ow.FindLastOccurrenceOfValueInCells([ [ 1, 2 ], [ 2, 3 ] ], 'Ali')"), "[ 2, 3 ]")
	Tn("NumberOfOccurrencesOfSubValueInCells counts the places of the text",
		Does("ow.NumberOfOccurrencesOfSubValueInCells([ [ 1, 2 ], [ 2, 3 ], [ 1, 3 ] ], 'Ali')"), "3")
	Tn("not the cells equal to it", Does("ow.NumberOfOccurrencesOfSubValueInCells([ [ 1, 1 ] ], 'Ali')"), "0")
	Tn("NumberOfOccurrencesInCells", Does("ow.NumberOfOccurrencesInCells([ [ 1, 2 ], [ 2, 3 ] ], 'Ali')"), "2")
	Tn("FindFirstOccurrenceOfSubValueInCells", Does("ow.FindFirstOccurrenceOfSubValueInCells([ [ 1, 2 ], [ 2, 3 ], [ 1, 3 ] ], 'Ali')"), "[ [ 1, 2 ], 1 ]")
	Tn("FindLasttOccurrenceOfSubValueInCells (the older spelling)",
		Does("ow.FindLasttOccurrenceOfSubValueInCells([ [ 1, 2 ], [ 2, 3 ], [ 1, 3 ] ], 'li')"), "[ [ 1, 3 ], 2 ]")
	Tn("FindNthOccurrenceOfSubValueInCells", Does("ow.FindNthOccurrenceOfSubValueInCells(2, [ [ 1, 2 ], [ 2, 3 ], [ 1, 3 ] ], 'li')"), "[ [ 2, 3 ], 2 ]")
	Tn("FindFirstInCells with a value", Does("ow.FindFirstInCells([ [ 2, 3 ], [ 1, 2 ] ], 'Ali')"), "[ 2, 3 ]")
	Tn("FindLastInCells with a value", Does("ow.FindLastInCells([ [ 1, 2 ], [ 2, 3 ] ], 'Ali')"), "[ 2, 3 ]")
	Tn("the spelling FindFirstOccurrenceInCells", Does("ow.FindFirstOccurrenceInCells([ [ 2, 3 ], [ 1, 2 ] ], 'Ali')"), "[ 2, 3 ]")
	Tn("and FindLastOccurrenceInCells", Does("ow.FindLastOccurrenceInCells([ [ 1, 2 ], [ 2, 3 ] ], 'Ali')"), "[ 2, 3 ]")
EndScenario()

Scenario("One cell")
	Given("the cell [ 1, 3 ] of the people table holds Alia")
	Tn("FindLastInCell takes :Last inside", Does("ow.FindLastInCell(1, 3, 'a')"), "4")
	Tn("FindFirstInCell", Does("ow.FindFirstInCell(1, 3, 'A')"), "1")
	Tn("FindNthInCell", Does("ow.FindNthInCell(2, 2, 2, 'a')"), "6")
	Tn("FindLastInCell on a cell with two of them", Does("ow.FindLastInCell(2, 2, 'a')"), "6")
	Tn("FindFirstInCell on the same cell", Does("ow.FindFirstInCell(2, 2, 'a')"), "4")
	Tn("an occurrence that is not there is 0, not an error", Does("ow.FindNthInCell(2, 1, 1, 'z')"), "0")
	Tn("FindFirstInCell for a text that is absent", Does("ow.FindFirstInCell(1, 1, 'zzz')"), "0")
	Tn("NumberOfOccurrencesInCell with a text", Does("ow.NumberOfOccurrencesInCell(1, 3, [ :SubValue, 'a' ])"), "1")
	Tn("NumberOfOccurrencesInCell with the whole value", Does("ow.NumberOfOccurrencesInCell(1, 3, 'Alia')"), "1")
	Tn("a value that is not the cell counts 0", Does("ow.NumberOfOccurrencesOfValueInCell(1, 3, 'Ali')"), "0")
	Tn("NumberOfOccurrencesOfValueInCell for the right value", Does("ow.NumberOfOccurrencesOfValueInCell(1, 3, 'Alia')"), "1")
	Tn("NumberOfOccurrencesOfSubValueInCell counts the places", Does("ow.NumberOfOccurrencesOfSubValueInCell(1, 3, 'A')"), "1")
	Tn("a text in a cell, counted", Does("ow.NumberOfOccurrencesOfSubValueInCell(1, 3, 'a')"), "1")
	Tn("CellContains with a value answers", Does("ow.CellContains(1, 3, 'Alia')"), "1")
	Tn("CellContains with a text answers", Does("ow.CellContains(1, 3, [ :SubValue, 'li' ])"), "1")
	Tn("CellContains answers 0 when the text is absent, not an error", Does("ow.CellContains(1, 3, [ :SubValue, 'zzz' ])"), "0")
	Tn("CellContainsValueCS without case", Does("ow.CellContainsValueCS(1, 3, 'alia', 0)"), "1")
	Tn("and with case", Does("ow.CellContainsValueCS(1, 3, 'alia', 1)"), "0")
	Tn("CellContainValue", Does("ow.CellContainValue(1, 3, 'Alia')"), "1")
	Tn("CellContainsSubValue answers 0 when absent", Does("ow.CellContainsSubValue(1, 3, 'zzz')"), "0")
	Tn("ContainsSubValueInCell", Does("ow.ContainsSubValueInCell(1, 3, 'ia')"), "1")
EndScenario()

Scenario("One row and a list of rows")
	Given("the people table, whose row 3 is Alia and Ali")
	Tn("FindValueInRow", Does("ow.FindValueInRow(2, 'Ali')"), "[ [ 1, 2 ] ]")
	Tn("FindSubValueInRow looks inside the cells", Does("ow.FindSubValueInRow(2, 'Ab')"), "[ [ [ 2, 2 ], [ 1 ] ] ]")
	Tn("FindNthValueInRow reads the row it is given", Does("ow.FindNthValueInRow(1, 3, 'Ali')"), "[ 2, 3 ]")
	Tn("FindNthSubValueInRow", Does("ow.FindNthSubValueInRow(2, 3, 'li')"), "[ [ 2, 3 ], 2 ]")
	Tn("FindFirstValueInRow", Does("ow.FindFirstValueInRow(3, 'Ali')"), "[ 2, 3 ]")
	Tn("FindFirstSubValueInRow", Does("ow.FindFirstSubValueInRow(3, 'li')"), "[ [ 1, 3 ], 2 ]")
	Tn("FindLastValueInRow", Does("ow.FindLastValueInRow(3, 'Ali')"), "[ 2, 3 ]")
	Tn("FindLastSubValueInRow", Does("ow.FindLastSubValueInRow(3, 'li')"), "[ [ 2, 3 ], 2 ]")
	Tn("NumberOfOccurrenceOfCellInRow", Does("ow.NumberOfOccurrenceOfCellInRow(3, 'Ali')"), "1")
	Tn("NumberOfOccurrenceOfValueInRow", Does("ow.NumberOfOccurrenceOfValueInRow(3, 'Ali')"), "1")
	Tn("CountOfValueInRowInRow", Does("ow.CountOfValueInRowInRow(3, 'Ali')"), "1")
	Tn("FindValueInRows", Does("ow.FindValueInRows([ 2, 3 ], 'Ali')"), "[ [ 1, 2 ], [ 2, 3 ] ]")
	Tn("FindNthInRows", Does("ow.FindNthInRows(2, [ 2, 3 ], 'Ali')"), "[ 2, 3 ]")
	Tn("FindNthInRows with a text", Does("ow.FindNthInRows(2, [ 2, 3 ], [ :SubValue, 'Ali' ])"), "[ [ 1, 3 ], 1 ]")
	Tn("FindFirstInRows", Does("ow.FindFirstInRows([ 2, 3 ], 'Ali')"), "[ 1, 2 ]")
	Tn("FindFirstValueInRows", Does("ow.FindFirstValueInRows([ 2, 3 ], 'Ali')"), "[ 1, 2 ]")
	Tn("FindFirstSubValueInRows", Does("ow.FindFirstSubValueInRows([ 1, 3 ], 'li')"), "[ [ 1, 3 ], 2 ]")
	Tn("FindLastInRows", Does("ow.FindLastInRows([ 2, 3 ], 'Ali')"), "[ 2, 3 ]")
	Tn("FindLastValueInRows", Does("ow.FindLastValueInRows([ 2, 3 ], 'Ali')"), "[ 2, 3 ]")
	Tn("FindLastSubValueInRows", Does("ow.FindLastSubValueInRows([ 2, 3 ], 'li')"), "[ [ 2, 3 ], 2 ]")
	Tn("NumberOfOccurrenceOfCellInRows", Does("ow.NumberOfOccurrenceOfCellInRows([ 2, 3 ], 'Ali')"), "2")
EndScenario()

Scenario("One column and a list of columns")
	Given("the people table")
	Tn("FindValueInCol", Does("ow.FindValueInCol(:job, 'Ali')"), "[ [ 2, 3 ] ]")
	Tn("FindSubValueInCol looks inside the cells", Does("ow.FindSubValueInCol(:name, 'li')"), "[ [ [ 1, 2 ], [ 2 ] ], [ [ 1, 3 ], [ 2 ] ] ]")
	Tn("FindFirstValueInCol", Does("ow.FindFirstValueInCol(:job, 'Ali')"), "[ 2, 3 ]")
	Tn("FindFirstSubValueInCol", Does("ow.FindFirstSubValueInCol(:name, 'li')"), "[ [ 1, 2 ], 2 ]")
	Tn("FindLastValueInCol", Does("ow.FindLastValueInCol(:name, 'Ali')"), "[ 1, 2 ]")
	Tn("FindLastSubValueInCol", Does("ow.FindLastSubValueInCol(:name, 'li')"), "[ [ 1, 3 ], 2 ]")
	Tn("NumberOfOccurrenceOfCellInCol", Does("ow.NumberOfOccurrenceOfCellInCol(:name, 'Ali')"), "1")
	Tn("FindValueInCols", Does("ow.FindValueInCols([ :name, :job ], 'Ali')"), "[ [ 1, 2 ], [ 2, 3 ] ]")
	Tn("FindNthInCols takes names and positions alike", Does("ow.FindNthInCols(2, [ :name, 2 ], 'Ali')"), "[ 2, 3 ]")
	Tn("FindFirstInCols", Does("ow.FindFirstInCols([ 1, 2 ], 'Ali')"), "[ 1, 2 ]")
	Tn("FindFirstValueInCols", Does("ow.FindFirstValueInCols([ 1, 2 ], 'Ali')"), "[ 1, 2 ]")
	Tn("FindFirstSubValueInCols", Does("ow.FindFirstSubValueInCols([ 1, 2 ], 'Ali')"), "[ [ 1, 2 ], 1 ]")
	Tn("FindLastInCols", Does("ow.FindLastInCols([ 1, 2 ], 'Ali')"), "[ 2, 3 ]")
	Tn("FindLastValueInCols", Does("ow.FindLastValueInCols([ 1, 2 ], 'Ali')"), "[ 2, 3 ]")
	Tn("FindLastSubValueInCols", Does("ow.FindLastSubValueInCols([ 1, 2 ], 'Ali')"), "[ [ 2, 3 ], 1 ]")
	Tn("NumberOfOccurrenceOfCellInCols", Does("ow.NumberOfOccurrenceOfCellInCols([ 1, 2 ], 'Ali')"), "2")
EndScenario()

Scenario("A section")
	Given("the section from [ 1, 1 ] to [ 2, 3 ], which is the whole people table")
	Tn("FindValueInSection", Does("ow.FindValueInSection([ 1, 1 ], [ 2, 3 ], 'Ali')"), "[ [ 1, 2 ], [ 2, 3 ] ]")
	Tn("FindNthValueInSection reads the corners it is given", Does("ow.FindNthValueInSection(2, [ 1, 1 ], [ 2, 3 ], 'Ali')"), "[ 2, 3 ]")
	Tn("FindNthSubValueInSection", Does("ow.FindNthSubValueInSection(2, [ 1, 1 ], [ 2, 3 ], 'Ali')"), "[ [ 1, 3 ], 1 ]")
	Tn("a smaller section leaves cells out", Does("ow.FindValueInSection([ 1, 1 ], [ 1, 2 ], 'Ali')"), "[ [ 1, 2 ] ]")
	Tn("FindFirstValueInSection", Does("ow.FindFirstValueInSection([ 1, 1 ], [ 2, 3 ], 'Ali')"), "[ 1, 2 ]")
	Tn("FindFirstSubValueInSection", Does("ow.FindFirstSubValueInSection([ 1, 1 ], [ 2, 3 ], 'Ali')"), "[ [ 1, 2 ], 1 ]")
	Tn("FindLastValueInSection", Does("ow.FindLastValueInSection([ 1, 1 ], [ 2, 3 ], 'Ali')"), "[ 2, 3 ]")
	Tn("FindLastSubValueInSection", Does("ow.FindLastSubValueInSection([ 1, 1 ], [ 2, 3 ], 'Ali')"), "[ [ 2, 3 ], 1 ]")
	Tn("NumberOfOccurrenceOfCellInSection", Does("ow.NumberOfOccurrenceOfCellInSection([ 1, 1 ], [ 2, 3 ], 'Ali')"), "2")
	Tn("NumberOfOccurrenceOfValueInSection", Does("ow.NumberOfOccurrenceOfValueInSection([ 1, 1 ], [ 2, 3 ], 'Ali')"), "2")
	Tn("CountOfValueInSectionInSection", Does("ow.CountOfValueInSectionInSection([ 1, 1 ], [ 2, 3 ], 'Ali')"), "2")
	Tn("on the 3 x 3 table, a block of numbers", Does("o.FindValueInSection([ 2, 2 ], [ 3, 3 ], 9)"), "[ [ 3, 3 ] ]")
EndScenario()

Summary()
