# Generate engine locale tables.
#
# OFFLINE, and the output is COMMITTED -- the same shape utf8proc_data.c and the
# tree-sitter parser.c files already have in this tree. There is no build-time
# codegen step in build.zig and this does not add one.
#
#   python gen_locale_tables.py            # regenerate src/locale_data.zig
#
# SOURCE: today this reads the Ring table it replaces, so the seam can be proved
# without waiting on CLDR. When the CLDR subset lands, only read_rows() changes
# -- everything below it, and the engine API above it, stays put. The source and
# its version are stamped into the generated file's header so a reader never has
# to guess where a row came from.

import io, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ENGINE = os.path.dirname(HERE)
RING_SRC = os.path.join(ENGINE, "..", "base", "i18n", "stzLocale.ring")
OUT = os.path.join(ENGINE, "src", "locale_data.zig")

SOURCE_NAME = "base/i18n/stzLocale.ring $_aCurrencyISOData"
SOURCE_VERSION = "2026-08-10"

ROW = re.compile(r'^\s*\[\s*:([A-Za-z_0-9]+)\s*,\s*"([^"]*)"\s*,\s*"([^"]*)"\s*\]')


def read_rows():
    """[(name, iso_code, symbol)] -- swap this for a CLDR reader; nothing below
    it needs to know."""
    src = io.open(RING_SRC, encoding='utf-8', newline='').read().replace('\r\n', '\n')
    start = src.index('$_aCurrencyISOData = [')
    rows = []
    depth = 0
    for line in src[start:].split('\n'):
        depth += line.count('[') - line.count(']')
        m = ROW.match(line)
        if m:
            rows.append((m.group(1), m.group(2), m.group(3)))
        if depth <= 0 and rows:
            break
    return rows


def zig_escape(s):
    return s.replace('\\', '\\\\').replace('"', '\\"')


def main():
    rows = read_rows()
    if len(rows) < 100:
        sys.exit("refusing to generate from %d rows -- the parse is wrong" % len(rows))

    # A property the data must hold, checked HERE so a bad row can never reach
    # the engine: a currency's symbol is not its own ISO code. 36 rows failed
    # this before 451501ecb, and the generator is the right place to make that
    # unrepeatable.
    bad = [r for r in rows if r[2].upper() == r[1].upper()]
    if bad:
        sys.exit("refusing: %d row(s) carry the ISO code as the symbol: %s"
                 % (len(bad), ', '.join(r[0] for r in bad[:5])))

    seen = {}
    for name, iso, sym in rows:
        if iso in seen and seen[iso] != sym:
            sys.exit("refusing: ISO code %s appears twice with different symbols" % iso)
        seen[iso] = sym

    out = []
    out.append("// GENERATED by tools/gen_locale_tables.py -- do not edit by hand.")
    out.append("//")
    out.append("// Source:  " + SOURCE_NAME)
    out.append("// Version: " + SOURCE_VERSION)
    out.append("// Rows:    %d" % len(rows))
    out.append("//")
    out.append("// Committed rather than built, like utf8proc_data.c and the tree-sitter")
    out.append("// parsers beside it. Regenerate with the tool above; never edit here.")
    out.append("")
    out.append("pub const Currency = struct {")
    out.append("    name: []const u8,")
    out.append("    iso: []const u8,")
    out.append("    symbol: []const u8,")
    out.append("};")
    out.append("")
    out.append("pub const currencies = [_]Currency{")
    for name, iso, sym in rows:
        out.append('    .{ .name = "%s", .iso = "%s", .symbol = "%s" },'
                   % (zig_escape(name), zig_escape(iso), zig_escape(sym)))
    out.append("};")
    out.append("")

    io.open(OUT, 'w', encoding='utf-8', newline='\n').write('\n'.join(out))
    print("wrote %s -- %d currencies" % (os.path.relpath(OUT, ENGINE), len(rows)))


main()
