# made k1.ring ; run: cd libraries/stzlib/base/test/reflect && ring <this file>  (picture: kg_canvas.png)
load "../../../stzlib.ring"
# chdir("<an output folder>") here, after the load, so the picture lands there (the engine DLL path breaks if Ring starts elsewhere: run from base/test/reflect)
oF = new stzFont("C:/Windows/Fonts/segoeui.ttf")
o1 = new stzKnowledgeGraph("zoo")
o1.AddFact("Dog", "is-a", "Animal")
o1.AddFact("Cat", "is-a", "Animal")
o1.AddFact("Dog", "eats", "Meat")
o1.AddFact("Cat", "eats", "Fish")
o1.AddFact("Animal", "lives-in", "Zoo")
? @@( o1.Query([ "?x", "is-a", "Animal" ]) )
write("kg_ascii.txt", o1.AsciiArt())
? o1.AsciiArt()
write("kg_zoo.dot", o1.Dot())
? o1.Dot()
oGC = o1.GraphCanvas([ :Layout = :Hierarchical, :SizeBy = :Degree, :ColorBy = :Degree, :Font = oF, :Margin = 70 ])
oGC.SetSize(760, 480)
? len(oGC.ToPNG("kg_canvas.png"))
