# Narrative
# --------
# pr()
#
# Extracted from stzchartest.ring, block #111.

load "../../stzBase.ring"


? CharsNames(InvisibleChars())
#-->
'
<control>
NO-BREAK SPACE
EN QUAD
EM QUAD
EN SPACE
EM SPACE
THREE-PER-EM SPACE
FOUR-PER-EM SPACE
SIX-PER-EM SPACE
FIGURE SPACE
PUNCTUATION SPACE
THIN SPACE
HAIR SPACE
ZERO WIDTH SPACE
ZERO WIDTH NON-JOINER
ZERO WIDTH JOINER
LEFT-TO-RIGHT MARK
RIGHT-TO-LEFT MARK
LINE SEPARATOR
PARAGRAPH SEPARATOR
NARROW NO-BREAK SPACE
MEDIUM MATHEMATICAL SPACE
IDEOGRAPHIC SPACE
HANGUL FILLER
HANGUL CHOSEONG FILLER
HALFWIDTH HANGUL FILLER
'

pf()
# Executed in 0.72 second(s) in Ring 1.23
