# The NATIVE half of the G5 edge-convergence proof (SOFTANZA_GPU_PLAN.md).
#
# Emits edge_proof/fixture.js: a kernel SPEC, the native engine's WGSL for
# it, f32-exact inputs, and the natively computed GPU results. The browser
# harness (edge_proof.html) then proves convergence:
#   1. stz.wasm (the freestanding build of the SAME transpiler) turns the
#      same spec into BYTE-IDENTICAL WGSL, and
#   2. the browser's WebGPU runs that kernel to results EXACTLY equal to
#      the native run's.
#
# To run the proof (needs a WebGPU browser; result 2026-08-07 on this
# machine: 5/5 PASS):
#   cd base/test/gpu ; ring edge_proof/gen_fixture.ring
#   cp ../../../engine/zig-out/bin/stz.wasm edge_proof/   (zig build wasm)
#   serve edge_proof/ over http and open edge_proof.html
#
# RUN FROM base/test/gpu (the engine-dir sensitivity applies).

load "../../stzBase.ring"

k = StzKernelMakerQ()
k.TakesVector(:A)
k.TakesVector(:B)
k.TakesScalar(:alpha)
k.ReturnsVector(:C)
k.ForEachElement('{ @C = alpha * @A + @B }')

cSpec = k.Spec()
cWgsl = k.ToWGSL()

nN = 256
aA = []
aB = []
for i = 1 to nN
    aA + ((i-1) / 2.0)
    aB + ((i-1) / 4.0)
next
oG = new stzGpu
if NOT oG.IsAvailable()
    ? "no GPU on this machine -- the fixture needs the native results"
    return
ok
aC = oG.Run(k, [ :A = aA, :B = aB, :alpha = 2.5 ])

cOut = "// generated by gen_fixture.ring -- the NATIVE side of the G5 proof" + char(10)
cOut += "export const spec = " + char(34) + _JsEscape(cSpec) + char(34) + ";" + char(10)
cOut += "export const nativeWgsl = " + char(34) + _JsEscape(cWgsl) + char(34) + ";" + char(10)
cOut += "export const alpha = 2.5;" + char(10)
cOut += "export const a = [" + _JoinNums(aA) + "];" + char(10)
cOut += "export const b = [" + _JoinNums(aB) + "];" + char(10)
cOut += "export const expected = [" + _JoinNums(aC) + "];" + char(10)
write("edge_proof/fixture.js", cOut)
? "fixture written: spec " + len(cSpec) + " chars, wgsl " + len(cWgsl) + " chars, " +
    len(aC) + " expected values"

func _JsEscape pcS
    _c_ = StzReplace(pcS, "\", "\\")
    _c_ = StzReplace(_c_, char(34), "\" + char(34))
    _c_ = StzReplace(_c_, char(10), "\n")
    return _c_

func _JoinNums paList
    _c_ = ""
    _n_ = len(paList)
    for _i_ = 1 to _n_
        if _i_ > 1
            _c_ += ","
        ok
        _c_ += "" + paList[_i_]
    next
    return _c_
