oGBad = new stzAgentGraph("bad")
oGBad.AddLLMActor("drafter")
oGBad.AddEffect("post")
oGBad.Proposes("drafter", "post")
oGOk = new stzAgentGraph("ok")
oGOk.AddLLMActor("drafter")
oGOk.AddGuardian("reviewer")
oGOk.AddEffect("post")
oGOk.AddTraceSink("audit")
oGOk.Proposes("drafter", "reviewer")
oGOk.Guards("reviewer", "post")
oGOk.Feeds("reviewer", "post")
oGOk.Traces("post", "audit")
? oGBad.IsSound()
? oGOk.IsSound()
